---
permalink: faq/faq-configuration-and-supported-devices.html 
sidebar: sidebar 
keywords:  
summary: このFAQでは、OnCommand Insight 構成とサポートされているデバイスに関する一般的な質問に回答します。 
---
= 構成とサポートされているデバイス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このFAQでは、OnCommand Insight 構成とサポートされているデバイスに関する一般的な質問に回答します。



== OCIによって環境が変更されるか。

いいえOCIは、環境に関する情報を収集する読み取り専用のツールです。OCIでアセットや設定を変更することはありません。



== OCIでデバイスに必要な権限レベルのアクセス権を教えてください。

デバイスがサポートしている場合、ほとんどの場合、読み取り専用アクセスが必要です。読み取り専用アクセスを許可しないソリューションもあるため、適切な昇格されたアクセス許可が必要になります。



== OCIはどのくらいの頻度で情報を収集しますか。

OCIでは通常、5分ごとにパフォーマンスデータが収集され、論理構造と物理構造の検出は0.5時間ごとに行われますOCIでは、推奨されるベストプラクティスと拡張性に従ってデフォルトのポーリング間隔が設定されますが、それらの間隔をユーザが完全に制御することはできます。



== OCIが環境に与える影響

OCIのエージェントレス、アウトオブバンド、パッシブなIP通信は、セットアップ、メンテナンス、データセンターのエコシステムへの影響を最小限に抑えるのに役立つ。OCIのパフォーマンス開発チームは、パフォーマンス自体の監視アクティビティにおいて、データセンターのパフォーマンスへの影響を最小限に抑えるための優れた対策を講じている。通常の運用環境では影響はごくわずかで、利用率の高いテクノロジプラットフォームやパフォーマンスの低いテクノロジプラットフォームで、リラックスした状態や強化が可能です。詳細については、『OnCommand Insight インストールガイド』を参照してください。



== OCIですべてのホスト/ VMを一覧表示するにはどうすればよいですか。

OCIにはウィジェットやクエリリスト機能が補完されており、データセンターアセットのインベントリ形式の一覧を表示できます。スピンドルとその間に配置されたさまざまな構成要素を仮想マシンで一覧表示することができ、クエリ、ウィジェット、ダッシュボード、データウェアハウスレポートにアクセスできます。 RESTful API からアクセスできます。



== OCIでは、関連する非ハイパーバイザーホスト（物理サーバ）に対して同じタイプのサポートを提供していますか。

VMwareなどのハイパーバイザーは、ESXiホストとそれに関連する仮想マシン（VM）に関する詳細情報を提供します。物理サーバについては、ホストHBAまでの指標が収集されます。OCIでは、特許申請中のテクノロジを使用して物理サーバを検出する独自の方法を採用しています。ストレージやスイッチが検出されると、物理サーバのホスト名がファブリックエイリアス情報に含まれます。OCIによってこれらのホスト名が選択され、DNSで一致すると、ホストが自動的にOCIに追加されます。この方法により、手動での入力更新やツールインベントリのメンテナンスが必要なくなります。



== 異機種混在環境全体で、OCIで提供されるデバイスのメトリック深度（パリティ）は同じですか。

サードパーティのプラットフォームとベンダーのテクノロジ全体で、標準化、共通性、および命名方法にはさまざまなレベルがあります。OCIでは、容量とパフォーマンスの情報を一貫したフレームワークに標準化しようとします。容量やパフォーマンスの一部の指標は、 IOPS 、レイテンシ、物理容量など、デバイスのカウンタからネイティブに提供されます。カウンタが指定されていない場合、OCIは値を要約しようとします（たとえば、基盤となるボリュームのIOPSや容量の合計など）。どちらも使用できない場合は、さまざまな計算アルゴリズムを使用して指標の値を取得しようとします。OCIでは、一般的なSNMP統合機能を使用して、現在OCIで収集されていない追加の指標を組み込むことができます。



== OCIではFibre Channelスイッチはサポートされていますか。

はい。OCIでは、ストレージ資産からデータを収集するだけでなく、環境内のCisco、Brocade、QLogicスイッチからインベントリとパフォーマンスのデータも取得します。



== インフラ全体のトポロジビューは使用できますか。OCIに「エンドツーエンドの可視性」が表示されるか。

はい。OCIでは、論理構造と物理構造を動的に検出してマッピングすることで、コンピューティング、ファブリック、仮想化、バックエンドストレージのトポロジビューをエンドツーエンドでインタラクティブに表示できます。トポロジアイコンを使用すると、影響を受けるリソースへのクイック起動ナビゲーションが可能になり、共有ストレージ環境でのワークロードや違反の特定に役立ちます。
