---
permalink: faq/faq-insight-licensing.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight のライセンスに関する一般的な質問と回答が表示されます。 
---
= OnCommand Insight ライセンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight のライセンスに関する一般的な質問と回答が表示されます。



== OCIライセンスの概要

OCIのライセンスは容量単位で提供される。お客様は、有効にするモジュールごとにライセンスを購入する必要があります。

* Discover *はAssure、Perform、Planの前提条件であり、単独では提供されません。Discoverのライセンスは、管理対象容量（TB）単位で付与されます。

*Assure *は、管理容量（FC、NAS、iSCSI、FCoEのすべてのストレージインフラストラクチャに対する単一の料金単位）でライセンスされます。

* Perform *には、管理対象容量（TB）単位でライセンスが付与されます。

*プラン*には、管理対象容量（TB）単位でライセンスが付与されます。

「管理容量」は、フォーマット前の物理ディスク、仮想ディスク、およびテープのraw容量として定義されます。これは、オンプレミスとクラウドの両方でInsightによって検出されたすべてのストレージに当てはまります。

ほとんどのデータソースでは、ディスクの物理容量（2進法）が使用されます。スペアディスク、未割り当てディスク、RAIDディスクなど、ディスクロールは考慮されません。

Insightのライセンスには、*恒久ライセンス*と*サブスクリプション*の2種類があります。

*恒久ライセンス*適用されるライセンス条件に従って取得したソフトウェアの特定のバージョン/リリースを無期限に使用することができます。ソフトウェアサポートプラン（SSP）を購入されたお客様の場合、ネットアップは、サポートサービス条件に従って更新が利用可能になった時点で、NetApp Support Site を通じて一般提供されているソフトウェアアップデートへのアクセスを提供します。ネットアップでは、ネットアップテクニカルサポートセンターで決定された特別なパッチも提供しています。

*サブスクリプション*は、以下の権利を付与するソフトウェアの固定ライセンスです。

* オンプレミスのソフトウェアは、適用されるライセンス条件に従い、限られた期間（通常は12カ月）のみ使用してください
* 期間中、ソフトウェアサポート（旧称SSP）を受ける
* ライセンス契約者は、事実上、市販されている最新のバージョン、リリース、またはアップデートを使用することができます。ただし、ソフトウェアのサポートを受けることはできません


各固定期間（通常は12カ月）の終了時に、追加の固定期間（通常は12カ月）にライセンスを更新できます。ライセンスが更新されない場合、ライセンシーはソフトウェアを使用する権利を失い、SSPの特典を受ける権利を失い、ライセンシーはソフトウェアのすべてのコピーを破棄する必要があります。



== OCIライセンスモジュールの詳細については、こちらをご覧ください

OCIには、今日のデータセンター環境のニーズを満たすために4つのコアライセンスモジュールが用意されている。これらのモジュールは、* Discover、Perform、Assure、Plan *です。Discoverは基本モジュールであり、その他のすべてのモジュール購入に必要です。

[Discover]*モジュールを使用すると、OCIでデータセンター内のアセットを特定し、デバイスサービスパスを動的にマッピングできます。容量、ベンダー情報、モデル、ファームウェア、シリアル番号などの情報が提供されます。

* perform *は、OCIのパフォーマンス収集モジュールです。Performは、IOPS、スループット、レイテンシ、CPUとメモリの情報のほか、その他の分析情報を収集します。

*Assure *は'ファイバ・チャネル環境と効率化テクノロジーに重点を置いていますファイバチャネルおよびiSCSI環境におけるリスクの特定と管理に役立ちます。Assureは、マスキング、マッピング、およびアラートに関する情報や、ファブリックの冗長性、スイッチホップ、ファンアウト比率、シンプロビジョニングなどの効率化に関するベストプラクティスポリシーも提供します。

*プラン*では、オンプレミスのハイブリッド環境と世界中に分散したデータセンター環境において、コンピューティング、ファブリック、各種ストレージ（clustered Data ONTAP、7-Mode、サードパーティ）のトレンドを特定して予測することができます。保持期間が長くなります。Data Warehouseは、レポートオーサリングを可能にする組み込みのインテリジェンスで構成されており、エンタープライズ共有ストレージ環境で指標が二重にカウントされることを回避します。「すぐに使用できる」製品化されたレポートを生成してスケジュール設定することも、統合されたレポートオーサリングツール「ドラッグアンドドロップ」を使用して独自のレポートを作成することもできます。
