---
permalink: faq/faq-general-insight-questions.html 
sidebar: sidebar 
keywords: redhat,Linux 
summary: このFAQでは、OnCommand Insight に関する一般的な質問に回答します。 
---
= 一般的な質問
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このFAQでは、OnCommand Insight に関する一般的な質問に回答します。



== OnCommand Insight （OCI）が導入されたのはいつですか。

OCIは、業界で最も成熟したインフラ監視製品の1つであり、10年以上にわたって活発な開発が行われている。以前はOnaroまたはSANscreen と呼ばれていたSANscreen の名称は、OnCommand 製品スイートに参加したときに変更され、現在はOnCommand Insight 、より一般的にはInsightまたはOCIと呼ばれています。



== OCIの環境への導入にはどれくらいの時間がかかりますか。

OCIは単にソフトウェアをダウンロードするだけです。ソフトウェアは、 2 台の専用の仮想サーバまたは物理サーバにインストールされます。一般的なインストールはわずか 2 時間で完了し、インベントリ、容量、パフォーマンスのデータの提供はほぼ即座に開始されます。パフォーマンスとベストプラクティスのポリシー、ユーザアノテーション、およびコスト情報の設定を追加する場合は、計画についてさらに検討する必要があります。



== OCIにはエージェント、コレクタ、プローブが必要ですか。

OCIは100%エージェントレスで、エージェント、タップ、プローブを使用する必要はありません。すべてのデバイス検出は読み取り専用で、アウトオブバンドおよび IP 経由で実行されます。



== OCIはどのようにしてデバイスを検出し、接続しますか？

OCIのセットアップでは、データセンター環境にすでに存在していることが多いネイティブのAPIとプロトコルを利用するため、エージェントやプローブは必要ありません。SSH 、 HTTP 、 SMIS 、および CLI は、ほんの一例です。デバイスエレメントマネージャ（EMCのUnisphereなど）がすでに存在する場合、OCIはエレメントマネージャと通信して既存の環境データを取得します。ほとんどのデバイス検出では、 IP アドレスと読み取り専用のユーザ名とパスワードのみが必要です。これらのデバイス検出は、OCIのVMwareデータソースのように「1対多」にすることができます。VMware vCenterを検出することで、OCIはそのすべてのESXiホストと関連するVMを1つのIPアドレスとクレデンシャルで検出します。



== OCIにはプロフェッショナルサービスが必要ですか。それは利用でき、それらは何を提供するか。

中規模の環境の場合は、導入、設定、統合のほか、さまざまなカスタムレポートやデータ検証の機能を提供するプロフェッショナルサービスを推奨します。OCIチームとアカウントエンゲージメントマネージャーと簡単に話し合うことで、パートナー様に最もメリットがあるサービスを見極めることができます。



== OCIは、どのくらいの頻度で新機能や改善点の更新をリリースしますか？

製品の更新とサービスパックは、OCIの複数のバージョンで利用できます。メジャーリリースまたはマイナーリリースは、通常、数か月ごとに提供され、新しいデバイスサポートやファームウェアのリリース頻度が高くなっています。どちらも support.netapp.com のダウンロードサイトから入手できます。新しいディスクモデルなど、メーカーから頻繁にリリースされる一部の更新は、OCIソフトウェアに自動的にプッシュされます。また、OCIデータソースデバイス収集は、開発の修正や更新の直後にオンサイトでパッチを適用できます。



== OCIの管理チームは、新しいデータソースの要求にどのように優先順位を付けますか。

OCIの製品管理チームは、すべてのお客様の機能強化と相互運用性機能に関する要望（IFR）を積極的に追跡している。各リクエストの詳細は、実現可能性について評価され、お客様のニーズと戦略的なビジネスへの全体的な影響に基づいて優先順位が付けられます。リクエストはいったん承認されると、対応レベルに基づいてサイズが決定され、将来の開発に向けてスケジュールされます。OCIの開発プロセスは即応性に優れているため、定期的にスケジュールされたリリースサイクルの外で新しいデータソースを利用できるようになります。ネットアップのアカウント担当者は、お客様からのお問い合わせや、新しいリクエストの送信にご協力いただけます。データソースにオンサイトでパッチを適用できるため、OCIをアップグレードする必要はありません。



== 私の会社は Linux で完全に動いています。OCIはLinuxでも動作しますか。

はい。OCIでは、複数のLinuxとWindowsをサポートしています。Cognos（OCIとData Warehouseで使用されるIBMのレポート作成ツール）はWindowsでのみサポートされるため、レポート作成にOCIを使用する場合はWindowsサーバでレポート作成ツールを実行する必要があります。『OCIインストールガイド』には、各OCIコンポーネントのサーバ要件とサポートされるオペレーティングシステムが記載されています。



== OCIは、インターネットアクセスのないセキュアな環境に適していますか。

はい。OCIは、Fortune 500企業上位10社に加え、世界中の大手銀行、医療機関、研究機関、政府機関で使用されています。OCIは、米軍共通アクセスカード（CAC）をサポートし、地理的に分散した環境やファイアウォールが厳しい環境向けのソリューションを提供している。



== OnCommand Unified Manager （ OCUM ）が clustered 解決策の管理 であることを私は聞き続けています。OCIを使用する理由を教えてください。

OnCommand Unified Managerはストレージアレイの「デバイス管理」レイヤで機能し、clustered Data ONTAP （cDOT）アレイとそのクラスタインターコネクトについて、インシデントベースやイベントベースで詳細に分析します。OCIでは、7-Mode、clustered Data ONTAP 、その他の他社製アレイで構成されるオンプレミス環境とグローバルに分散した環境を包括的に把握できます。仮想マシンからスピンドルに至るまでエンドツーエンドの可視性を提供することで、容量、パフォーマンス、コストモデリングのトレンドと予測の履歴を把握し、データセンター管理に対するプロアクティブなサービス品質アプローチを促進できます。



== Automation Storefrontに記載されているOnCommand Insight セカンダリETLとは何ですか。

一部のOnCommand Insight オートメーションStorefrontレポートのダウンロードで参照されている「セカンダリETL」要件は、OnCommand Insight データウェアハウスにデータを取り込むために、キャプチャされたデータの追加抽出、変換、読み込み(ETL)を呼び出すために使用される、開発されたプロフェッショナルサービスの実装を指します。

セカンダリ ETL プロセスの主な目的は、より複雑なレポートの生成を高速化したり、毎日実行するようにスケジュールしたりできるように、「バッチ」データをプリフェッチすることです。

このセカンダリETLは、OnCommand Insight データウェアハウス管理ガイドで詳しく説明されている推奨される「1日に1回」ETLに追加されています。

ネットアッププロフェッショナルサービスは、既存のOnCommand Insight レポートスケジュール、自動バックアップ、拡張性、その他のシステムパフォーマンスアクティビティへの影響を回避するために、セカンダリETLスクリプトを設定することを認定されています。ETL スクリプトの作成やデータ検証のニーズについては、ネットアップの営業担当者にお問い合わせのうえ、ネットアップのプロフェッショナルサービスがどのようにサポートされるかをご相談ください。追加情報
