---
permalink: faq/faq-scale-and-ease-of-use.html 
sidebar: sidebar 
keywords:  
summary: このFAQでは、OnCommand Insight の拡張性と使いやすさに関する一般的な質問に回答します。 
---
= 拡張性と使いやすさ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このFAQでは、OnCommand Insight の拡張性と使いやすさに関する一般的な質問に回答します。



== OCIの拡張性

OCIは、相互運用性と最小限の設置面積で取得できる資産の数の点で業界をリードしています。OCIの中核には、仮想サーバまたは物理サーバが2台必要です。1台はデータセンターのすべての資産を検出する運用サーバ用、もう1台は長期的な履歴レポートを作成するための統合データウェアハウス用です。OCIのエンタープライズ環境では、数百のアレイ、数万の仮想マシン、10万のファイバチャネルパス、10万以上のファイバチャネルポートがすべて単一のサーバインスタンスでサポートされています。



== OCIアプリケーションの管理には何人の担当者が必要ですか。

OCIでは、1人のユーザが管理できます。一方、OCIには、ビジネス環境内の複数の担当者が使用できる機能があり、それぞれに役割が異なり、レポート、トラブルシューティング、分析のニーズも異なります。設定の問題を表示するヘルスメニューや通知メニューから、ファブリックに接続されている物理ホストの自動検出まで、ツールのメンテナンスを最小限に抑えるためにあらゆる努力が払われています。柔軟なアノテーションにより、あらゆるタイプのユーザのエコシステムデータにビジネスコンテキストが反映されます。OCIでは、ストレージ管理者、ファブリック管理者、仮想化管理者からキャパシティプランニング担当者、ビジネスアナリスト、エグゼクティブまで、ビジネスサイロやテクノロジ全体で情報を共有できます。



== OCIはカスタムレポートをサポートしていますか。

はい。OCIでは、IBM Cognosビジネスインテリジェンスツールを使用してレポートを作成できます。このツールを使用すると、OCIのデータウェアハウスで収集されたデータを基に、完全にカスタマイズされた独自のレポートを作成できます。



== カスタムレポートは簡単に作成できますか？

OCIのレポート機能は、初心者と上級者の両方に対応しています。OCIには、「ドラッグアンドドロップ」のレポートオーサリング機能や、より高度なユーザサービスやプロフェッショナルサービス契約向けのSQLクエリベースのレポート作成機能など、さまざまなレポートオーサリング機能が用意されています。OCIに組み込まれたビジネスインテリジェンス解決策 （IBM Cognos）は、容量の二重カウントなどのよくある間違いを回避する。すぐに使えるレポート、ウィジェット、クエリ、ダッシュボードを追加することで、誰もが必要とするレポートを作成できます。

レポートテンプレートはOCIコミュニティストアからダウンロードすることもできます。



== OCIでは、シンプルな「信号機」でパフォーマンスと可用性を表示できますか。

はい。OCI Data WarehouseおよびReportingでは、値が赤/黄/緑の「条件付きスタイル」など、色が強化されたレポートを作成できます。レポートに色付きのフォントや背景を生成することは、エンドユーザとプロフェッショナルサービスの両方で実装できます。OCIウィジェットライブラリを使用すると、ビジネス固有のパフォーマンス指標をダッシュボードに表示できます。
