---
permalink: faq/faq-anomaly-detection.html 
sidebar: sidebar 
keywords:  
summary: このFAQでは、OnCommand Insight の異常検出に関する一般的な質問に回答します。 
---
= 異常検出
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このFAQでは、OnCommand Insight の異常検出に関する一般的な質問に回答します。



== 異常とは何ですか？

異常とは、以前に観測されたパターンや想定されるパターンと一致しない、IOPS、レイテンシ、利用率、バッファ間クレジット、CPU単位のパフォーマンス変化イベントです。OCIの異常検出機能は、アプリケーションサービスを提供しているアプリケーションインフラを対象に、処理のパターンや動作の変化を探します。このような循環的なプロセスパターンには、ワークロードのパフォーマンスが、業務時間と週末の時間帯に「増減とフロー」の履歴が含まれます。OCIの異常検出エンジンは、機械学習インテリジェンスを使用して「正常な」ベースラインパターンを確立し、定義されたアプリケーションが想定される動作から逸脱すると検出します。



== OCIでの異常検出の仕組み

OCIの異常検出は、履歴情報に基づく機械学習インテリジェンスを活用したプロアクティブな監視アプローチです。従来のしきい値よりもはるかに早く発生しているパフォーマンスの異常を検出できるため、管理者は、アプリケーションのSLOやデータセンターのサービスに影響が及ぶ前に、検討、計画、問題の軽減に時間をかけることができます。

Insightは、アプリケーションをサポートするインフラスタック全体を検出し、コンピューティングリソースからスイッチファブリック、さらにストレージリソースに至るまで、自動的にマッピングします。OCIは、IOPS、レイテンシ、ノード情報、ストレージプール利用率、ハイパーバイザーCPU、 各リソースのBB Credit Zeroからデータが異常検出エンジンに送られ、アプリケーションの異常分析に使用されます。異常の結果は1時間に2回更新され、アプリケーションダッシュボード、アプリケーションランディングページ、およびクエリテーブルウィジェットで確認できます。異常スコアはリソースごと、カウンタごとに実行され、アプリケーションインフラ全体の合計スコアが表示されます。



== 異常検出はどのバージョンのOCIでサポートされていますか？

異常検出はOCI 7.2以降でサポートされます。



== OCIで異常検出を有効にできるアプリケーションはいくつありますか？

OCIでは、ビジネスクリティカルなアプリケーションを最大48個まで監視できます。



== 導入できる異常検出エンジン（ADES）はいくつですか。

OCI運用サーバごとに1つの異常検出エンジン。



== アプリケーションが48個を超える場合、追加の異常検出エンジンを導入できますか。

はい。現在OCIでサポートされている異常検出エンジンは、OCIサーバごとに1つです。OCIサーバが複数ある環境では、追加の異常検出エンジンとOCI運用サーバを「ペアリング」して導入できます。各サーバでは、異常検出機能が有効になっているアプリケーションのみが可視化されます。



== アプリケーションクラスタ/グループのサイズには拡張性の制限はありますか。

OCIエンジニアリングにおけるInsightの異常検出機能を使用して最適な運用と拡張を実現するための一般的なガイドラインは次のとおりです。Insightサーバごとに1つの異常検出エンジンがサポートされます。OCIでは、最大48個のアプリケーションを監視できます。アプリケーションインフラは、最大4、000個のオブジェクトで構成できます。リソースが不足すると、全体的な規模が縮小します。



== 異常検出に必要なOCIライセンス

異常検出分析には、DiscoverライセンスとPerformライセンスの両方が必要です。



== 異常の検出を開始して結果を確認するには、どのくらいの時間がかかりますか。

異常スコアリングの結果は、アプリケーション監視を有効にしてからわずか2~3時間で表示されます。



== 結果を運用上使用するには、どのくらい待つ必要がありますか？

異常検出エンジンの結果の品質と精度は、時間（数週間、数カ月、四半期など）の経過とともに向上します。周期的な評価（周期性）は通常3週目頃に開始される。より長い期間（毎月など）にわたるパターンの場合、エンジンは異常スコアを調整する前に繰り返しイベントを観察する必要があります。



== 異常検出エンジンが学習を保持する期間はどれくらいですか。

異常検出エンジンは、学習情報を保存する方法で非常に効率的です。統計的学習は、オブジェクトの異常な動作について数カ月単位で測定できます。Insightで一般的に考えられる「保持」はありません。異常検出エンジンは、時間の経過とともに「統計的に重要」と判断されたデータを学習して保存し、必要に応じて重要でないデータを消去します。このメカニズムにより、学習時間が大幅に増加し、データの保存に必要なリソースと分析の実行に必要な時間の両方が削減されます



== 今日異常検出を有効にした場合、先週起こった異常を教えてもらえますか？

いいえ。異常検出が初期化されると、Insight Serverは既存のパフォーマンスデータをInsight Serverからロードして、監視対象のアプリケーションとそのインフラを理解する異常検出エンジンを起動します。取り込まれた「既存」のパフォーマンスデータでは異常は発生しません。異常は、既存のデータと比較して分析されるため、新しい受信データでのみ報告されます。新たに検出された異常は、わずか数時間で表示され始めます。



== 異常スコアはどのように計算されますか？

各アプリケーションの異常スコアは、さまざまなアセットのスコアを集計して計算されます。異常検出エンジンは、30以上の複雑なアルゴリズムと式を使用して、異常の判定とスコアを提供します。ユーザーは、このタイプの分析スコアリング手法を、多数の変数と測定値（体重、年齢、身長、密度など）からなるBMI（Body Mass Index）スコアなどの同様の医療スコアと比較することができます。



== 青いバーはそれぞれ何を表していますか？

3本のバーで構成される各ブロックは、リソースとその異常値の範囲を表します。青いバーが多いほど、観察された行動の変化が大きくなります。ブロックをクリックすると、（異常の）重要度、個 々 のリソース、カウンタが表示されます。



== 個 々 のリソースのスコアがアプリケーションの合計スコアに加算されないのはなぜですか。

各リソースは、観察された行動の偏差に基づいて個別に採点されます。個 々 のリソーススコアの有意性は、アプリケーションスコアの合計に関与しますが、その他の分析的および数学的要因も含まれる場合があります。



== アノテーションが割り当てられたビジネスエンティティやオブジェクトを監視するように異常検出を設定できますか。

現在、異常検出は定義されたアプリケーションでのみ有効にできます。アプリケーションに割り当て可能な任意のオブジェクト（VM、ハイパーバイザー、サーバ、ボリューム、内部ボリューム）をグループ化して監視できます。



== OCIは異常スコアが高い場合の通知を提供できますか。

はい、アプリケーションの異常スコアに基づいてアプリケーションのパフォーマンスポリシーを作成できます。ポリシーで定義されているしきい値を超えると、アプリケーションのリソースに関連する問題を通知するアラートがトリガーされます。



== アプリケーションの異常検出を無効にするとどうなりますか？

アプリケーションインフラに関して学習された（異常の履歴）情報はすべて、異常検出エンジンからクリアされます。異常検出の結果は、Insight運用データベースからすべてクリアされます。



== 静的なしきい値はどのような場合に使用しますか。

静的なしきい値は、インフラリソースの制限に関するベストプラクティスのアラートやイベントの期間の特定に適しています。また、サービスレベルの管理や、リンクのリセット、クラス3の破棄、同期の喪失など、さまざまなエラーカウンタメトリックに対するアラートの生成にも役立ちます。



== 異常検出に他の指標を追加する計画はありますか？

異常な機械学習モデルとアルゴリズムは、新しい統計データ、ユーザーフィードバック、製品改善が利用可能になるにつれて、引き続き改善または調整されます。



== 異常結果はData Warehouse（DWH）で確認できますか。

今日の異常結果はOCI Data Warehouseに送信されません（ETL-ed）。結果は、OCIアプリケーションのランディングページまたはユーザ定義のクエリテーブルウィジェットで確認できます。
