---
permalink: faq/faq-performance-troubleshooting.html 
sidebar: sidebar 
keywords:  
summary: このFAQでは、OnCommand Insight のパフォーマンスのトラブルシューティングに関する一般的な質問に回答します。 
---
= パフォーマンスのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このFAQでは、OnCommand Insight のパフォーマンスのトラブルシューティングに関する一般的な質問に回答します。



== 環境内のすべての Greedy リソースのリストを作成するにはどうすればよいですか。

OCIの相関分析は、指定されたサービスパスについて、システムリソースを大量に消費しているリソースやパフォーマンスが低下しているリソースを特定するのに役立つ。相関フィーチャーの生成された解析は ' 各オブジェクトを表示しながらリアルタイムで実行されます提供される分析によって、パフォーマンスの問題のトラブルシューティングやルート原因の特定に必要な時間が大幅に短縮されます。定義されたパフォーマンスポリシーで発生した違反の調査は、 Greedy リソースやパフォーマンスが低下したリソースを検出するためのエントリポイントの 1 つです。最新のクエリ機能を使用しているウィジェットとダッシュボードのどちらも、想定 IOPS （ Greedy ）、利用率、レイテンシを超えるリソースのフィルタリング、ソート、可視化に役立ちます。



== OCIでは、パフォーマンスの問題を1箇所で診断できますか。

はい。OCIでのパフォーマンストラブルシューティングには、さまざまな方法があります。OCIには、さまざまなアラート方法があります。SNMP 、 syslog 、 E メールで送信されるアラートがよく使用されます。Eメールで送信されたアラートを使用すると、影響を受けるリソースをすばやくクリックしてOCI内で起動できます。グローバル検索ウィンドウでは、リソース名を入力するだけで状況の分析を開始できます。

OCIのViolation Dashboardでは、イベント数、期間、時刻に基づいて作業の優先順位を設定できます。アラートの種類には、レイテンシ、IOPS、利用率、重大度、ビジネスユニット、関連するアプリケーションなどがあります。

OCIの相関分析は、影響を受けるリソースに関連付けられているオブジェクトを比較し、IOPS、レイテンシ、利用率、CPU、BBクレジットへの影響を判定するのに役立つ。

OCIのクエリテクノロジとウィジェットダッシュボードを使用すると、データセンター内の問題領域を対象に、詳細な情報を体系的に表示できます。



== OCIは7-Modeからclustered Data ONTAPへの移行に役立ちますか。

はい。OCIは、既存のワークロードのニーズや移行後の検証に非常に役立つ情報を提供します。今日のデータセンターの最新化におけるOCIの役割は、変更管理シミュレーション、移行前の最適化計画、適切なサービス階層の定義を可能にする。OCIでは、数回クリックするだけで、数千ものNFS共有やファイバチャネルパス全体のビジネスへの影響を簡単に収集し、関連付けることができます。OCIは、移行から機器更改まで、信頼性の高い適切なサイズの移行を実現し、計画外のサービス停止を軽減するための手段を提供します。



== OCIのパフォーマンス監視の「実際の時間」はどのようなものですか。

OCIは、オンプレミスとハイブリッドクラウドの両方のデータセンター管理で*ほぼリアルタイム*とみなされます。データソースのポーリングをより頻繁に実行するように設定できますが、ほとんどのユーザは、ほとんどのデバイスでパフォーマンス収集間隔を5分未満に設定しても、分析上の大きなメリットは得られません。収集頻度を増やすと、管理対象のオブジェクトや実行される分析に不要な負荷がかかる可能性があります。もちろん、より詳細な収集が必要になる場合もあります。OCIでは、お客様のデータセンター環境のニーズに合わせて、デバイスインベントリやパフォーマンスのポーリング間隔を設定できるなど、柔軟性に優れています。



== 「合計」が「読み取り」と「書き込み」で異なるのはなぜですか？

場合によっては、カウンタの_Total_がそのカウンタの_reads_plus_writes_の合計と等しくないことがあります。この問題が発生する可能性があるのは、いくつかの場合です。

* IOPS *：読み取りと書き込みに加えて、ストレージアレイやその他のアセットで、ワークロードのデータフローに関係のない内部処理が処理されます。これらの処理は、「システム」、「メタデータ」、または単に「その他」の処理と呼ばれることもあり、Snapshot、重複排除、スペース再割り当てなどの内部プロセスに起因する可能性があります。このような場合、特定のアセットに対するシステム処理の量を調べるには、_Total_IOPSから_Read_and_Write_IOPSの合計を差し引きます。読み取り IOPS と書き込み IOPS の合計は、データフローに直接関連する合計 IOPS です。

*レイテンシ*：合計応答時間は時間で加重された平均であるため、処理の合計応答時間（レイテンシ）が書き込み応答時間より_less than _と報告されることがあります。I/O ワークロードは多くの場合書き込み処理よりも多くの読み取り処理で構成され、書き込みでは一般にレイテンシが大きくなります。たとえば、平均レイテンシが 5 ミリ秒で 10 個の読み取り処理を実行したワークロードの場合、平均レイテンシが 10 ミリ秒の 5 つの書き込み処理を実行した場合、合計加重平均レイテンシは、読み取り回数と平均読み取りレイテンシの合計で計算されます。 書き込み数に平均書き込みレイテンシを掛けた値を、 I/O 処理の合計数で割った値。たとえば、（ 10 × 5 + 5 × 10 ） / （ 10 + 5 ） = 6.33 ミリ秒のようになります。



== オーバーコミットされたスペースでOCIとOCUMの値が異なるのはなぜですか？

OnCommand Unified Manager（OCUM）の「プロビジョニング」スペースの概念には、FlexVol（OnCommand Insight 内部ボリューム）が拡張される可能性がある自動拡張の制限が含まれている場合があります。OCIの「容量」には自動拡張時の制限は反映されません。そのため、自動拡張FlexVolがある環境では、OCUMでプロビジョニングされる合計容量がOCIストレージレベルの「オーバーコミット容量」の合計容量を超えます。FlexVolの容量と自動拡張時の容量の差がデルタになります。
