---
permalink: faq/faq-integrating-insight-and-third-party-tools.html 
sidebar: sidebar 
keywords:  
summary: このFAQでは、OnCommand Insight と他のツールの統合に関する一般的な質問に回答します。 
---
= Insightを他のツールと統合する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このFAQでは、OnCommand Insight と他のツールの統合に関する一般的な質問に回答します。



== OCIは他のツールと統合できますか。また、どのような統合ポイントを利用できますか。

はい。OCIは拡張可能な（オープンな）解決策 で、サードパーティのオーケストレーションシステム、ビジネス管理システム、変更管理システム、チケット発行システムとの統合や、カスタムのCMDB統合が可能です。OCIでは、完全に公開されたRESTful APIとオープンなMySQLデータベースのプライマリ統合ポイントにより、データを簡単かつ効果的に移動し、ユーザはデータにシームレスにアクセスできる。

InsightのSwaggerベースのAPIドキュメントは、製品の*（？）で確認できます。 [Help]>[REST API Documentation]*。



== Insight BMC Connectorとは何ですか。

OnCommand Insight Connector for BMCは、OnCommand Insight Data Warehouse（DWH）とBMC Atrium Configuration Management Database（CMDB）を統合します。Insight Connector for BMCは、ネットワークストレージシステム（ストレージユニット、ホストストレージサービス、VSストレージサービス、VMストレージサービスなど）、およびそれらのデバイス（ホスト、ストレージスイッチ、VMストレージサービスなど）との関係について、保存されている物理データと論理データをマッピングします。 およびテープ）を使用し、それらを構成アイテムおよび関係としてBMC CMDBにインポートします。OnCommand Insight Connector for BMCの詳細については、NetApp Support Site を参照してください。



== OCIはSCOMまたはVROPに対応していますか。

はい。OCIは多くのビジネス管理ソリューションを補完するものであり、データセンターのストレージ、コンピューティング、ハイパーバイザー、ファブリックに関する情報の信頼できるソースと考えられています。OCIをご利用のお客様は、OCIのRESTful APIと拡張可能なMySQLデータベースを活用して、BMC Remedy、ServiceNow、SCOM、Vrops、Splunkなどのさまざまなアプリケーションを いくつか例を挙げましょう。OCIでは、ほぼすべての記録ソースから情報をインポートしたり、収集した環境指標をサードパーティの一般的な監視、チケット処理、CMDB請求、オーケストレーションシステムに送信したりすることで、統合を拡張している。



== OCIでは、すでに使用しているクラウドサービスや使用を検討しているクラウドサービスを使用できますか。

はい。OCIでは、従来のオンプレミス環境と即応性に優れたハイブリッドクラウド環境の両方を管理することで、ビジネスサービスのニーズに最も適した対費用効果の高いプラットフォームを見極めることができます。OCIは移行前と移行後の分析に活用できるため、クラウドに適したワークロードを特定するのに役立つ。適切なクラウドサービスを選択するには、過去の容量のトレンド分析、パフォーマンス、コストのすべてが必要です。OCIのI/O密度などの指標を活用したサービス設計ワークショップは、環境を最適化しているかどうか、クラウドが有効かどうかなど、回答 に関する質問にも役立ちます。OCIの対象範囲は、NetApp Private Storage、Cloud ONTAP 、Amazon S3、OpenStack KVMをサポートすることで拡大を続けている。OCIは、特に容量計画、パフォーマンス、サービス品質、チャージバックの可視化が重要な領域で、ネットアップのクラウド管理キャンペーンで引き続き重要な役割を果たしている。



== OCIでインシデントをインシデント管理解決策 で開くことはできますか。

はい。OCIの違反イベントは、トラップまたはsyslogとしてSNMPでトリガーおよび送信できます。一部のイベントはRESTful APIでトリガーおよび送信できます。提供されたイベントに含まれる詳細は、多くのサードパーティのインシデント管理およびチケットソリューションで解釈できます。



== ビジネスユニットや部門にリソースを割り当てることはできますか？

はい。OCIにはアノテーションと呼ばれるメタデータのタグ付け方法が組み込まれています。ビジネスユニット、基幹業務、テナント、プロジェクトをデータセンターリソースに割り当てることで、資産、キャパシティプランニング、トラブルシューティング、レポート作成に関するビジネスコンテキストをより充実させることができます。



== OCIはWork Flow Automator（WFA）と連携できますか。

OCIの成功には、サードパーティのCMDB、課金、オーケストレーションテクノロジとの統合機能が重要な価値であり、WFAも例外ではありません。ネットアップのプロフェッショナルサービスは、現在WFAワークフローとOCIを使用して成功を収めている数多くの統合を実施してきました。



== OCIでパフォーマンスデータを保持する期間

OCIサーバには、90日間のほぼリアルタイムのパフォーマンスと、現在の（ポイントインタイムの）インベントリ（論理構成要素と物理構成要素）が格納されます。

OCIのパフォーマンスポーリング間隔はユーザが設定できます。ほとんどのベンダーでは、ストレージパフォーマンスは通常5分ごとに設定されています。パフォーマンス/インベントリデータは、長期的な履歴レポートと予測レポートを作成するために、毎日OCI Data Warehouse（DWH）に送信されます。DWHでは、このデータが集計データ（毎時、日次、月次ロールアップデータ）に変換されます。ストレージ/コンピューティング/ファブリックの構成/マッピングに関する環境履歴の監視など、「変化」を追跡する機能には、現時点では制限は定義されていません。

Data Warehouseでは、データマートおよびデータの単位に基づいて履歴データが保持されます。



== パフォーマンス計画レポートはありますか？

はい。OCIには複数のレポートが用意されています。また、ユースケースに基づいて、ネットアップのプロフェッショナルサービスカタログで提供されているレポートも多数用意されています。Data Warehouseモジュールには、ユーザが独自のレポートを作成できるCognosのレポートオーサリングツールも付属しています。
