---
permalink: config-admin/3par-inserv-firmware-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight は、3PAR InServ\（Firmware 2.2.2+、SSH\）データソースを使用して、HP 3PAR StoreServストレージアレイのインベントリを検出します。 
---
= 3PAR InServデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight は、3PAR InServ（Firmware 2.2.2+、SSH）データソースを使用して、HP 3PAR StoreServストレージアレイのインベントリを検出します。



== 用語集

OnCommand Insight では、3PAR InServデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
物理ディスク
 a| 
ディスク



 a| 
ストレージシステム
 a| 
ストレージ



 a| 
コントローラノード
 a| 
ストレージノード



 a| 
Common Provisioning Group の 1 つ
 a| 
ストレージプール



 a| 
仮想ボリューム
 a| 
ボリューム

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* InServ クラスタの IP アドレスまたは FQDN
* インベントリの場合、InServサーバに対する読み取り専用のユーザ名とパスワード。
* パフォーマンスを高めるために、InServサーバに対する読み取り/書き込みのユーザ名とパスワード。
* ポート要件：22（インベントリ収集）、5988、または5989（パフォーマンス収集）[注：3PARパフォーマンスはInServ OS 3.x以降でサポートされます]
* パフォーマンス収集については、 SSH を使用して 3PAR アレイにログインし、 SMI-S が有効になっていることを確認してください。




== 設定

|===


| フィールド | 説明 


 a| 
クラスタ IP
 a| 
InServクラスタのIPアドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
InServサーバのユーザ名



 a| 
パスワード
 a| 
InServサーバのパスワード



 a| 
SMI-SホストIP
 a| 
SMI-SプロバイダホストのIPアドレス



 a| 
SMI-S ユーザー名
 a| 
SMI-S プロバイダホストのユーザ名



 a| 
SMI-S のパスワード
 a| 
SMI-S プロバイダホストのパスワード

|===


== 詳細設定

|===


| フィールド | 説明 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリのポーリング間隔（デフォルトは 40 分）



 a| 
デバイスを除外します
 a| 
対象から除外するデバイスのIPをカンマで区切ったリスト



 a| 
SSHプロセス待機タイムアウト（秒）
 a| 
SSHプロセスのタイムアウト（デフォルトは60秒）



 a| 
SSHの再試行回数
 a| 
SSHの再試行回数



 a| 
SSHバナー待機タイムアウト（秒）
 a| 
SSHバナーのタイムアウト（デフォルトは20秒）



 a| 
SMI-Sポート
 a| 
SMI-Sプロバイダホストが使用するポート



 a| 
プロトコル
 a| 
SMI-S プロバイダへの接続に使用するプロトコル



 a| 
SMI-Sネームスペース
 a| 
SMI-Sネームスペース



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）



 a| 
SMI-S接続の再試行回数
 a| 
SMI-S接続の再試行回数

|===