---
permalink: config-admin/about-oncommand-insight-anomaly-detection.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight には、機械学習による異常検出分析が含まれています。アプリケーションのインフラを可視化し、サービスの停止を引き起こす前にパフォーマンスの異常を特定できます。 
---
= OnCommand Insight の異常検出の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight には、機械学習による異常検出分析機能が搭載されています。アプリケーションのインフラを可視化し、サービスの停止を引き起こす前にパフォーマンスの異常を特定できます。

異常分析は、アプリケーションの通常運用時のワークロードの範囲を特定し、パフォーマンスの変化が想定外のレベルになったときに通知するのに役立ちます。アプリケーションの異常検出エンジンは、Insightで収集されたパフォーマンス指標を取り込んで、アプリケーションインフラの異常を特定します。

異常検出を使用すると、次のタスクを実行できます。

* アプリケーションインフラの動作における大きな変化を特定する
* スタック全体および複数のカウンタでアプリケーションを追跡します
* アプリケーションワークロードで定期的に繰り返されるイベントの原因 を診断します
* 静的なしきい値を使用したパフォーマンスカウンタからのデータよりも包括的な情報を提供します
* トポロジのエンドツーエンドビューと最も異常な動作に焦点を当てる機能により、改善されたリアクティブモードで監視します。


異常検出エンジンでは、Insightのデータを使用してアプリケーションを分析します。監視を最初に開始した時点で、最大14日分の履歴パフォーマンスデータを分析エンジンに取り込むことができます。データは数週間から数カ月にわたって収集されるため、特定のリソースに関するより正確なデータが提供されます。データには次のカウンタの合計が含まれます。

|===


| オブジェクト | カウンタ 


 a| 
VM
 a| 
レイテンシ、IOPS



 a| 
ハイパーバイザー
 a| 
CPU利用率、IOPS



 a| 
エッジポート
 a| 
BBクレジットゼロ



 a| 
ストレージノード
 a| 
レイテンシ、利用率、IOPS



 a| 
ボリューム
 a| 
レイテンシ、IOPS



 a| 
内部ボリューム
 a| 
レイテンシ、IOPS



 a| 
ストレージプール
 a| 
IOPS、利用率

|===
Insight Serverでパフォーマンスデータのアーカイブが有効になっている場合は、異常検出エンジンで収集されたデータがアーカイブされます。アーカイブが有効かどうかを確認するには、[システムヘルス]ページを参照してください。

異常検出エンジンは、Insight Serverとは別のサーバで実行されます。物理マシンまたはVM上で設定できます。詳細については、『OnCommand Insight インストールガイド（WindowsまたはLinux）』を参照してください。
