---
permalink: config-admin/adding-data-sources.html 
sidebar: sidebar 
keywords:  
summary: '[データソースの追加]ダイアログボックスを使用して、データソースをすばやく追加できます。' 
---
= データソースを追加しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[データソースの追加]ダイアログボックスを使用して、データソースをすばやく追加できます。



== 手順

. ブラウザでOnCommand Insight を開き、管理者権限を持つユーザとしてログインします。
. [Admin]*を選択し、*[Data sources]*を選択します。
. [+追加]*ボタンをクリックします。
+
データソースの追加ウィザードが開きます。

. [設定]セクションで、次の情報を入力します。
+
|===


| フィールド | 説明 


 a| 
名前
 a| 
このデータソースの一意のネットワーク名を入力します。注：データソース名に使用できる文字は、アルファベット、数字、アンダースコア（_）のみです。



 a| 
ベンダー
 a| 
ドロップダウンからデータソースのベンダーを選択します。



 a| 
モデル
 a| 
ドロップダウンからデータソースのモデルを選択します。



 a| 
どこで実行するか
 a| 
[Local]を選択します。環境でRAUが設定されている場合はRemote Acquisition Unitを選択できます。



 a| 
収集するもの
 a| 
ほとんどのデータソースでは、これらのオプションは[Inventory]と[Performance]です。インベントリはデフォルトで常に選択されており、選択を解除することはできません。一部のデータソースには異なるオプションがある場合があります。選択した収集オプションによって、[Configuration]セクションと[Advanced configuration]セクションの使用可能なフィールドが変更されます。

|===
. [Configuration]*リンクをクリックし、選択したデータ収集タイプでデータソースに必要な基本的な設定情報を入力します。
. 通常、このタイプのデータソースをネットワークで設定するために詳細な情報が必要な場合は、*[Advanced configuration]*リンクをクリックして追加情報 に入ります。
. 特定のデータソースに必要な設定情報や高度な設定情報、または使用可能な設定情報の詳細については、を参照してください link:vendor-specific-data-source-reference.md#["ベンダー別のデータソースリファレンス"]。
. [Test]*リンクをクリックして、データソースが正しく設定されていることを確認します。
. [ 保存（ Save ） ] をクリックします。

