---
permalink: config-admin/adding-a-missing-disk-model.html 
sidebar: sidebar 
keywords:  
summary: ディスクモデルが不明なために取得に失敗した場合は、そのディスクモデルをnew_disk_models.txtファイルに追加して取得を再度実行できます。 
---
= 見つからないディスクモデルを追加しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ディスクモデルが不明なために取得に失敗した場合は、そのディスクモデルをに追加できます `new_disk_models.txt` ファイルを作成し、収集を再度実行します。



== このタスクについて

OnCommand Insight 取得によるストレージデバイスのポーリングの一環として、ストレージデバイス上のディスクモデルが読み取られます。Insightで認識されない新しいディスクモデルがベンダーによってアレイに追加された場合や、Insightで検索するモデル番号とストレージデバイスから返されるモデル番号が一致していない場合は、エラーが発生してそのデータソースの取得に失敗します。このエラーを回避するには、Insightで認識されるディスクモデルの情報を更新する必要があります。アップデート、パッチ、メンテナンスリリースによって新しいディスクモデルがInsightに追加されます。ただし、パッチや更新を待たずに、この情報を手動で更新することもできます。

OnCommand Insight はディスクモデルファイルを5分ごとに読み取るため、入力した新しいデータモデル情報は自動的に更新されます。変更を有効にするためにサーバを再起動する必要はありませんが、サーバとRemote Acquisition Unit（RAU）を再起動すると、次回の更新前に変更を有効にすることができます。

ディスクモデルの更新がに追加されます `new_disk_models.txt` ファイルはにあります``<SANScreenInstallDir>\wildfly\standalone\deployments\datasources.war`` ディレクトリ。を更新する前に、新しいディスクモデルの説明に必要な情報を確認しておきます `new_disk_models.txt` ファイル。ファイル内の情報が不正確な場合、誤ったシステムデータが生成され、取得に失敗する可能性があります。

Insightのディスクモデルを手動で更新するには、次の手順に従います。



== 手順

. ディスクモデルの適切な情報を確認します。
. テキストエディタを使用してを開きます `new_disk_models.txt` ファイル。
. 新しいデータソースの必要な情報を追加します。
. ファイルをに保存します `<SANScreenInstallDir>\wildfly\standalone\deployments\datasources.war` サーバ上のディレクトリ。
. をバックアップします `new_disk_models.txt` ファイルを安全な場所に保存します。以降のOnCommand Insight アップグレードでは、このファイルは上書きされます。アップグレードしたファイルにディスクモデル情報がない場合は、その情報を再入力する必要があります。

