---
permalink: config-admin/advanced-asset-search-techniques-new.html 
sidebar: sidebar 
keywords:  
summary: 監視対象環境内のデータやオブジェクトを検索する場合は、複数の検索手法を使用できます。 
---
= 高度な検索技術
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監視対象環境内のデータやオブジェクトを検索する場合は、複数の検索手法を使用できます。



== ワイルドカード検索

文字を使用して、複数文字のワイルドカード検索を実行できます。たとえば、_applic*n_と指定すると、applicationが返されます。



== 検索で使用されるフレーズ

フレーズは、二重引用符で囲まれた単語のグループです（例：「Paw VNX LUN 5」）。二重引用符を使用して、名前または属性にスペースを含むドキュメントを検索できます。



== ブール演算子

ブール演算子を使用すると、複数の用語を組み合わせて、より複雑なクエリを作成できます。

* *または*
+
** OR 演算子は、デフォルトの結合演算子です。
+
2 つのキーワードの間にブール演算子がない場合は、 OR 演算子が使用されます。

** OR 演算子は、 2 つのキーワードをリンクし、どちらかの条件がドキュメントに存在する場合に一致するドキュメントを検索します。
+
たとえば、「storage or netapp」と指定すると、「storage」または「netapp」のいずれかを含むドキュメントが検索されます。

** 一致するキーワードの数が多いドキュメントほどスコアが高くなります。


* *および*
+
AND 演算子を使用すると、両方の検索語が 1 つのドキュメント内に存在するドキュメントを検索できます。たとえば、「auroraとnetapp」と指定すると、「storage」と「netapp」の両方を含むドキュメントが検索されます。

+
単語との代わりに記号&&を使用できます。

* *ではありません*
+
NOT 演算子を使用すると、 NOT のあとのキーワードを含むすべてのドキュメントが検索結果から除外されます。たとえば、「strage not netapp」と指定すると、「strage」のみを含むドキュメントが検索され、「netapp」は検索されません。

+
記号を使用できます。「NOT」という単語の代わりに。





== プレフィックスとサフィックスの検索

* 検索文字列の入力を開始するとすぐに、検索エンジンによってプレフィックスとサフィックスの検索が実行され、最も一致するものが検索されます。
* 完全一致は、プレフィックスまたはサフィックスの一致よりもスコアが高くなります。スコアは、検索語と実際の検索結果との距離に基づいて計算されます。たとえば、「aurora」、「aurora1」、「aurora11」の3つのストレージがあるとします。「aur」を検索すると、3つのストレージすべてが返されます。ただし、接頭辞検索文字列との距離が最も近いため、「オーロラ」の検索結果のスコアが最も高くなります。
* また、検索エンジンは逆の順序で用語を検索します。これにより、接尾辞検索を実行できます。たとえば、検索ボックスに「345」と入力すると、検索エンジンは「345」を検索します。
* 検索では大文字と小文字は区別されません。




== インデックスキーワードを使用して検索します

インデックスキーワードの数が多い検索では、スコアが高くなります。

検索文字列は、スペースで複数の検索キーワードに分けて表示されます。たとえば、「strage aurora netapp」という検索文字列は、「strage」、「aurora」、「netapp」の3つのキーワードに分割されます。3 つのキーワードをすべて使用して検索が実行されます。これらのキーワードのほとんどに一致するドキュメントのスコアが最も高くなります。入力する情報が多いほど、検索結果の方が適しています。たとえば、ストレージの名前とモードでストレージを検索できます。

検索結果は、カテゴリごとに上位 3 件まで表示されます。想定していたドキュメントが見つからなかった場合は、検索文字列にキーワードを追加して検索結果を向上させることができます。

次の表に、検索文字列に追加できるインデックスキーワードのリストを示します。

|===


| カテゴリ | インデックスキーワード 


 a| 
ストレージ
 a| 
* "ストレージ"
* 名前
* ベンダー
* モデル




 a| 
ストレージプール
 a| 
* "`stragepool`"
* 名前
* ストレージの名前
* ストレージのIPアドレス
* ストレージのシリアル番号
* ストレージベンダー
* ストレージモデル
* 関連付けられているすべての内部ボリュームの名前
* 関連付けられているすべてのディスクの名前




 a| 
内部ボリューム
 a| 
* "`internalvolume'"
* 名前
* ストレージの名前
* ストレージのIPアドレス
* ストレージのシリアル番号
* ストレージベンダー
* ストレージモデル
* ストレージプールの名前
* 関連付けられているすべての共有の名前
* 関連付けられているすべてのアプリケーションとビジネスエンティティの名前




 a| 
ボリューム
 a| 
* "'ボリューム'"
* 名前
* ラベル
* すべての内部ボリュームの名前
* ストレージプールの名前
* ストレージの名前
* ストレージのIPアドレス
* ストレージのシリアル番号
* ストレージベンダー
* ストレージモデル




 a| 
ストレージノード
 a| 
* 「Stragenode」
* 名前
* ストレージの名前
* ストレージのIPアドレス
* ストレージのシリアル番号
* ストレージベンダー
* ストレージモデル




 a| 
ホスト
 a| 
* "ホスト""
* 名前
* IP アドレス
* 関連付けられているすべてのアプリケーションとビジネスエンティティの名前




 a| 
データストア
 a| 
* 「データストア」
* 名前
* Virtual Center IPの略
* すべてのボリュームの名前
* すべての内部ボリュームの名前




 a| 
仮想マシン
 a| 
* "`virtualmachine'"
* 名前
* DNS名
* IP アドレス
* ホストの名前
* ホストのIPアドレス
* すべてのデータストアの名前
* 関連付けられているすべてのアプリケーションとビジネスエンティティの名前




 a| 
スイッチ（標準と NPV ）
 a| 
* "スイッチ"
* IP アドレス
* WWN
* 名前
* シリアル番号
* モデル
* ドメインID
* ファブリックの名前
* ファブリックのWWN




 a| 
アプリケーション
 a| 
* "`application'"
* 名前
* テナント
* 基幹業務部門
* ビジネスユニット
* プロジェクト




 a| 
テープ
 a| 
* "`tape'"
* IP アドレス
* 名前
* シリアル番号
* ベンダー




 a| 
ポート
 a| 
* "ポート"
* WWN
* 名前




 a| 
ファブリック
 a| 
* 「ファブリック」
* WWN
* 名前


|===