---
permalink: config-admin/analyzing-slow-pc-performance.html 
sidebar: sidebar 
keywords:  
summary: ネットワークユーザからコンピュータの動作が遅いという苦情を受けた場合は、ホストのパフォーマンスを分析し、影響を受けるリソースを特定する必要があります。 
---
= PCパフォーマンスの低下を分析しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークユーザからコンピュータの動作が遅いという苦情を受けた場合は、ホストのパフォーマンスを分析し、影響を受けるリソースを特定する必要があります。



== 作業を開始する前に

この例では、呼び出し元がホスト名を指定しています。



== 手順

. ブラウザでInsightを開きます。
. [Search assets]*ボックスにホスト名を入力し、検索結果でホスト名をクリックします。
+
リソースの_assetページ_が開きます。

. ホストのアセットページで、ページ中央のパフォーマンスチャートを確認します。通常は事前に選択されているレイテンシとIOPSに加えて、必要に応じてさまざまなタイプのデータを表示できます。デバイスタイプに応じて、スループット、メモリ、CPU、IPスループットなど、他のタイプのデータのチェックボックスをオンにします。
. グラフ上のポイントの概要 を表示するには、そのポイントの上にマウスポインタを置きます。
. また、ページ上部で期間を3時間から7日まで、または使用可能なすべてのデータを選択して変更することもできます。
. [Top correlated resources]*のリストで、アクティビティパターンがベースリソースと同じリソースがほかにないかどうかを確認します。
+
リストの最初のリソースは常にベースリソースです。

+
.. 関連するリソースの横にあるリンクをクリックすると、IOPSとCPUのどちらのアクティビティパターンがベースリソースと別のリソースのどちらであるかを確認できます。
.. 関連するリソースのチェックボックスをクリックして、そのデータをパフォーマンスチャートに追加します。
.. 関連するリソースの名前をクリックすると、そのリソースのアセットページが表示されます。


. VMの場合も同様に、*[Top correlated resources]*でストレージプールを探し、ストレージプール名をクリックします。

