---
permalink: config-admin/assigning-annotations-using-a-query.html 
sidebar: sidebar 
keywords: bulk edit 
summary: アセットのグループにアノテーションを割り当てると、それらのアセットを識別しやすくなり、クエリやダッシュボードでそれらの関連するアセットを使用しやすくなります。 
---
= クエリを使用して複数のアセットにアノテーションを割り当てる
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アセットのグループにアノテーションを割り当てると、それらのアセットを識別しやすくなり、クエリやダッシュボードでそれらの関連するアセットを使用しやすくなります。



== 作業を開始する前に

アセットに割り当てるアノテーションは、事前に作成しておく必要があります。



== このタスクについて

クエリを使用すると、アノテーションを複数のアセットに簡単に割り当てることができます。たとえば、カスタムのアドレスアノテーションをデータセンターの特定の場所にあるすべてのアレイに割り当てる場合などです。



== 手順

. アノテーションを割り当てるアセットを特定するための新しいクエリを作成します。[クエリ]*>*+[新しいクエリ]*をクリックします。
. [検索...]*ドロップダウンで*[ストレージ]*を選択します。フィルタを設定して、表示されるストレージのリストをさらに絞り込むことができます。
. 表示されたストレージのリストで、ストレージ名の横にあるチェックボックスをクリックして1つ以上を選択します。リストの上部にあるメインのチェックボックスをクリックして、表示されているすべてのストレージを選択することもできます。
. 必要なストレージをすべて選択したら、*[操作]*>*[アノテーションの編集]*をクリックします。
+
[Add Annotation]ダイアログボックスが表示されます。

. ストレージに割り当てる*[アノテーション]*と*[値]*を選択し、*[保存]*をクリックします。
+
そのアノテーションの列が表示されている場合は、選択したすべてのストレージで列が表示されます。

. アノテーションを使用して、ウィジェットやクエリでストレージをフィルタリングできるようになりました。ウィジェットでは、次の操作を実行できます。
+
.. ダッシュボードを作成するか、既存のダッシュボードを開きます。[Variable]*を追加し、上記のストレージで設定したアノテーションを選択します。変数がダッシュボードに追加されます。
.. 追加した変数フィールドで、* any *をクリックして、フィルタするための適切な値を入力します。チェックマークをクリックして変数値を保存します。
.. ウィジェットを追加します。ウィジェットの[Query]で、[**Filter by][***+*]ボタンをクリックし、リストから適切な注釈を選択します。
.. [Any]*をクリックし、上記で追加したアノテーション変数を選択します。作成した変数は"$`"で始まり、ドロップダウンに表示されます。
.. 必要に応じて他のフィルタやフィールドを設定し、ウィジェットがカスタマイズされたら*[保存]*をクリックします。


+
ダッシュボードのウィジェットには、アノテーションを割り当てたストレージのデータのみが表示されます。


