---
permalink: config-admin/auditing-system-and-user-activities.html 
sidebar: sidebar 
keywords:  
summary: '予期しない変更を特定する場合は、OnCommand Insight システムとそのユーザアクティビティの監査証跡を表示できます。監査ログメッセージは、[Audit]ページに表示されるだけでなく、syslogに送信することもできます。' 
---
= システムおよびユーザアクティビティの監査
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
予期しない変更を特定する場合は、OnCommand Insight システムとそのユーザアクティビティの監査証跡を表示できます。監査ログメッセージは、[Audit]ページに表示されるだけでなく、syslogに送信することもできます。



== このタスクについて

Insightでは、ストレージネットワークやストレージネットワークの管理に影響するユーザアクティビティについて、次のような監査エントリが生成されます。

* ログインしています
* パスの許可または許可解除
* 許可されたパスの更新
* グローバルなポリシーまたはしきい値を設定します
* データソースの追加または削除
* データソースを開始または停止します
* データソースのプロパティを更新しています
* タスクの追加、編集、または削除
* アプリケーショングループを削除しています
* デバイスの ID を識別または変更する
* ユーザを作成します
* ユーザを削除します
* ユーザロールの変更
* ユーザの変更（Guest à Admin）
* ユーザからのログアウト（強制ログアウトまたは手動ログアウト）
* Acquisition Unitの削除
* ライセンスの更新
* バックアップを有効にします
* バックアップの無効化
* ASUPの有効化（同じページでプロキシの有効化が監査ログに報告される）
* ASUPの無効化（同じページでプロキシの無効化が監査ログに報告される）
* セキュリティキーの再作成、システムパスワードの変更
* アセットのアノテーションを削除/追加しています
* CACユーザーのログオン/ログオフ
* CACユーザセッションタイムアウト




== 手順

. ブラウザでInsightを開きます。
. [Admin]*をクリックし、*[Audit]*を選択します。
+
[監査]ページでは、監査エントリが表形式で表示されます。

. テーブルでは、次の詳細を確認できます。
+
** * 時間 *
+
変更が行われた日時

** * ユーザー *
+
監査エントリに関連付けられているユーザの名前

** * 役割 *
+
ユーザアカウントのロール（ゲスト、ユーザ、または管理者）

** * IP *
+
監査エントリに関連付けられているIPアドレス

** * アクション *
+
監査エントリのアクティビティのタイプ

** * 詳細 *
+
監査エントリの詳細

+
データソースやアプリケーションなどのリソースに影響するユーザアクティビティがある場合は、そのリソースのランディングページへのリンクが詳細に表示されます。

+
[NOTE]
====
データソースを削除すると、そのデータソースに関連するユーザアクティビティの詳細にデータソースのランディングページへのリンクが表示されなくなります。

====


. 監査エントリを表示するには、特定の期間（1時間、3時間、24時間、3日間、7日間）を選択します。 Insightでは、選択した期間について、最大1、000件の違反が表示されます。
+
1ページに収まらないデータがある場合は、表の下のページ番号をクリックして、ページごとにデータを参照できます。

. 列ヘッダーの矢印をクリックして、表内の列のソート順序を昇順（上矢印）または降順（下矢印）に変更します。デフォルトのソート順序に戻すには、他の列ヘッダーをクリックします。
+
デフォルトでは、エントリは降順で表示されます。

. [*filter*]ボックスを使用すると、必要なエントリだけを表に表示できます。
+
ユーザの監査エントリのみを表示します `izzyk`を入力します `izzyk` を* filter *ボックスに入力します。


