---
permalink: config-admin/brocade-sphereon-intrepid-switch-snmp-data-source.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight では、Brocade Sphereon/Intrepid Switch\（SNMP\）データソースを使用して、Brocade Sphereon/Intrepidスイッチのインベントリを検出します。 
---
= Brocade Sphereon/Intrepid Switchデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight では、Brocade Sphereon/Intrepid Switch（SNMP）データソースを使用して、Brocade Sphereon/Intrepidスイッチのインベントリを検出します。



== 要件

[NOTE]
====
このデータコレクタは、OnCommand Insight 7.3.11以降では使用できません。

====
* ファブリック内のすべてのスイッチへの IP 接続が必要です。[Discover all switches in the fabric]チェックボックスを選択すると、ファブリック内のすべてのスイッチが識別されますが、検出するにはこれらの追加スイッチへのIP接続が必要です。
* SNMP V1 または SNMP V2 を使用している場合は、読み取り専用コミュニティストリングが必要です。
* ゾーニング情報を取得するには、スイッチへの HTTP アクセスが必要です。
* を実行してアクセスを検証します `snmpwalk` スイッチへのユーティリティ（を参照） `<install_path\>\bin\)`。




== 設定

|===


| * フィールド * | * 概要 * 


 a| 
球スイッチ
 a| 
スイッチの IP アドレスまたは完全修飾ドメイン名



 a| 
SNMP バージョン
 a| 
SNMP バージョン



 a| 
SNMPコミュニティ
 a| 
スイッチへのアクセスに使用する SNMP の読み取り専用コミュニティストリング



 a| 
ユーザ名
 a| 
スイッチの SMI-S のユーザ名（ SNMP v3 のみ）



 a| 
パスワード
 a| 
スイッチの SMI-S のパスワード（ SNMP v3 のみ）

|===


== 高度な設定

|===


| * フィールド * | * 概要 * 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは15分）



 a| 
SNMP 認証プロトコル
 a| 
SNMP 認証プロトコル（ SNMPv3 のみ）



 a| 
SNMP プライバシープロトコル
 a| 
SNMP プライバシープロトコル（ SNMPv3 のみ）



 a| 
SNMP プライバシーパスワード
 a| 
SNMPプライバシーパスワード



 a| 
SNMP 再試行回数
 a| 
SNMP の再試行回数



 a| 
SNMP タイムアウト（ミリ秒）
 a| 
SNMP タイムアウト（デフォルトは 5 、 000 ミリ秒）



 a| 
ファブリック名
 a| 
データソースでレポートするファブリック名。ファブリック名を WWN としてレポートする場合は、空白のままにします。



 a| 
トラッピングを有効にします
 a| 
デバイスからの SNMP トラップの受信時にデータ収集を有効にする場合に選択します。トラップを有効にするを選択した場合は、 SNMP も有効にする必要があります。



 a| 
Ttrapsの最小間隔（秒）
 a| 
トラップでデータ収集を試行する最小間隔（デフォルトは 10 秒）



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）

|===