---
permalink: config-admin/brocade-efcm-9-5-to-9-7-data-sources.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight は、Brocade Enterprise Fabric Connectivity Manager\（EFCM\）データソースを使用して、Brocade EFCMスイッチのインベントリを検出します。Insightでは、EFCMバージョン9.5、9.6、9.7がサポートされます。 
---
= Brocade Enterprise Fabric Connectivity Managerデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight は、Brocade Enterprise Fabric Connectivity Manager（EFCM）データソースを使用して、Brocade EFCMスイッチのインベントリを検出します。Insightでは、EFCMバージョン9.5、9.6、9.7がサポートされます。



== 要件

[NOTE]
====
このデータコレクタは、OnCommand Insight 7.3.11以降では使用できません。

====
* EFCM サーバのネットワークアドレスまたは完全修飾ドメイン名
* EFCM のバージョンは 9.5 、 9.6 、または 9.7 である必要があります
* EFCM サーバの IP アドレス
* EFCM サーバに対する読み取り専用のユーザ名とパスワード
* 読み取り専用のユーザ名とパスワードを使用して、InsightサーバからConnectrixスイッチにポート51512経由でTelnetでアクセスできることを確認しました




== 設定

|===


| * フィールド * | * 概要 * 


 a| 
EFC サーバ
 a| 
EFC サーバの IP アドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
スイッチのユーザ名



 a| 
パスワード
 a| 
スイッチのパスワード

|===


== 高度な設定

|===


| * フィールド * | * 概要 * 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは15分）



 a| 
ファブリック名
 a| 
EFCMデータソースによってレポートされるファブリック名。ファブリック名を WWN としてレポートする場合は、空白のままにします。



 a| 
通信ポート
 a| 
スイッチとの通信に使用するポート



 a| 
トラッピングを有効にします
 a| 
デバイスからの SNMP トラップの受信時にデータ収集を有効にする場合に選択します。トラップを有効にするを選択した場合は、 SNMP も有効にする必要があります。



 a| 
トラップ間の最小時間（秒）
 a| 
トラップによって収集を試行する最小間隔（デフォルトは15秒）



 a| 
非アクティブなゾーンセット
 a| 
アクティブなゾーンセットに加えてデータ収集の対象に含める非アクティブなゾーンセットをカンマで区切ったリスト



 a| 
使用する NIC
 a| 
SAN デバイスをレポートする際に RAU で使用するネットワークインターフェイスを指定します



 a| 
デバイスを除外します
 a| 
ポーリングの対象に含めるか除外するユニットの名前をカンマで区切ったリスト



 a| 
EFCMスイッチのニックネームをInsightスイッチ名として使用します
 a| 
EFCMスイッチのニックネームをInsightスイッチ名として使用する場合に選択します



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）

|===