---
permalink: config-admin/brocade-fc-switch-firmware-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight では、Brocade FC Switch\（SSH\）データソースを使用して、Factored Operating System\（FOS\）ファームウェア4.2以降を実行しているBrocadeまたはブランド名が変更されたスイッチデバイスのインベントリを検出します。FC スイッチとアクセスゲートウェイの両方のモードのデバイスがサポートされます。 
---
= Brocade FC Switchデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight では、Brocade FC Switch（SSH）データソースを使用して、Factored Operating System（FOS）ファームウェア4.2以降を実行しているBrocadeスイッチデバイス（ブランド名が変更されたスイッチデバイス）のインベントリを検出します。FC スイッチとアクセスゲートウェイの両方のモードのデバイスがサポートされます。



== 用語集

OnCommand Insight では、Brocade FC Switchデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
スイッチ
 a| 
スイッチ



 a| 
ポート
 a| 
ポート



 a| 
仮想ファブリック、物理ファブリック
 a| 
ファブリック



 a| 
ゾーン
 a| 
ゾーン



 a| 
Logical Switch の略
 a| 
Logical Switch の略



 a| 
LSAN ゾーン
 a| 
IVR ゾーン

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* Acquisition Unit（ローカルまたはリモート）は、BrocadeスイッチのTCPポート22への接続を開始してインベントリデータを収集します。AU は、パフォーマンスデータの収集用に UDP ポート 161 への接続も開始します。
* ファブリック内のすべてのスイッチへの IP 接続が必要です。[Discover all switches in the fabric]チェックボックスを選択すると、ファブリック内のすべてのスイッチが識別されますが、検出するにはこれらの追加スイッチへのIP接続が必要です。
* ファブリック内のすべてのスイッチで、同じアカウントがグローバルに必要です。アクセスの確認には、 PuTTY （オープンソースの端末エミュレータ）を使用できます。
* Performライセンスがインストールされている場合は、SNMPパフォーマンスポーリング用に、ポート161および162をファブリック内のすべてのスイッチに対して開いておく必要があります。
* SNMP 読み取り専用コミュニティストリング




== 設定

|===


| フィールド | 説明 


 a| 
スイッチ IP
 a| 
スイッチの IP アドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
スイッチのユーザ名



 a| 
パスワード
 a| 
スイッチのパスワード



 a| 
SNMP バージョン
 a| 
SNMP バージョン



 a| 
SNMP コミュニティストリング
 a| 
スイッチへのアクセスに使用する SNMP の読み取り専用コミュニティストリング



 a| 
SNMP ユーザ名
 a| 
SNMPバージョンプロトコルのユーザ名（SNMP v3のみ）



 a| 
SNMP パスワード
 a| 
SNMPバージョンプロトコルのパスワード（SNMP v3のみ）

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
ファブリック名
 a| 
データソースでレポートするファブリック名。ファブリック名を WWN としてレポートする場合は、空白のままにします。



 a| 
デバイスを除外します
 a| 
ポーリングの対象から除外するデバイスの ID をカンマで区切ったリスト



 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは15分）



 a| 
タイムアウト（秒）
 a| 
接続タイムアウト（デフォルトは30秒）



 a| 
バナー待機タイムアウト（秒）
 a| 
SSHバナーのタイムアウト（デフォルトは5秒）



 a| 
管理ドメインはアクティブです
 a| 
管理ドメインを使用する場合に選択します



 a| 
MPR データを取得する
 a| 
マルチプロトコルルータ（MPR）からルーティングデータを取得する場合に選択します。



 a| 
トラッピングを有効にします
 a| 
デバイスからの SNMP トラップの受信時にデータ収集を有効にする場合に選択します。トラップを有効にするを選択した場合は、 SNMP も有効にする必要があります。



 a| 
トラップ間の最小時間（秒）
 a| 
トラップでデータ収集を試行する最小間隔（デフォルトは 10 秒）



 a| 
ファブリック内のすべてのスイッチを検出します
 a| 
ファブリック内のすべてのスイッチを検出する場合に選択します



 a| 
HBA との優先を選択しますゾーンのエイリアス
 a| 
HBA とゾーンエイリアスのどちらを優先するかを選択します



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）



 a| 
SNMP 認証プロトコル
 a| 
SNMP 認証プロトコル（ SNMP v3 のみ）



 a| 
SNMP プライバシープロトコル
 a| 
SNMPプライバシープロトコル（SNMP v3のみ）



 a| 
SNMP プライバシーパスワード
 a| 
SNMP プライバシーパスワード（ SNMP v3 のみ）



 a| 
SNMP 再試行回数
 a| 
SNMP の再試行回数



 a| 
SNMP タイムアウト（ミリ秒）
 a| 
SNMP タイムアウト（デフォルトは 5 、 000 ミリ秒）

|===