---
permalink: config-admin/cdot-landing-page-terminology-storage.html 
sidebar: sidebar 
keywords:  
summary: ネットアップのclustered Data ONTAP ストレージアセットランディングページに記載されているオブジェクトや参照に適用される用語。 
---
= clustered Data ONTAP ストレージ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットアップのclustered Data ONTAP ストレージアセットランディングページに記載されているオブジェクトや参照に適用される用語。



== clustered Data ONTAP ストレージの用語

以下の用語は、NetApp clustered Data ONTAP のストレージアセットランディングページに表示されるオブジェクトや参照先に適用されます。これらの用語の多くは、他のデータコレクタにも適用されます。

* Model --このクラスタ内で一意の個別のノードモデル名をカンマで区切ったリスト。クラスタ内のすべてのノードのモデルタイプが同じ場合、表示されるモデル名は 1 つだけです。
* vendor --新しいデータソースを設定する場合と同じベンダー名。
* シリアル番号--アレイのシリアル番号NetApp clustered Data ONTAP などのクラスタアーキテクチャストレージシステムでは、このシリアル番号が個 々 の「ストレージノード」のシリアル番号よりも有用でない場合があります。
* IP：通常は、データソースで設定されているIPまたはホスト名です。
* マイクロコードバージョン--ファームウェア。
* Raw Capacity：役割に関係なく、システム内のすべての物理ディスクの2進数の合計。
* レイテンシ：ホストに直面しているワークロードで発生している状況を読み取りと書き込みの両方で表したもの。OCIがこの価値を直接提供するのが理想的ですが、そうではないことがよくあります。OCIでは、この機能を提供するアレイの代わりに、個 々 の内部ボリュームの統計に基づいてIOPSの加重計算を実行します。
* スループット：内部ボリュームから集計された値。
* 管理--これには'デバイスの管理インタフェースのハイパーリンクが含まれている場合がありますインベントリレポートの一部としてInsightデータソースによってプログラムによって作成されます。

