---
permalink: config-admin/cdot-landing-page-terminology-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: NetApp clustered Data ONTAP ストレージプールのアセットランディングページに記載されているオブジェクトや参照に適用される用語。 
---
= clustered Data ONTAP ストレージプール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp clustered Data ONTAP ストレージプールのアセットランディングページに記載されているオブジェクトや参照に適用される用語。



== clustered Data ONTAP ストレージプールの用語

以下に示す用語は、NetApp clustered Data ONTAPストレージプールのアセットランディングページにあるオブジェクトや参照先に適用されます。これらの用語の多くは、他のデータコレクタにも適用されます。

* ストレージ--このプールが配置されているストレージアレイ必須。
* タイプ(Type)--可能性の列挙されたリストから'説明的な値を指定します最も一般的な構成は「アグリゲート」または「RAIDグループ」です。
* ノード：このストレージアレイのアーキテクチャでプールが特定のストレージノードに属する場合は、ストレージアレイの名前が独自のランディングページへのハイパーリンクとして表示されます。
* [Uses Flash Pool]-[Yes/No Value]-このSATA / SASベースのプールには、キャッシュアクセラレーションにSSDが使用されていますか。
* redundancy -- RAIDレベルまたは保護スキーム。raid_dp はデュアルパリティ、 raid_dp はトリプルパリティです。
* 容量--使用済み論理容量、使用可能容量、論理合計容量、およびこれらの使用率が表示されます。
* オーバーコミット容量：効率化テクノロジを使用して、ストレージプールの論理容量よりも大きいボリュームまたは内部ボリュームの合計容量を割り当てた場合、この割合の値は0%より大きくなります。
* スナップショット--使用中のスナップショット容量と合計容量(ストレージプールアーキテクチャがその容量の一部をスナップショット専用のセグメント領域に使用している場合)MetroCluster 構成のONTAP ではこの傾向が見られますが、他のONTAP 構成ではそうではありません。
* 利用率--このストレージプールに容量を提供しているディスクのうち、最も高いディスクビジー率を示すパーセンテージ。ディスク利用率は、必ずしもアレイのパフォーマンスと強い相関関係があるとは限りません。ホスト主導のワークロードがない場合、ディスクのリビルドや重複排除処理などが原因で利用率が高くなる可能性があります。また、多くのアレイのレプリケーション実装では、内部ボリュームまたはボリュームのワークロードとして表示されずに、ディスク利用率が上昇する可能性があります。
* IOPS --このストレージプールに容量を提供しているすべてのディスクの合計IOPS。
* スループット--このストレージプールに容量を提供しているすべてのディスクの合計スループット

