---
permalink: config-admin/cdot-landing-page-terminology-storage-node.html 
sidebar: sidebar 
keywords:  
summary: NetApp clustered Data ONTAPのストレージノードのアセットランディングページに記載されている、オブジェクトや参照に適用される用語。 
---
= clustered Data ONTAP ストレージノード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp clustered Data ONTAPのストレージノードのアセットランディングページに記載されている、オブジェクトや参照に適用される用語。



== clustered Data ONTAP ストレージノードの用語

以下の用語は、NetApp clustered Data ONTAP ストレージプールのアセットランディングページに表示されるオブジェクトや参照先に適用されます。これらの用語の多くは、他のデータコレクタにも適用されます。

* ストレージ--このノードが属するストレージアレイ必須。
* HAパートナー-- 1つのノードが1つだけ他のノードにフェイルオーバーするプラットフォームでは、一般的にここに表示されます。
* State --ノードのヘルス。アレイが正常な状態でデータソースでインベントリを作成できる場合にのみ使用できます。
* model --ノードのモデル名。
* version --デバイスのバージョン名
* シリアル番号--ノードのシリアル番号
* memory --ベース2メモリ(使用可能な場合)。
* 利用率-- ONTAP では、これは独自のアルゴリズムによるコントローラの応力指数です。パフォーマンスポーリングが行われるたびに、 WAFL ディスクの競合率または平均 CPU 利用率の値が 0 ～ 100% の範囲で報告されます。50%を超える値が続く場合は、サイズ不足を示しています。コントローラ/ノードのサイズが十分でないか、書き込みワークロードを吸収するのに十分な回転式ディスクがない可能性があります。
* IOPS：ノードオブジェクトに対するONTAP ZAPI呼び出しから直接導出されます。
* レイテンシ：ノードオブジェクトに対するONTAP ZAPI呼び出しから直接導出されます。
* スループット：ノードオブジェクトに対するONTAP ZAPI呼び出しから直接導出されます。
* processors -- CPU数。

