---
permalink: config-admin/changing-oncommand-insight-internal-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: セキュリティポリシーによっては、OnCommand Insight 環境でパスワードの変更が必要になる場合があります。1台のサーバのパスワードの一部は、環境内の別のサーバに存在するため、両方のサーバでパスワードを変更する必要があります。たとえば、Insight Serverで「inventory」ユーザのパスワードを変更した場合は、そのInsight Server用に設定されているData Warehouseサーバコネクタの「inventory」ユーザのパスワードと一致している必要があります。 
---
= OnCommand Insight の内部ユーザのパスワードを変更しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティポリシーによっては、OnCommand Insight 環境でパスワードの変更が必要になる場合があります。1台のサーバのパスワードの一部は、環境内の別のサーバに存在するため、両方のサーバでパスワードを変更する必要があります。たとえば、Insight Serverでユーザのパスワード「inventory」を変更する場合は、そのInsight Server用に設定されたData Warehouse Server Connectorでユーザのパスワード「inventory」と一致している必要があります。



== 作業を開始する前に

[NOTE]
====
パスワードを変更する前に、ユーザアカウントの依存関係を理解しておく必要があります。必要なすべてのサーバでパスワードを更新しないと、Insightコンポーネント間の通信に失敗します。

====


== このタスクについて

次の表に、Insight Serverの内部ユーザパスワードと、依存するパスワードが新しいパスワードと一致する必要があるInsightコンポーネントを示します。

|===


| Insight Serverのパスワード | 必要な変更 


 a| 
_internal
 a| 



 a| 
取得
 a| 
愛称はラオ



 a| 
dwh_internalの略
 a| 
Data Warehouse



 a| 
ホスト
 a| 



 a| 
在庫
 a| 
Data Warehouse



 a| 
ルート
 a| 

|===
次の表に、Data Warehouseの内部ユーザパスワードと、依存するパスワードが新しいパスワードと一致する必要があるInsightコンポーネントを示します。

|===


| Data Warehouseのパスワード | 必要な変更 


 a| 
cognos_adminをクリックします
 a| 



 a| 
DWH
 a| 



 a| 
dwh_internal（Server Connectorの設定UIを使用して変更）
 a| 
Insightサーバ



 a| 
誰だ
 a| 



 a| 
ホスト
 a| 



 a| 
インベントリ（Server Connector設定UIを使用して変更）
 a| 
Insightサーバ



 a| 
ルート
 a| 

|===
* DWHサーバ接続設定UIでのパスワードの変更*

次の表に、LAUのユーザパスワードと、依存するパスワードが新しいパスワードと一致する必要があるInsightコンポーネントを示します。

|===


| LAUパスワード | 必要な変更 


 a| 
取得
 a| 
Insight Server、RAU

|===