---
permalink: config-admin/cisco-fc-switch-firmware-snmp-data-source.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight では、Cisco FC Switch Firmware 2.0+\（SNMP\）データソースを使用して、Cisco MDSファイバチャネルスイッチおよびFCサービスが有効になっているさまざまなCisco Nexus FCoEスイッチのインベントリを検出します。さらに、このデータソースを使用して、NPVモードで実行されているシスコデバイスの多くのモデルを検出できます。 
---
= Cisco FC Switch Firmware（SNMP）データソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight では、Cisco FC Switch Firmware 2.0+（SNMP）データソースを使用して、Cisco MDSファイバチャネルスイッチおよびFCサービスが有効になっているさまざまなCisco Nexus FCoEスイッチのインベントリを検出します。さらに、このデータソースを使用して、NPVモードで実行されているシスコデバイスの多くのモデルを検出できます。



== 用語集

OnCommand Insight では、Cisco FC Switchデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
スイッチ
 a| 
スイッチ



 a| 
ポート
 a| 
ポート



 a| 
VSAN （仮想 SAN
 a| 
ファブリック



 a| 
ゾーン
 a| 
ゾーン



 a| 
Logical Switch の略
 a| 
Logical Switch の略



 a| 
ネームサーバエントリ
 a| 
ネームサーバエントリ



 a| 
Inter-VSAN Routing （ IVR ）ゾーン
 a| 
IVR ゾーン

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* ファブリック内の 1 つのスイッチまたは個々のスイッチの IP アドレス
* シャーシ検出。ファブリック検出をイネーブルにします
* SNMP V2 を使用している場合は、読み取り専用コミュニティストリングが必要です
* ポート 161 はデバイスへのアクセスに使用されます
* を使用したアクセスの検証 `snmpwalk` スイッチへのユーティリティ（を参照） `<install_path\>\bin\`)




== 設定

|===


| フィールド | 説明 


 a| 
Cisco スイッチ IP
 a| 
スイッチの IP アドレスまたは完全修飾ドメイン名



 a| 
SNMP バージョン
 a| 
パフォーマンスの取得にはSNMPバージョンv2以降が必要です



 a| 
SNMP コミュニティストリング
 a| 
スイッチへのアクセスに使用する SNMP の読み取り専用コミュニティストリング（ SNMP v3 は対象外）



 a| 
ユーザ名
 a| 
スイッチのユーザ名（ SNMP v3 のみ）



 a| 
パスワード
 a| 
スイッチのパスワード（ SNMPv3 のみ）

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリのポーリング間隔（デフォルトは 40 分）



 a| 
SNMP 認証プロトコル
 a| 
SNMP 認証プロトコル（ SNMPv3 のみ）



 a| 
SNMP プライバシープロトコル
 a| 
SNMP プライバシープロトコル（ SNMPv3 のみ）



 a| 
SNMP プライバシーパスワード
 a| 
SNMPプライバシーパスワード



 a| 
SNMP 再試行回数
 a| 
SNMP の再試行回数



 a| 
SNMP タイムアウト（ミリ秒）
 a| 
SNMP タイムアウト（デフォルトは 5 、 000 ミリ秒）



 a| 
トラッピングを有効にします
 a| 
トラップを有効にする場合に選択します。トラッピングを有効にする場合は、 SNMP 通知も有効にする必要があります。



 a| 
トラップ間の最小時間（秒）
 a| 
トラップでデータ収集を試行する最小間隔（デフォルトは 10 秒）



 a| 
すべてのファブリックスイッチを検出します
 a| 
ファブリック内のすべてのスイッチを検出する場合に選択します



 a| 
デバイスを除外します
 a| 
ポーリングの対象から除外するデバイスの IP をカンマで区切ったリスト



 a| 
デバイスを含める
 a| 
ポーリングの対象に含めるデバイスの IP をカンマで区切ったリスト



 a| 
デバイスタイプを確認します
 a| 
Cisco デバイスとして明示的にアドバタイズされたデバイスのみを受け入れる場合に選択します



 a| 
プライマリエイリアスタイプ
 a| 
エイリアスの解決で最初に優先する情報を指定します。次のいずれかを選択します。

* *デバイスエイリアス*
+
これは、ポートWWN（pWWN）のフレンドリ名であり、必要に応じてすべてのコンフィギュレーションコマンドで使用できます。Cisco MDS 9000 ファミリのすべてのスイッチは、 Distributed Device Alias Services （デバイスエイリアス）をサポートしています。

* * なし *
+
エイリアスは報告しないでください

* *ポート概要 *
+
ポートのリストでポートを識別するための概要

* *ゾーンエイリアス（すべて）*
+
ゾーニング設定でのみ使用できるポートのフレンドリ名

* *ゾーンエイリアス（アクティブのみ）*
+
アクティブな構成でのみ使用できるポートのフレンドリ名。これがデフォルトです。





 a| 
セカンダリエイリアスタイプ
 a| 
エイリアスの解決で 2 番目に優先する情報を指定します



 a| 
ターシャリエイリアスタイプ
 a| 
エイリアスの解決で 3 番目に優先する情報を指定します



 a| 
SANTap プロキシモードサポートをイネーブルにします
 a| 
Cisco スイッチで SANTap のプロキシモードを使用している場合に選択。EMC RecoverPoint を使用している場合は、 SANTap を使用していると考えられます。



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）

|===