---
permalink: config-admin/configuring-client-settings.html 
sidebar: sidebar 
keywords:  
summary: サーバでOnCommand Insight Java UIクライアントのオプションを設定できます。 
---
= クライアント設定の構成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サーバでOnCommand Insight Java UIクライアントのオプションを設定できます。



== 手順

. Insightのツールバーで、*[Admin]*をクリックし、*[Troubleshooting]*を選択します。
. ページ下部の[その他のタスク]領域で、*[高度なトラブルシューティング]*リンクをクリックします。
. 次のページの[詳細設定]メニューで、*[詳細設定]タブをクリックします。
. [Acquisition Dynamic Attributes]*に、動的な属性変更を無視する時間数を入力します。
. [クライアント設定の構成]*で、次の情報を入力します。
+
** *初期ヒープサイズ*は、クライアントを実行するためにVM（仮想マシン）が起動されたときに作成されるヒープのサイズです。この番号は、を構成するために使用されます``-Xms<size>`` パラメータの値 `java`。この数を減らすと、Javaの起動時に消費するメモリが少なくなります。（ただし、この数値を超えるとJavaでヒープの再割り当てが必要になる可能性が高くなるため、この数値を小さくしすぎないようにします）。
** *最大ヒープサイズ*は、クライアントを実行しているVMでJavaがヒープを拡張できる最大値です。この番号は、を構成するために使用されます``-Xmx<size>`` パラメータの値 `java`。
** [Log Level]は、クライアントログで生成される詳細の量を制御します。指定できる値は次の2つです。
+
*** INFO -「通常」の量の情報を生成します。
*** debug -デバッグに役立つ詳細情報をクライアントログに生成します。




. データソースのアラートを設定します。
. クライアントが表示するログイン警告メッセージを設定します。
. [ 保存（ Save ） ] をクリックします。

