---
permalink: config-admin/configuring-anomaly-detection-for-applications.html 
sidebar: sidebar 
keywords:  
summary: アプリケーションのインフラの異常な動作を監視するには、異常検出を有効にする必要があります。異常検出の監視は、アプリケーションに対してのみ有効または無効になります。 
---
= 異常検出用のアプリケーションの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプリケーションのインフラの異常な動作を監視するには、異常検出をオンにする必要があります。異常検出の監視は、アプリケーションに対してのみ有効または無効になります。



== 作業を開始する前に

* 異常検出エンジンをインストールして設定しておく必要があります。
* 異常検出情報を確認するすべてのアセットについて、コンピューティングリソース（仮想マシンまたはホスト）にアプリケーションを割り当てておく必要があります。残りのリソースはInsightによって自動的に検出されます。




== 手順

. OnCommand InsightWeb UIにログインします。
. [管理]*をクリックし、*[アプリケーション]*を選択します。
. コンピューティングリソースに割り当てられているアプリケーションを探します。
. [* Anomalies*（異常*）]セクションで、セクションの右上にある[* Monitor*（モニタ*）]コントロールボックスに* off *ではなく* on *が表示されていることを確認します。表示されていない場合は、[Monitor*（モニタ）]コントロールボックスの任意の場所をクリックして、コントロールを* on
+
最大48個のアプリケーションの異常を同時に監視できます。

+
セクションのステータスには、少なくとも1時間は「学習中」と表示されます。異常検出エンジンは、最大14日分の既存のパフォーマンスデータを事前にロードして、エンジンが環境の動作を学習できるようにします。Insight Serverで環境のアセットが最初にポーリングされると、その期間のアプリケーションのスコアが異常検出エンジンによって計算されて返されます。



* 関連情報 *

link:assigning-applications-to-assets.md#["アセットへのアプリケーションの割り当て"]
