---
permalink: config-admin/configuring-the-number-of-hours-to-ignore-dynamic-data.html 
sidebar: sidebar 
keywords:  
summary: 使用済み容量などの動的なデータの更新をOnCommand Insight が無視する時間数を設定できます。デフォルトの6時間を使用し、設定を変更しない場合、デフォルトの時間数が経過するまで、レポートは動的データで更新されません。このオプションを使用すると、動的なデータのみが変更された場合に更新が延期されるため、パフォーマンスが向上します。 
---
= 動的なデータを無視する時間数を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用済み容量などの動的なデータの更新をOnCommand Insight が無視する時間数を設定できます。デフォルトの6時間を使用し、設定を変更しない場合、デフォルトの時間数が経過するまで、レポートは動的データで更新されません。このオプションを使用すると、動的なデータのみが変更された場合に更新が延期されるため、パフォーマンスが向上します。



== このタスクについて

このオプションに値が設定されている場合、OnCommand Insight は次のルールに基づいて動的データを更新します。

* 設定は変更されず、容量データが変更された場合、データは更新されません。
* 動的なデータ（設定変更を除く）は、このオプションで指定したタイムアウト後にのみ更新されます。
* 構成が変更されると、構成データと動的データが更新されます。


このオプションの影響を受ける動的なデータには、次のものがあります。

* 容量違反のデータ
* ファイルシステムの割り当て済み容量と使用容量
* ハイパーバイザー
+
** 仮想ディスクの使用容量
** Virtual Machine Used Capacityの略


* 内部ボリューム
+
** データの割り当て容量
** データの使用容量
** 重複排除による削減量
** 最終アクセス時間
** 最終Snapshot時間
** その他の使用容量
** Snapshot数
** Snapshotの使用容量
** 合計使用容量


* iSCSIセッションのイニシエータIP、ターゲットセッションID、およびイニシエータセッションID
* qtreeクォータの使用容量
* クォータで使用されているファイルと使用済み容量
* Storage Efficiencyテクノロジ、ゲイン/損失、潜在的なゲイン/損失
* ストレージプール
+
** データの使用容量
** 重複排除による削減量
** その他の使用容量
** Snapshotの使用容量
** 合計使用容量


* ボリューム
+
** 重複排除による削減量
** 最終アクセス時間
** 使用済み容量






== 手順

. Insightのツールバーで、*[Admin]*をクリックし、*[Troubleshooting]*を選択します。
. ページ下部の[その他のタスク]領域で、*[高度なトラブルシューティング]*リンクをクリックします。
. [Advanced settings]*タブをクリックし、[Acquisition Dynamic Attributes]セクションで、OnCommand Insight がAcquisition Dynamic Attributesの動的データを無視する時間数を入力します。
. [ 保存（ Save ） ] をクリックします。
. （オプション）Acquisition Unitを再起動するには、[Restart Acquisition Unit]リンクをクリックします。
+
Local Acquisition Unitを再起動すると、OnCommand Insight のすべてのデータソースビューがリロードされます。この変更は次回のポーリング時に適用されるため、Acquisition Unitを再起動する必要はありません。


