---
permalink: config-admin/configuring-system-level-event-notifications.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight では、Acquisition Unitの障害やデータソースのエラーなど、システムレベルのイベントの通知がサポートされます。通知を受信するには、これらのイベントが発生したときにEメールを送信するようにInsightを設定する必要があります。 
---
= システムレベルのイベント通知の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight では、Acquisition Unitの障害やデータソースのエラーなど、システムレベルのイベントの通知がサポートされます。通知を受信するには、これらのイベントが発生したときにEメールを送信するようにInsightを設定する必要があります。



== 作業を開始する前に

* Admin *>* Notifications *>* Sending Methods *で通知を受信するEメール受信者を設定しておく必要があります。



== 手順

. [管理]*>*[通知]*をクリックします。
. [*イベント*]をクリックします。
. [System Alert Events]*[Email]セクションで、通知の重大度レベル（* Warning and above *または* Critical *）を選択します。システムレベルのイベントの通知を受信しない場合は、*[Do not send]*を選択します。
. [ 保存（ Save ） ] をクリックします。
. アラート自体を設定するには、*[管理]*>*[システムアラート]*をクリックします。
. 新しいアラートを追加するには、*+追加*をクリックし、一意の*名前*を指定します。右側のアイコンをクリックして*[編集]*既存のアラートを編集することもできます。
. アラートを送信する*イベントタイプ*を選択します（例：_Acquisition Unit Failure_）。
. 選択した時間間隔で選択したタイプの重複イベントに関する通知を停止するには、*スヌーズ*間隔を選択します。_never_を選択すると、イベントが発生しなくなるまで1分に1回通知が繰り返し送信されます。
. イベント通知の[Severity]*（[Warning]または[Critical]）を選択します。
. Eメール通知はデフォルトでグローバルEメール受信者リストに送信されます。または、表示されたリンクをクリックしてグローバルリストを上書きし、特定の受信者に通知を送信できます。
. [Save]をクリックしてアラートを追加します。

