---
permalink: config-admin/configuring-sso.html 
sidebar: sidebar 
keywords:  
summary: シングルサインオン\（SSO\）を使用すると、組織内のユーザーは特別なアカウントを必要とせずにOnCommand Insight を使用できます。 
---
= シングルサインオン（SSO）の設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シングルサインオン（SSO）を使用すると、組織内のユーザーは特別なアカウントを必要とせずにOnCommand Insight を使用できます。

管理者は、社内ドメイン内のユーザーの*シングルサインオン*（SSO）アクセス用にOnCommand Insight サーバーを構成できます。SSOが設定されている場合、ドメインのEメールアドレスを持つユーザは、社内クレデンシャルを使用してInsightにログインできます。OnCommand Insight は、SSO用のOpenID Connect（OIDC）プロトコルをサポートしています。

[NOTE]
====
SSOは、Insight ServerのWebベースUIでのみ使用できます。SSOは、Data Warehouse、Reporting、Java ClientのUIコンポーネントでは使用できません。

====


== SSOの設定手順

* メニューの[Admin][Settings]>[Users]に移動します。
* SSO設定URLを入力して、設定フィールド（「OpenID設定」とも呼ばれます）を自動入力します。これは、アイデンティティプロバイダの設定を記述するJSONを提供するURIです。
* または、次のアイデンティティプロバイダリソースのSSO設定URLを手動で入力します。これらのリソースに関する詳細情報へのリンクは、このページの下部にある「関連情報」セクションにあります。
+
** *認証エンドポイント*：ユーザにクレデンシャルの入力を求めるアイデンティティプロバイダリソース。成功すると、IDはOnCommand Insight に承認付与を発行し、ユーザーに代わってアクションを実行できるようにします。
** *JWK Set URI *: JWTトークンに署名するために使用される公開鍵を提供します。これにより、クライアントはJWTトークンがサードパーティではなくアイデンティティプロバイダによって実際に発行されたものであることを確認できます。
** *トークンエンドポイント*：クライアントがJWTトークンの承認付与を取引するアイデンティティプロバイダリソース。クライアントは、クライアントIDとクライアントシークレットも提供する必要があります（下記を参照）。Insightで使用されるJWTトークンは「IDトークン」で、ユーザのユーザ名とロールを示します。
** *セッションの終了エンドポイント*：IDプロバイダによって提供されます。クライアント（OCI）によってブラウザがリダイレクトされ、IDプロバイダによってIDプロバイダとのユーザのセッションが無効になります。つまり、次回のサインオン時に、ユーザはクレデンシャルを入力する必要があります。


* *クライアントID *：クライアント（OCI）を一意に識別し、アイデンティティプロバイダによって認識されている他のクライアントと区別します。アイデンティティプロバイダは、アプリケーションの作成時にクライアントIDを生成します。クライアントは、トークン要求の一部としてクライアントIDを提示するため、クライアントIDを認識している必要があります。
* * Client Secret *：アイデンティティプロバイダとクライアントだけが認識するランダムな文字列。アイデンティティプロバイダに対してクライアントを認証します。この文字列は、クライアントが自身が主張するアプリケーションであり、悪意のあるサードパーティではないことを証明します。クライアントIDとともに、クライアントシークレットがトークン要求の一部としてアイデンティティプロバイダに渡されます。クライアントシークレットは、アイデンティティプロバイダによって生成されます。Azure Active Directoryでは、複数のクライアントシークレットが許可されます。
* *ユーザー名のJWT要求*:ユーザーのユーザー名を識別するID JWTトークン内の要求。クレームは、JWTトークンのJSONペイロード内のキーと値のペアです。設定された「JTW claim for username」はキーの名前であり、IDトークンごとに、値は認証されるユーザのユーザ名です。キー名は、アイデンティティプロバイダによって異なる場合があります。Azure Active Directoryの場合、要求名は通常「preferred_username」になります。
* *ロールのJWT請求*：上記と同様ですが、OCIロールのリスト（「guest」、「user」、「admin」など）がこの請求に含まれる点が異なります。Azure Active Directoryの場合、このキーの名前は「roles」です。




== SSL証明書を管理します

アイデンティティプロバイダのSSL証明書チェーンのルート証明書をインポートする必要があります。そのためには、トークンエンドポイントのホスト名に関連付けられたルート証明書をダウンロードします。（Azure Active Directoryの場合はlogin.microsoftonline.com）、ファイルに保存します。次に、「証明書」ボタンをクリックし、「手動」タブを使用してファイルを選択し、「so-root'」などのエイリアスを指定してインポートします。

SSOがすでに有効になっており、新しい証明書をインポートした場合は、SANscreen サービスを再起動する必要があります。



== オペレーティングシステムでSSOを有効にする

現在のシステムでSSOを有効にし、ssoAuthシステムプロパティをアップグレードによって保持するには、次の手順を実行する必要があります。

WindowsでSSOを有効にするには、レジストリで_HKEY_LOCAL_MACHINE\SOFTWARE\NetApp\SANscreen_に移動します。ssoAuthの値をfalseからtrueに変更します。この値はアップグレード中に読み取られ、アップグレードされたシステムのssoAuthシステムプロパティの設定に使用されます。このコマンドは現在のインスタンスには影響しません。また、_HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Apache Software Foundation\Procrun 2.0\SANscreen Server\Parameters\Java Options_でssoAuthを更新する必要があります。

LinuxでSSOを有効にするには、_/opt/netapp/oci/conf/に移動して_wildfly.properties_ファイルを開きます。_sso_auth_enabled_の 値をfalseからtrueに変更します。

SSOを有効にしたら、SANscreen サービスを再起動します。



== SSOの問題のトラブルシューティング

「Not Authorized」エラーが表示された場合は、server.logで詳細を確認してください。このエラーは、認証に失敗したことがInsightで報告されたが、アイデンティティプロバイダによってユーザが正しく認証された場合に表示されることがあります。

ユーザがSSOでログインできない場合は、管理者権限を持つ非SSOユーザとしてログインし、SSO設定を修正します。これを行うには、ブラウザウィンドウで___<Your Insight URL> **/uiserver/login.html#**_と入力します。

* 関連情報 *

https://ldapwiki.com/wiki/Openid-configuration[]

https://ldapwiki.com/wiki/Authorization_endpoint[]

https://ldapwiki.com/wiki/JWK%20Set[]

https://ldapwiki.com/wiki/Token_endpoint[]

https://ldapwiki.com/wiki/End_session_endpoint[]

https://ldapwiki.com/wiki/Client_id[]

https://ldapwiki.com/wiki/Client%20Secret[]

https://ldapwiki.com/wiki/Identity%20Token[]
