---
permalink: config-admin/creating-an-application-performance-policy.html 
sidebar: sidebar 
keywords: anomaly score 
summary: アプリケーションの異常スコアに基づいてアプリケーションパフォーマンスポリシーを作成できます。しきい値を超えると、アプリケーションのリソースに関連する問題を通知するアラートがトリガーされます。 
---
= アプリケーションパフォーマンスポリシーを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプリケーションの異常スコアに基づいてアプリケーションパフォーマンスポリシーを作成できます。しきい値を超えると、アプリケーションのリソースに関連する問題を通知するアラートがトリガーされます。



== 作業を開始する前に

アプリケーションのパフォーマンスポリシーに設定されているしきい値を監視するには、Insightサーバで異常検出エンジンが実行されている必要があります。



== このタスクについて

監視が必要なさまざまなタイプの異常スコアに関するアラートを提供するポリシーを作成できます。

* 異常の急増を特定するには、最初の発生時にアラートを生成するポリシーを作成し、しきい値を高い異常スコア（90以上）に設定します。
* 時間の経過に伴う動作の変化を特定するには、中程度の異常スコアで1時間後にアラートを生成するポリシーを作成します。このポリシーは、3つの連続した異常検出スコアに基づいてアラートを提供します。




== 手順

. ブラウザでOnCommand Insight を開きます。
. [管理]*>*[パフォーマンスポリシー]*をクリックします
+
パフォーマンスポリシーページが表示されます。

. 「*+追加」をクリックします。
+
[Add Policy]ダイアログボックスが表示されます。

. [ポリシー名]*フィールドに一意のポリシー名を入力します。
+
オブジェクトの他のすべてのポリシーとは異なる名前を使用する必要があります。

. [タイプのオブジェクトに適用（Apply to objects of type）]リストから[アプリケーション（Application）]を選択する。
. [アプリケーションの優先度]リストからアプリケーションの優先度を選択します。
. [Apply after a window of *]リストで、しきい値違反を示すアラートが生成されるタイミングを選択します。
+
[First occurrence]オプションを指定すると、最初のスコアでしきい値を超えたときにアラートがトリガーされます。それ以外のオプションでは、しきい値を超えたあと、その状態のまま一定の時間を経過した時点でアラートがトリガーされます。

+
異常スコアは30分間隔（時速5分、時速35分）で表示されるため、30で割り切れる期間のみを選択する必要があります。

+
|===


| のウィンドウの後に適用します | 違反をスローするために必要なバケットの数 


 a| 
初登場
 a| 
1.



 a| 
5 分
 a| 
2.



 a| 
10分だ
 a| 
2.



 a| 
15 分
 a| 
2.



 a| 
30 分
 a| 
2.



 a| 
45分だ
 a| 
3.



 a| 
1 時間
 a| 
3.



 a| 
2時間
 a| 
4.

|===
. [警告]*リストから、[重大]または[警告]を選択します
. デフォルトのEメール通知方法を変更する場合は、Eメールを設定します。
. [Create alert if *]セクションで演算子を選択し、値を入力してしきい値を作成します。異常スコアは、アプリケーションのパフォーマンスポリシーに使用される唯一のパフォーマンスカウンタです。
+
次のような範囲を使用して一連のアラートを作成できます。

+
** 0-20警告アラート
** 21-50警告アラート
** 51-80警告アラート
** 80件を超える重大アラート


. アラートが発生したときにポリシーの処理を停止するには、*[アラートが生成された場合に追加のポリシーを停止する]*チェックボックスをオンにします。




== 結果

通知だけが違反を表示する手段ではありません。違反はアプリケーションランディングページと違反ダッシュボードに表示され、フィルタリングできます。ダッシュボードを作成したり、違反テーブルウィジェットを追加したり、パフォーマンスポリシー名でフィルタしてアプリケーション違反を特定したりすることもできます。
