---
permalink: config-admin/defining-applications.html 
sidebar: sidebar 
keywords:  
summary: 環境で実行されている特定のアプリケーションに関連するデータを追跡するには、それらのアプリケーションを定義する必要があります。 
---
= アプリケーションの定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境で実行されている特定のアプリケーションに関連するデータを追跡するには、それらのアプリケーションを定義する必要があります。



== 作業を開始する前に

アプリケーションをビジネスエンティティに関連付ける場合は、ビジネスエンティティを作成しておく必要があります。



== このタスクについて

アプリケーションを関連付けることができるアセットは、ホスト、仮想マシン、ボリューム、内部ボリューム、 qtree 、 共有、ハイパーバイザー：



== 手順

. OnCommand Insight Web UIにログインします。
. [管理]*をクリックし、*[アプリケーション]*を選択します。
+
アプリケーションを定義すると、[アプリケーション]ページにアプリケーションの名前と優先度、およびアプリケーションに関連付けられているビジネスエンティティ（該当する場合）が表示されます。

. [ 追加（ Add ） ] をクリックします。
+
[アプリケーションの追加]ダイアログボックスが表示されます。

. [名前]ボックスにアプリケーションの一意の名前を入力します。
. [優先度]*をクリックし、環境内のアプリケーションの優先度（[重大]、[高]、[中]、[低]）を選択します。
. このアプリケーションを特定のビジネスエンティティで使用する場合は、*[Business Entity]*をクリックし、リストからエンティティを選択します。
. *オプション*：ボリューム共有を使用しない場合は、*[Validate volume sharing]*ボックスをオフにします。
+
これにはAssureライセンスが必要です。この値は、クラスタ内の同じボリュームに各ホストがアクセスできるようにする場合に設定します。たとえば、高可用性クラスタのホストは、フェイルオーバーを可能にするために同じボリュームにマスクする必要があることがよくありますが、無関係なアプリケーションのホストは通常、同じ物理ボリュームにアクセスする必要はありません。また、セキュリティ上の理由から、関係のないアプリケーションによる同じ物理ボリュームへのアクセスを明示的に禁止するように規制ポリシーで規定されている場合があります。

. [ 保存（ Save ） ] をクリックします。
+
[Applications]ページにアプリケーションが表示されます。アプリケーションの名前をクリックすると、そのアプリケーションのアセットページが表示されます。





== 完了後

アプリケーションを定義したら、ホスト、仮想マシン、ボリューム、内部ボリューム、またはハイパーバイザーのアセットページに移動して、アプリケーションをアセットに割り当てることができます。
