---
permalink: config-admin/dell-emc-powerstore-data-source.html 
sidebar: sidebar 
keywords:  
summary: Dell EMC PowerStoreデータコレクタは、Dell EMC PowerStoreストレージからインベントリ情報を収集します。データコレクタを設定するには、ストレージプロセッサの IP アドレス、および読み取り専用のユーザ名とパスワードが必要です。 
---
= Dell EMC PowerStoreデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dell EMC PowerStoreデータコレクタは、Dell EMC PowerStoreストレージからインベントリ情報を収集します。データコレクタを設定するには、ストレージプロセッサの IP アドレス、および読み取り専用のユーザ名とパスワードが必要です。



== 用語集

OnCommand Insight では、EMC Data Domainデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
ホスト
 a| 
ホスト



 a| 
host_volume_mapping
 a| 
host_volume_mapping



 a| 
ハードウェア（「 extra_details 」オブジェクトにドライブが含まれています）：ドライブ
 a| 
ディスク



 a| 
アプライアンス
 a| 
ストレージプール



 a| 
クラスタ
 a| 
ストレージアレイ



 a| 
ノード
 a| 
ストレージノード



 a| 
FC ポート
 a| 
ポート



 a| 
ボリューム
 a| 
ボリューム



 a| 
内部ボリューム
 a| 
ファイルシステム



 a| 
ファイルシステム
 a| 
内部ボリューム



 a| 
ミトリー
 a| 
qtree



 a| 
クォータ
 a| 
クォータ



 a| 
NFS 共有および CIFS 共有
 a| 
ファイル共有

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* ストレージプロセッサの IP アドレスまたは完全修飾ドメイン名
* 読み取り専用のユーザ名とパスワード




== 親シリアル番号の説明

従来、Insightでは、ストレージアレイのシリアル番号や個 々 のストレージノードのシリアル番号をレポートすることができました。ただし、一部のストレージアレイアーキテクチャはこれに適切に対応していません。PowerStoreクラスタは1~4台のアプライアンスで構成でき、各アプライアンスには2つのノードがあります。アプライアンス自体のシリアル番号がある場合、そのシリアル番号はクラスタのシリアル番号でもノードのシリアル番号でもありません。

大規模なクラスタの一部にすぎない中間アプライアンス/エンクロージャに個 々 のノードが配置されている場合、ストレージノードオブジェクトの「Parent Serial Number」属性がDell/EMC PowerStoreアレイ用に適切に設定されます。



== 設定

|===


| フィールド | 説明 


 a| 
PowerStore ゲートウェイ
 a| 
PowerStore ストレージの IP アドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
PowerStore のユーザー名



 a| 
パスワード
 a| 
PowerStore のパスワード

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
HTTPS ポート
 a| 
デフォルトは 443 です



 a| 
インベントリポーリング間隔（分）
 a| 
インベントリのポーリング間隔。デフォルトは 60 分です。

|===
OnCommand InsightのPowerStoreパフォーマンスコレクションでは、PowerStoreの5分単位のソースデータを使用します。そのため、Insightは5分ごとにそのデータをポーリングします。このポーリングは設定できません。
