---
permalink: config-admin/dell-emc-ecs-data-source.html 
sidebar: sidebar 
keywords:  
summary: このデータコレクタは、 EMC ECS ストレージシステムからインベントリデータとパフォーマンスデータを取得します。データコレクタを設定するには、ECSサーバのIPアドレスと管理者レベルのドメインアカウントが必要です。 
---
= Dell EMC ECSデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このデータコレクタは、 EMC ECS ストレージシステムからインベントリデータとパフォーマンスデータを取得します。データコレクタを設定するには、ECSサーバのIPアドレスと管理者レベルのドメインアカウントが必要です。



== 用語集

OnCommand Insight では、EMC ECSデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
クルーザー
 a| 
ストレージ



 a| 
テナント
 a| 
ストレージプール



 a| 
バケット
 a| 
内部ボリューム



 a| 
ディスク
 a| 
ディスク

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* ECS 管理コンソールの IP アドレス
* ECS システムの管理者レベルドメインアカウント
* ポート 443 （ HTTPS ）：ECS システムで TCP ポート 443 へのアウトバウンド接続が必要です。
* パフォーマンスを確保するには、 ssh/scp アクセス用の読み取り専用のユーザ名とパスワードを使用します。
* パフォーマンスを確保するには、ポート 22 が必要です。




== 設定

|===


| フィールド | 説明 


 a| 
ECS ホスト
 a| 
ECSシステムのIPアドレスまたは完全修飾ドメイン名



 a| 
ECS ホストポート
 a| 
ECS ホストとの通信に使用されるポート



 a| 
ECS ベンダー ID
 a| 
ECS のベンダー ID



 a| 
パスワード
 a| 
ECS のパスワード

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリのポーリング間隔。デフォルトは 360 分です。

|===