---
permalink: config-admin/designing-your-business-entities-hierarchy.html 
sidebar: sidebar 
keywords:  
summary: 企業構造の要素と、ビジネスエンティティで何を表す必要があるかを理解する必要があります。これは、それらがOnCommand Insight データベースで固定構造になるためです。次の情報を使用してビジネスエンティティをセットアップできます。これらのカテゴリのデータを収集するために、すべての階層レベルを使用する必要はないことに注意してください。 
---
= ビジネスエンティティ階層の設計
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
企業構造の要素と、ビジネスエンティティで何を表す必要があるかを理解する必要があります。これは、それらがOnCommand Insight データベースで固定構造になるためです。次の情報を使用してビジネスエンティティをセットアップできます。これらのカテゴリのデータを収集するために、すべての階層レベルを使用する必要はないことに注意してください。



== 手順

. ビジネスエンティティ階層の各レベルを調べて、そのレベルを会社のビジネスエンティティ階層に含める必要があるかどうかを判断します。
+
** *テナント*レベルは、会社がISPで、顧客のリソース使用状況を追跡する場合に必要です。
** *さまざまな製品ラインのデータを追跡する必要がある場合は、基幹業務（LOB）*が階層に必要です。
** *部門ごとにデータを追跡する必要がある場合は、ビジネスユニット*が必要です。この階層レベルは、1つの部門が使用するリソースと、他の部門が使用しないリソースを分離するのに役立ちます。
** *プロジェクト*レベルは、部門内の特殊な作業に使用できます。このデータは、企業や部門内の他のプロジェクトと比較して、個別のプロジェクトのテクノロジニーズを特定、定義、および監視するのに役立ちます。


. 各ビジネスエンティティとそのエンティティ内のすべてのレベルの名前を示すグラフを作成します。
. 階層内の名前をチェックして、OnCommand Insight のビューやレポートでわかりやすい名前になっていることを確認します。
. 各ビジネスエンティティに関連付けられているアプリケーションをすべて特定します。

