---
permalink: config-admin/device-resolution.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight で監視するすべてのデバイスを検出する必要があります。環境内のパフォーマンスとインベントリを正確に追跡するには、検出が必要です。通常、環境内のほとんどのデバイスは自動デバイス解決によって検出されます。 
---
= デバイス解決
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight で監視するすべてのデバイスを検出する必要があります。環境内のパフォーマンスとインベントリを正確に追跡するには、検出が必要です。通常、環境内のほとんどのデバイスは自動デバイス解決によって検出されます。

[NOTE]
====
アップグレードを実行する際に、アップグレード元のシステムに非アクティブの自動解決ルールがあると、それらのルールはアップグレード時に削除されます。アクティブでない自動解決ルールを保持するには、アップグレードの実行前にルールをアクティブ化（チェックボックスをオンに）します。

====
データソースをインストールして設定すると、環境内のデバイス（スイッチ、ストレージアレイ、ハイパーバイザーとVMの仮想インフラなど）が識別されます。ただし、通常は環境内のすべてのデバイスが識別されるわけではありません。

データソースタイプのデバイスを設定したら、デバイス解決ルールを利用して環境内の残りの不明なデバイスを特定することを推奨します。デバイス解決は、次のデバイスタイプとして不明なデバイスの解決に役立ちます。

* 物理ホスト
* ストレージアレイ
* テープだ
* スイッチ


デバイス解決後に「不明」と表示されたままのデバイスは汎用デバイスとみなされ、クエリやダッシュボードにも表示できます。

似た属性の新しいデバイスが以降に環境に追加されると、作成したルールに基づいて自動的に識別されます。場合によっては、Insightで検出されないデバイスに対するデバイス解決ルールをバイパスして、手動で識別することもできます。

デバイスの識別が完了していないと、次のような問題が発生する可能性

* 不完全なパスです
* マルチパス接続が識別されない
* アプリケーションをグループ化できない
* 正確なトポロジが表示されない
* Data Warehouse や Reporting で正確なデータが表示されない


デバイス解決機能（* Manage *>* Device resolution *）には、次のタブがあります。各タブは、デバイス解決の計画と結果の表示に役割を果たします。

* 「FC Identify」には、自動デバイス解決で解決されなかったファイバチャネルデバイスのWWNとポート情報のリストが表示されます。識別されたデバイスの割合も表示されます。
* 「IP identify」には、自動デバイス解決で識別されなかったCIFS共有およびNFS共有にアクセスするデバイスのリストが含まれます。識別されたデバイスの割合も表示されます。
* 「自動解決ルール」には、ファイバチャネルデバイス解決の実行時に実行されるルールのリストが含まれます。これらのルールは、識別されないファイバチャネルデバイスを解決するために作成します。
* 「環境設定」では、環境に合わせてデバイス解決をカスタマイズするための設定オプションを提供します。

