---
permalink: config-admin/e-series-landing-page-terminology-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: NetApp Eシリーズストレージプールのアセットランディングページに記載されているオブジェクトや参照に適用される用語。 
---
= Eシリーズストレージプール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Eシリーズストレージプールのアセットランディングページに記載されているオブジェクトや参照に適用される用語。



== Eシリーズストレージプールの用語

以下の用語は、NetApp Eシリーズストレージプールのアセットランディングページに表示されるオブジェクトや参照先に適用されます。これらの用語の多くは、他のデータコレクタにも適用されます。

* ストレージ--このプールが配置されているストレージアレイ必須。
* タイプ(Type)--可能性の列挙されたリストから'説明的な値を指定します最も一般的な構成は「シンプロビジョニング」または「RAIDグループ」です。
* ノード：このストレージアレイのアーキテクチャでプールが特定のストレージノードに属する場合は、ストレージアレイの名前が独自のランディングページへのハイパーリンクとして表示されます。
* Flash Poolを使用（「はい」または「いいえ」）
* redundancy -- RAIDレベルまたは保護スキーム。Eシリーズでは、DDPプールについて「RAID 7」が報告されます。
* 容量--使用済み論理容量、使用可能容量、論理合計容量、およびこれらの使用率が表示されます。どちらの値にもEシリーズの「予約済み」容量が含まれるため、Eシリーズのユーザインターフェイスで表示される数値と割合がどちらも大きくなります。
* オーバーコミット容量：効率化テクノロジを使用して、ストレージプールの論理容量よりも大きい合計ボリューム容量を割り当てた場合、この割合の値は0%より大きくなります。
* スナップショット--使用中のスナップショット容量と合計容量(ストレージプールアーキテクチャがその容量の一部をスナップショット専用のセグメント領域に使用している場合)
* 利用率：このストレージプールに容量を提供しているディスクのうち、ディスクビジー率が最も高い割合を示すパーセンテージ。ディスク利用率は、必ずしもアレイのパフォーマンスと強い相関関係があるとは限りません。ホスト駆動型のワークロードがない場合、ディスクのリビルドや重複排除処理などが原因で利用率が高くなる可能性があります。また、多くのアレイのレプリケーション実装では、ボリュームのワークロードとしては表示されませんが、ディスク利用率が上昇する可能性があります。
* IOPS --このストレージプールに容量を提供しているすべてのディスクの合計IOPS。
* スループット--このストレージプールに容量を提供しているすべてのディスクの合計スループット

