---
permalink: config-admin/editing-multiple-data-sources.html 
sidebar: sidebar 
keywords: bulk edit 
summary: 同じベンダーおよびモデルの複数のデータソースについて、ほとんどの情報を一度に編集できます。たとえば、これらのデータソースでユーザ名とパスワードが共有されている場合は、一箇所でパスワードを変更して、選択したすべてのデータソースのパスワードを更新できます。 
---
= 複数のデータソースの情報を編集する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
同じベンダーおよびモデルの複数のデータソースについて、ほとんどの情報を一度に編集できます。たとえば、これらのデータソースでユーザ名とパスワードが共有されている場合は、一箇所でパスワードを変更して、選択したすべてのデータソースのパスワードを更新できます。



== このタスクについて

選択したデータソースについて編集できないオプションは、[データソースの編集]ダイアログボックスでグレー表示または非表示になります。また、オプションの値が「* Mixed *」と表示されている場合は、選択したデータソース間でオプションの値が異なることを示します。たとえば、選択した2つのデータソースの* Timeout (sec)*オプションが* Mixed *の場合、一方のデータソースのタイムアウト値は60、もう一方のデータソースの値は90になります。 したがって、この値を120に変更してデータソースへの変更を保存すると、両方のデータソースのタイムアウト設定が120になります。



== 手順

. [Admin]*をクリックし、データソースのリストビューに移動します
. 変更するデータソースを選択します。同じベンダー、モデル、Acquisition Unitに属しているデータソースを選択する必要があります。
. [アクション]*ボタンをクリックし、*[編集]*オプションを選択します。
. 編集ダイアログで、必要に応じて*設定*を変更します。
. [Configuration]*リンクをクリックして、データソースの基本オプションを変更します。
. [Advanced Configuration]*リンクをクリックして、データソースの詳細オプションを変更します。
. [ 保存（ Save ） ] をクリックします。

