---
permalink: config-admin/emc-datadomain-data-source.html 
sidebar: sidebar 
keywords:  
summary: このデータソースは、EMC Data Domain重複排除ストレージシステムからストレージと構成の情報を収集します。データソースを追加するには、特定の設定手順とコマンドを使用し、データソースの要件と使用に関する推奨事項を確認しておく必要があります。 
---
= EMC Data Domainデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このデータソースは、EMC Data Domain重複排除ストレージシステムからストレージと構成の情報を収集します。データソースを追加するには、特定の設定手順とコマンドを使用し、データソースの要件と使用に関する推奨事項を確認しておく必要があります。



== 用語集

OnCommand Insight では、EMC Data Domainデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
ディスク
 a| 
ディスク



 a| 
配列
 a| 
ストレージ



 a| 
ポート
 a| 
ポート



 a| 
ファイルシステム
 a| 
内部ボリューム



 a| 
ミトリー
 a| 
qtree



 a| 
クォータ
 a| 
クォータ



 a| 
NFS 共有および CIFS 共有
 a| 
ファイル共有

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* Data Domain デバイスの IP アドレス
* Data Domain ストレージに対する読み取り専用のユーザ名とパスワード
* SSH ポート 22




== 設定

|===


| フィールド | 説明 


 a| 
IP アドレス
 a| 
Data Domain ストレージアレイの IP アドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
Data Domain ストレージアレイのユーザ名



 a| 
パスワード
 a| 
Data Domain ストレージアレイのパスワード

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは20分）



 a| 
SSHプロセス待機タイムアウト（秒）
 a| 
SSHプロセスのタイムアウト（デフォルトは180秒）



 a| 
SSH ポート
 a| 
SSH サービスポート

|===