---
permalink: config-admin/emc-isilon-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: Isilon SSHデータソースは、EMC IsilonスケールアウトNASストレージからインベントリとパフォーマンスを収集します。 
---
= EMC Isilonデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Isilon SSHデータソースは、EMC IsilonスケールアウトNASストレージからインベントリとパフォーマンスを収集します。



== 用語集

OnCommand Insight では、EMC Isilonデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
ドライブ
 a| 
ディスク



 a| 
クラスタ
 a| 
ストレージ



 a| 
ノード
 a| 
ストレージノード



 a| 
File System の略
 a| 
内部ボリューム

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* Isilon ストレージに対する管理者権限
* を使用してアクセスを検証 `telnet` ポート22に接続します




== 設定

|===


| フィールド | 説明 


 a| 
IP アドレス
 a| 
Isilon クラスタの IP アドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
Isilonクラスタのユーザ名



 a| 
パスワード
 a| 
Isilonクラスタのパスワード

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは20分）



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）



 a| 
SSHプロセス待機タイムアウト
 a| 
SSHプロセスのタイムアウト（デフォルトは60秒）



 a| 
SSH ポート
 a| 
SSH サービスポート

|===


== CLIコマンドの実行

OnCommand Insight バージョン7.3.11およびサービスパック9以降、EMC Isilonデータソースには、より多くのCLIコマンドが実行されるようになる拡張機能が含まれています。データソース内でroot以外のユーザを使用している場合は、「sudoers」ファイルを設定して、そのユーザアカウントにSSH経由で特定のCLIコマンドを実行する権限を付与している可能性があります。

InsightでEMCのアクセスゾーン機能を理解するために'次の新しいCLIコマンドが追加で実行されるようになりました

* `sudo isi zone zones list --format json –verbose`
* `sudo isi zone zones list`


Insightでは、これらのコマンドの出力を解析し、既存のコマンドのインスタンスを追加で実行して、デフォルト以外のアクセスゾーンに存在するqtree、クォータ、NAS共有/エクスポートなどのオブジェクトの論理構成を取得します。この機能拡張の結果、デフォルト以外のアクセスゾーンについてこれらのオブジェクトが報告されるようになりました。Insightでは、既存のコマンド（オプションが異なる）を実行してデータを取得するため、sudoersファイルを変更する必要はありません。変更が必要になるのは、上記の新しいコマンドを導入したときだけです。

このInsightリリースにアップグレードする前に、sudoersファイルを更新してInsightサービスアカウントでこれらのコマンドが実行されるようにしてください。これを行わないと、Isilonデータソースに障害が発生します。



== 「ファイルシステム」統計

OnCommand Insight 7.3.12以降では、EMC Isilonデータコレクタによって、EMC Isilonのノードオブジェクトに関する「ファイルシステム」統計が導入されています。OnCommand Insight によって報告される既存のノードの統計は「ディスク」ベースです。ストレージノードのIOPSとスループットの場合、このノードのディスクはアグリゲートで何をしていますか？ただし、読み取りがメモリにキャッシュされたり、圧縮が使用されたりするワークロードの場合、ファイルシステムのワークロードは実際にディスクにヒットするワークロードよりも大幅に高くなる可能性があります。つまり、5：1で圧縮されるデータセットの場合は、「ファイルシステムの読み取りスループット」の値がストレージノードの5倍になる可能性があります。読み取りスループット、 後者はディスクからの読み取りを測定します。これは、ノードがデータを解凍してクライアントの読み取り要求を処理すると5倍に拡張されます。
