---
permalink: config-admin/emc-celerra-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: Celerra\（SSH\）データソースは、Celerraストレージからインベントリ情報を収集します。このデータソースを設定するには、ストレージプロセッサのIPアドレス、および読み取り専用のユーザ名とパスワードが必要です。 
---
= EMC Celerraデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Celerra（SSH）データソースは、Celerraストレージからインベントリ情報を収集します。このデータソースを設定するには、ストレージプロセッサのIPアドレス、および_read-only_userの名前とパスワードが必要です。



== 用語集

OnCommand Insight では、EMC Celerraデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
Celerra Network Serverの略
 a| 
ストレージ



 a| 
Celerraメタ・ボリューム/Celerraストレージ・プール
 a| 
ストレージプール



 a| 
File System の略
 a| 
内部ボリューム



 a| 
データムーバー
 a| 
コントローラ



 a| 
Data Moverにマウントされたファイルシステム
 a| 
ファイル共有



 a| 
CIFS および NFS エクスポート
 a| 
共有



 a| 
ディスクボリューム
 a| 
バックエンド LUN

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* ストレージプロセッサの IP アドレス
* 読み取り専用のユーザ名とパスワード
* SSH ポート 22




== 設定

|===


| フィールド | 説明 


 a| 
Celerraのアドレス
 a| 
CelerraデバイスのIPアドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
Celerraデバイスへのログインに使用する名前



 a| 
パスワード
 a| 
Celerraデバイスへのログインに使用するパスワード

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは20分）



 a| 
SSHプロセス待機タイムアウト（秒）
 a| 
SSHプロセスのタイムアウト（デフォルトは600秒）



 a| 
再試行回数
 a| 
インベントリの再試行回数



 a| 
SSHバナー待機タイムアウト（秒）
 a| 
SSHバナーのタイムアウト（デフォルトは20秒）

|===