---
permalink: config-admin/emc-vplex-cli-data-source.html 
sidebar: sidebar 
keywords:  
summary: このデータソースを設定するには、VPLEXサーバのIPアドレスと管理者レベルのドメインアカウントが必要です。 
---
= EMC VPLEXデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このデータソースを設定するには、VPLEXサーバのIPアドレスと管理者レベルのドメインアカウントが必要です。



== 用語集

OnCommand Insight では、EMC VPLEXデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
クラスタ
 a| 
ストレージ



 a| 
エンジン
 a| 
ストレージノード



 a| 
デバイス、システム拡張
 a| 
バックエンドストレージプール



 a| 
仮想ボリューム
 a| 
ボリューム



 a| 
フロントエンドポート、バックエンドポート
 a| 
ポート



 a| 
分散デバイス
 a| 
ストレージ同期



 a| 
ストレージビュー
 a| 
ボリュームマップ、ボリュームマスク



 a| 
ストレージボリューム
 a| 
バックエンド LUN



 a| 
ITL
 a| 
バックエンドパス

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* VPLEXサーバのIPアドレス
* VPLEX サーバの管理者レベルのドメインアカウント
* ポート 443 （ HTTPS ）：VPLEX 管理ステーションの TCP ポート 443 へのアウトバウンド接続が必要です。
* パフォーマンスを確保するには、 ssh/scp アクセス用の読み取り専用のユーザ名とパスワードを使用します。
* パフォーマンスを確保するには、ポート 22 が必要です。
* アクセスの検証：を使用して検証します `telnet` ポート443に接続します。デフォルトポート以外のポートの場合は、任意のブラウザでを使用します




== 設定

|===


| フィールド | 説明 


 a| 
VPLEX Management Console の IP アドレス
 a| 
VPLEX Management Console の IP アドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
VPLEX CLI のユーザ名



 a| 
パスワード
 a| 
VPLEX CLI のパスワード



 a| 
VPLEX Management ConsoleのパフォーマンスリモートIPアドレス
 a| 
VPLEX Management Console のパフォーマンスリモートの IP アドレス



 a| 
パフォーマンスリモートユーザ名
 a| 
VPLEX Management Console のパフォーマンスリモートのユーザ名



 a| 
パフォーマンスリモートパスワード
 a| 
VPLEX Management Console のパフォーマンスリモートのパスワード

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
通信ポート
 a| 
VPLEX CLIに使用するポート



 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは20分）



 a| 
接続タイムアウト（秒）
 a| 
接続タイムアウト（デフォルトは60秒）



 a| 
再試行回数
 a| 
インベントリの再試行回数



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスポーリング間隔（デフォルトは600秒）



 a| 
パフォーマンスSSHプロセス待機タイムアウト（秒）
 a| 
SSHプロセスのタイムアウト（デフォルトは600秒）



 a| 
SSHバナー待機タイムアウト（秒）
 a| 
SSHバナーのタイムアウト（デフォルトは20秒）



 a| 
再試行回数
 a| 
パフォーマンスの再試行回数

|===