---
permalink: config-admin/enabling-the-syslog-facility.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 違反、パフォーマンスアラート、および監査メッセージのログの場所を特定し、ロギングプロセスをアクティブ化できます。 
---
= syslogファシリティのイネーブル化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 違反、パフォーマンスアラート、および監査メッセージのログの場所を特定し、ロギングプロセスをアクティブ化できます。



== 作業を開始する前に

* システムログを格納するサーバのIPアドレスが必要です。
* メッセージを記録するプログラムのタイプ（local1やuserなど）に対応するファシリティレベルを把握しておく必要があります。




== このタスクについて

syslogには、次のタイプの情報が含まれます。

* 違反メッセージ
* パフォーマンスアラート
* 必要に応じて、監査ログメッセージ


syslogでは次の単位が使用されます。

* 利用率の指標：割合
* トラフィックの指標：MB
* トラフィックレート：MB/秒




== 手順

. Insightのツールバーで、*[Admin]*をクリックし、*[Notifications]*を選択します。
. ページの* Syslog *セクションまで下にスクロールします。
. [Enable syslog]チェックボックスをオンにします。
. 必要に応じて、*監査を送信*チェックボックスをオンにします。新しい監査ログメッセージは[Audit]ページに表示されるだけでなく、syslogに送信されます。既存の監査ログメッセージはsyslogには送信されず、新しく生成されたログメッセージのみが送信されます。
. [*Server*]フィールドに、ログサーバのIPアドレスを入力します。
+
カスタムポートを指定するには、サーバIPの末尾にコロンの後に追加します（例：server:port）。portを指定しない場合は、デフォルトのsyslogポートである514が使用されます。

. [*Facility*]フィールドで、メッセージを記録するプログラムのタイプに対応するファシリティレベルを選択します。
. [ 保存（ Save ） ] をクリックします。

