---
permalink: config-admin/examining-network-performance.html 
sidebar: sidebar 
keywords:  
summary: ストレージ環境のパフォーマンスを調べて、利用率の低いリソースや利用率の高いリソースを特定し、リスクを未然に特定して問題に発展させることができます。 
---
= ネットワークパフォーマンスの確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ環境のパフォーマンスを調べて、利用率の低いリソースや利用率の高いリソースを特定し、リスクを未然に特定して問題に発展させることができます。

Insightを使用すると、収集したストレージのデータから明らかになったパフォーマンスや可用性の問題を解決または防止できます。

Insightを使用して、次のパフォーマンス管理タスクを実行できます。

* 環境全体のパフォーマンスを監視
* 他のデバイスのパフォーマンスに影響を与えるリソースを特定する




== ポートの重要性

Insight ServerとData Warehouse（DWH）サーバを確実に動作させるには、いくつかのTCPポートを空けておく必要があります。これらのポートの一部は、localhostアダプタ（127.0.0.1）にバインドされたプロセスにのみ使用されますが、コアサービスが確実に動作するためには引き続き必要です。必要なポート数は、ネットワーク全体で使用されるポートのスーパーセットです。



== Insight Serverのポート

Insight Serverには、ソフトウェアファイアウォールをインストールできます。開く必要がある「穴」は、以下のようになります。

*インバウンドHTTPS 443 *- Insight WebUIをTCP 443で実行している場合は、次のいずれかのユーザを許可するために、その情報を公開する必要があります。

* Web UIのInsightユーザ
* Remote Acquisition UnitがInsight Serverへの接続を要求しています
* このInsightサーバへのコネクタを備えたOCI DWHサーバ。
* Insight REST APIとのプログラムによるやり取り
* 異常検出エンジンは、異常情報をレンダリングするためにInsightのパフォーマンスデータを収集します


Insight Serverのホストレベルのファイアウォール機能の実装を検討している方には、企業ネットワークのすべてのIPブロックへのHTTPSアクセスを許可することをお勧めします。

*インバウンドMySQL（TCP 3306）*。このポートは、コネクタを備えたInsight DWHサーバにのみ公開する必要があります

Insightには多数のデータコレクタがありますが、これらはすべてポーリングベースです。Insight Will原因 its Acquisition Unit（AUS）によって、さまざまなデバイスへのアウトバウンド通信が開始されます。ホストベースのファイアウォールが「ステートフル」で、リターントラフィックがファイアウォールを通過できるようになっている限り、Insight Serverのホストベースのファイアウォールはデータ取得に影響しません。



== Data Warehouseのポート

Insight DWHサーバの場合：

*インバウンドHTTPS 443 *- Insight WebUIをTCP 443で実行している場合は、次のコンシューマを許可するためにこの情報を公開する必要があります。

* DWH管理ポータルのInsight管理ユーザ


*インバウンドHTTPS（TCP 9300）*- Cognosのレポートインターフェイスです。ユーザがCognosのレポートインターフェイスを操作する場合は、このインターフェイスをリモートで公開する必要があります。

DWHを公開する必要がない環境を想像できます。たとえば、レポートの作成者がDWHサーバにRDP接続し、DWHサーバでレポートを作成してスケジュールを設定し、すべてのレポートをSMTP経由で配信するか、リモートファイルシステムに書き込むようにスケジュール設定します。

*インバウンドMySQL（TCP 3306）*。このポートを公開する必要があるのは、DWHデータとMySQLベースの統合がある場合だけです。さまざまなDWHデータマートからデータを抽出して、CMDB、チャージバックシステムなどの他のアプリケーションに取り込みますか
