---
permalink: config-admin/fujitsu-eternus-data-source.html 
sidebar: sidebar 
keywords:  
summary: Fujitsu Eternusデータソースには、ストレージのIPアドレスが必要です。カンマで区切ることはできません。 
---
= Fujitsu Eternusデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fujitsu Eternusデータソースには、ストレージのIPアドレスが必要です。カンマで区切ることはできません。



== 用語集

OnCommand Insight では、Fujitsu ETERNUSデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
ディスク
 a| 
ディスク



 a| 
ストレージ
 a| 
ストレージ



 a| 
シンプール、フレキシブル階層プール、

RAID グループ
 a| 
ストレージプール



 a| 
標準ボリューム、Snap Data Volume（SDV）、

Snap Data Poolボリューム（SDPV）

シンプロビジョニングボリューム（TPV）
 a| 
ボリューム

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* Eternus ストレージの IP アドレス。カンマで区切って指定することはできません
* SSH 管理レベルのユーザ名とパスワード
* ポート 22
* ページスクロールが無効になっていることを確認します。（clientv-show-more-scroll disable）




== 設定

|===


| フィールド | 説明 


 a| 
Eternus ストレージの IP アドレス
 a| 
Eternus ストレージの IP アドレス



 a| 
ユーザ名
 a| 
Eternus ストレージのユーザ名



 a| 
パスワード
 a| 
胸骨に使用するパスワード

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは20分）



 a| 
SSHプロセス待機タイムアウト（秒）
 a| 
SSHプロセスのタイムアウト（デフォルトは600秒）

|===