---
permalink: config-admin/hds-hnas-data-source.html 
sidebar: sidebar 
keywords:  
summary: HDS NAS \（HNAS\）データソースは、HDS NASクラスタの検出をサポートするためのインベントリおよび設定のデータソースです。Insightでは、NFS共有とCIFS共有、ファイルシステム\（Insight内部ボリューム\）、スパン\（Insightストレージプール\）の検出がサポートされています。 
---
= HDS NAS（HNAS）データソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HDS NAS（HNAS）データソースは、HDS NASクラスタの検出をサポートするためのインベントリおよび設定のデータソースです。Insightでは、NFS共有とCIFS共有、ファイルシステム（Insightの内部ボリューム）、スパン（Insightのストレージプール）の検出がサポートされています。

このデータソースはSSHベースであるため、ホストするAcquisition Unitから、HNAS自体またはクラスタが接続されているSystems Management Unit（SMU）のTCP 22へのSSHセッションを開始できる必要があります。



== 用語集

OnCommand Insight では、HNASデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
階層
 a| 
ディスクグループ



 a| 
クラスタ
 a| 
ストレージ



 a| 
ノード
 a| 
ストレージノード



 a| 
スパン（ Span ）
 a| 
ストレージプール



 a| 
File System の略
 a| 
内部ボリューム

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

このデータソースを設定して使用するための要件は次のとおりです。

* デバイスの IP アドレス
* ポート 22 、 SSH プロトコル
* ユーザ名とパスワードの権限レベル： Supervisor
* 注：このデータコレクタはSSHベースなので、ホストするAUは、HNAS自体またはクラスタが接続されているSystems Management Unit（SMU）のTCP 22へのSSHセッションを開始できる必要があります。


[NOTE]
====
このデータコレクタはSSHベースなので、ホストするAUは、HNAS自体またはクラスタが接続されているSystems Management Unit（SMU）のTCP 22へのSSHセッションを開始できる必要があります。

====


== 設定

|===


| フィールド | 説明 


 a| 
HNAS ホスト
 a| 
HNAS 管理ホストの IP アドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
HNAS CLI のユーザ名



 a| 
パスワード
 a| 
HNAS CLI のパスワード

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは30分）



 a| 
SSHバナー待機タイムアウト（秒）
 a| 
SSHバナーのタイムアウト（デフォルトは15秒）



 a| 
SSHコマンドタイムアウト（秒）
 a| 
SSHコマンドのタイムアウト（デフォルトは30秒）

|===