---
permalink: config-admin/hds-landing-page-terminology-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: HDSストレージプールのアセットランディングページに記載されているオブジェクトや参照に適用される用語。 
---
= HITACHI Storage Poolの略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HDSストレージプールのアセットランディングページに記載されているオブジェクトや参照に適用される用語。



== HDSストレージプールの用語

HDS ストレージプールのアセットランディングページにあるオブジェクトや参照に関連する用語を次に示します。これらの用語の多くは、他のデータコレクタにも適用されます。

* タイプ：値は次のいずれかになります。
+
** リザーブ(Reserved)--このプールがデータボリューム以外の目的(ジャーナリング'スナップショットなど)専用の場合
** Thin Provisioning：HDPプールの場合
** RAIDグループ：いくつかの理由により'これらが表示されない可能性があります
+
OCIでは、容量がどのようなコストであっても二重にカウントされることは避けたいと強く考えているHDS では、通常、ディスクから RAID グループを作成し、それらの RAID グループにプールボリュームを作成し、それらのプールボリュームからプール（多くの場合 HDP を作成しますが、特別な目的にすることもあります）を構築する必要があります。基盤となるRAIDグループとプールの両方について報告された場合、物理容量の合計がディスクの合計を大幅に超えてしまいます。

+
OCIのHDS HiCommandデータコレクタは、プールボリュームの容量に応じてRAIDグループのサイズを任意に縮小します。そのため、OCIでRAIDグループがまったく報告されない場合があります。また、作成されたRAIDグループにはOCI Web UIには表示されず、OCI Data Warehouse（DWH）にも表示されるようにフラグが設定されます。これらの決定の目的は、ほとんどのユーザーが気にしないことでUIが乱雑にならないようにすることです。HDSアレイに50MBの空き容量があるRAIDグループがある場合、その空き容量を有意義な結果に使用することはおそらくできません。



* HDS プールは 1 つの特定のノードに関連付けられないため、ノードなし
* Redundancy - プールの RAID レベル。複数の RAID タイプで構成される HDP プールには、複数の値が含まれる可能性があります
* Capacity % - プールでデータ使用に使用されている割合。プールの使用済み GB と合計論理 GB サイズです
* オーバーコミット容量-「このプールの論理容量は、プールの論理容量をこの割合で超過した論理ボリュームの合計により、この割合でオーバーサブスクライブされています」を示す派生値。
* snapshot - このプールでの Snapshot の使用用にリザーブされている容量が表示されます

