---
permalink: config-admin/how-annotations-are-assigned.html 
sidebar: sidebar 
keywords:  
summary: 'アノテーションは、手動またはアノテーションルールを使用して自動で割り当てることができます。また、OnCommand Insight では、アセットの取得時と継承時に一部のアノテーションが自動的に割り当てられます。アセットに割り当てたアノテーションは、アセットページの[User Data]セクションに表示されます。' 
---
= アノテーションの割り当て方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アノテーションは、手動またはアノテーションルールを使用して自動で割り当てることができます。また、OnCommand Insight では、アセットの取得時と継承時に一部のアノテーションが自動的に割り当てられます。アセットに割り当てたアノテーションは、アセットページの[User Data]セクションに表示されます。

アノテーションは次の方法で割り当てられます。

* アセットにアノテーションを手動で割り当てることができます。
+
アノテーションがアセットに直接割り当てられている場合、そのアノテーションはアセットページに通常のテキストとして表示されます。手動で割り当てたアノテーションは、継承またはアノテーションルールで割り当てられたアノテーションよりも常に優先されます。

* アノテーションルールを作成して、同じタイプのアセットにアノテーションを自動的に割り当てることができます。
+
ルールに基づいてアノテーションが割り当てられている場合、Insightのアセットページのアノテーション名の横にルール名が表示されます。

* Insightでは、階層レベルがストレージ階層モデルに自動的に関連付けられるため、アセットを取得したときにリソースにストレージのアノテーションをすばやく割り当てることができます。
+
特定のストレージリソースは、事前定義された階層（階層1と階層2）に自動的に関連付けられます。たとえば、Symmetrixストレージ階層はSymmetrixおよびVMAXファミリーに基づいており、階層1に関連付けられています。デフォルト値は、階層の要件に合わせて変更できます。Insightによって割り当てられたアノテーション（階層など）については、アセットページでアノテーションの名前にカーソルを合わせると「システム定義」と表示されます。

* 一部のリソース（アセットの子）では、事前定義された階層のアノテーションをアセット（親）から取得できます。
+
たとえば、ストレージにアノテーションを割り当てた場合、そのストレージに属するすべてのストレージプール、内部ボリューム、ボリューム、qtree、および共有に階層のアノテーションが適用されます。ストレージの内部ボリュームに別のアノテーションを適用すると、それ以降はすべてのボリューム、qtree、および共有にアノテーションが適用されます。アセットページのアノテーション名の横に「データベース」と表示されます。


