---
permalink: config-admin/hpe-nimble-data-source.html 
sidebar: sidebar 
keywords:  
summary: HPE Nimble Data Collector は、 HPE Nimble ストレージアレイのインベントリとパフォーマンスのデータをサポートしています。 
---
= HPE Nimbleデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HPE Nimble Data Collector は、 HPE Nimble ストレージアレイのインベントリとパフォーマンスのデータをサポートしています。



== 用語集

OnCommand Insight では、HPE Nimbleデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
配列
 a| 
ストレージ



 a| 
ディスク
 a| 
ディスク



 a| 
プール
 a| 
ストレージプール



 a| 
ボリューム
 a| 
ボリューム



 a| 
イニシエータ
 a| 
ストレージホストのエイリアス



 a| 
コントローラ
 a| 
ストレージノード



 a| 
Fibre Channel インターフェイス
 a| 
コントローラ

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* アレイがインストールおよび設定されていて、クライアントから完全修飾ドメイン名（ FQDN ）またはアレイ管理 IP アドレスを使用して到達できる必要があります。
* アレイで NimbleOS 2.3.x 以降が実行されている必要があります。
* アレイに対する有効なユーザ名とパスワードが必要です。
* アレイのポート 5392 が開いている必要があります。




== 設定

|===


| * フィールド * | * 概要 * 


 a| 
アレイ管理 IP アドレス
 a| 
Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）またはアレイ管理 IP アドレスです。



 a| 
ユーザ名
 a| 
Nimble アレイのユーザ名



 a| 
パスワード
 a| 
Nimble アレイのパスワード

|===


== 高度な設定

|===


| * フィールド * | * 概要 * 


 a| 
ポート
 a| 
Nimble REST API が使用するポート。デフォルトは 5392. です。



 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは60分）

|===
注：デフォルトのパフォーマンスのポーリング間隔は 300 秒で、変更することはできません。Nimble でサポートされている唯一の間隔はこれです。
