---
permalink: config-admin/ibm-powervm-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: IBM PowerVM\（SSH\）データソースは、ハードウェア管理コンソール\（HMC\）で管理されるIBM POWERハードウェアインスタンスで実行されている仮想パーティションに関する情報を収集します。このデータソースを設定するには、SSHを使用してHMCにログインするためのユーザ名、およびHMCの設定に対する表示レベルの権限が必要です。 
---
= IBM PowerVMデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM PowerVM（SSH）データソースは、ハードウェア管理コンソール（HMC）で管理されるIBM POWERハードウェアインスタンスで実行されている仮想パーティションに関する情報を収集します。このデータソースを設定するには、SSHを使用してHMCにログインするためのユーザ名、およびHMCの設定に対する表示レベルの権限が必要です。



== 用語集

OnCommand Insight では、IBM PowerVMデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
hdisk
 a| 
仮想ディスク



 a| 
Managed System の略
 a| 
ホスト



 a| 
LPAR 、 VIO サーバ
 a| 
仮想マシン



 a| 
ボリュームグループ
 a| 
データストア



 a| 
物理ボリューム
 a| 
LUN

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* ハードウェア管理コンソール（ HMC ）の IP アドレス
* SSH経由でHMCにアクセスするためのユーザ名とパスワード
* ポート要件は SSH-22 です
* すべての管理システムおよび論理パーティションセキュリティドメインに対する表示権限
+
ユーザには、 HMC の設定に対する表示権限も必要であり、 HMC コンソールセキュリティグループの VPD 情報を収集できる必要があります。ユーザーは、論理パーティションセキュリティグループの Virtual IO Server コマンドへのアクセスも許可されている必要があります。オペレータのロールから開始し、すべてのロールを削除することを推奨します。HMC の読み取り専用ユーザには、 AIX ホストでプロキシされたコマンドを実行する権限はありません。

* IBM のベストプラクティスは、 2 台以上の HMI でデバイスを監視することです。これにより、原因 OnCommand Insight で重複したデバイスが報告される場合があるため、このデータコレクタの詳細設定の [ デバイスを除外する ] リストに冗長デバイスを追加することを強くお勧めします。




== 設定

|===


| * フィールド * | * 概要 * 


 a| 
ハードウェア管理コンソール（HMC）のアドレス
 a| 
PowerVM ハードウェア管理コンソールの IP アドレスまたは完全修飾ドメイン名



 a| 
HMC ユーザ
 a| 
ハードウェア管理コンソールのユーザ名



 a| 
パスワード
 a| 
ハードウェア管理コンソールのパスワード

|===


== 高度な設定

|===


| * フィールド * | * 概要 * 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは20分）



 a| 
SSH ポート
 a| 
PowerVM への SSH に使用するポート



 a| 
SSHプロセス待機タイムアウト（秒）
 a| 
SSHプロセスのタイムアウト（デフォルトは600秒）



 a| 
再試行回数
 a| 
インベントリの再試行回数



 a| 
デバイスを除外します
 a| 
対象から除外するデバイスの ID または表示名をカンマで区切ったリスト

|===