---
permalink: config-admin/ibm-xiv-cli-data-source.html 
sidebar: sidebar 
keywords:  
summary: IBM XIV\（CLI\）データソースのインベントリの収集は、XIVコマンドラインインターフェイスを使用して実行します。XIVのパフォーマンスは、ポート5989でSMI-Sプロバイダを実行するXIVアレイにSMI-Sを呼び出して実現されます。 
---
= IBM XIVデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM XIV（CLI）データソースのインベントリの収集は、XIVコマンドラインインターフェイスを使用して実行します。XIVのパフォーマンスは、ポート5989でSMI-Sプロバイダを実行するXIVアレイにSMI-Sを呼び出して実現されます。



== 用語集

OnCommand Insight では、IBM XIVデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
ディスク
 a| 
ディスク



 a| 
ストレージシステム
 a| 
ストレージ



 a| 
ストレージプール
 a| 
ストレージプール



 a| 
ボリューム
 a| 
ボリューム

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* ポート要件： TCP ポート 7778
* XIV管理インターフェイスのIPアドレス
* 読み取り専用のユーザ名とパスワード
* XIV CLIがInsight ServerまたはRAUにインストールされている必要があります
* アクセスの検証：Insight Serverから、ユーザ名とパスワードを使用してXIVのユーザインターフェイスにログインします。




== 設定

|===


| * フィールド * | * 概要 * 


 a| 
IP アドレス
 a| 
XIVストレージのIPアドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
XIV ストレージのユーザ名



 a| 
パスワード
 a| 
XIV ストレージのパスワード



 a| 
XIV CLIディレクトリの完全パス
 a| 
XIV CLIディレクトリの完全パス

|===


== 高度な設定

|===


| * フィールド * | * 概要 * 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリのポーリング間隔（デフォルトは 40 分）



 a| 
CLIプロセス待機タイムアウト（ミリ秒）
 a| 
CLIプロセスのタイムアウト（デフォルトは7200000ミリ秒）



 a| 
SMI-SホストIP
 a| 
SMI-SプロバイダホストのIPアドレス



 a| 
SMI-Sポート
 a| 
SMI-Sプロバイダホストが使用するポート



 a| 
SMI-S プロトコル
 a| 
SMI-S プロバイダへの接続に使用するプロトコル



 a| 
SMI-Sネームスペース
 a| 
SMI-Sネームスペース



 a| 
ユーザ名
 a| 
SMI-S プロバイダホストのユーザ名



 a| 
パスワード
 a| 
SMI-S プロバイダホストのパスワード



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）



 a| 
SMI-S接続の再試行回数
 a| 
SMI-S接続の再試行回数

|===