---
permalink: config-admin/ibm-ds-cli-data-source.html 
sidebar: sidebar 
keywords:  
summary: IBM DS\（CLI\）データソースは、DS6xxxおよびDS8xxxデバイスのみをサポートします。DS3xxx、DS4xxx、およびDS5xxxのデバイスは、NetApp E-Seriesデータソースでサポートされます。サポートされるモデルとファームウェアバージョンについては、Insightデータソースサポートマトリックスを参照してください。 
---
= IBM DSデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM DS（CLI）データソースでサポートされるのは、DS6xxxデバイスとDS8xxxデバイスのみです。DS3xxx、DS4xxx、およびDS5xxxのデバイスは、NetApp E-Seriesデータソースでサポートされます。サポートされるモデルとファームウェアバージョンについては、Insightデータソースサポートマトリックスを参照してください。



== 用語集

OnCommand Insight では、IBM DSデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
ディスクドライブモジュール
 a| 
ディスク



 a| 
ストレージイメージ
 a| 
ストレージ



 a| 
エクステントプール
 a| 
ストレージプール



 a| 
固定ブロックボリューム
 a| 
ボリューム

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* 各 DS アレイの IP アドレス
* ストレージの表示名はオプションであり、外観上のみです
* 各 DS アレイの読み取り専用のユーザ名とパスワード
* サードパーティ製ソフトウェアをInsightサーバにインストール：IBM dscli
* アクセスの検証：を実行します `dscli` ユーザ名とパスワードを使用したコマンド
* ポートの要件： 80 、 443 、および 1750




== 設定

|===


| フィールド | 説明 


 a| 
DSストレージ
 a| 
DS Storage HostのIPアドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
DS CLIに使用する名前



 a| 
パスワード
 a| 
DS CLIのパスワード



 a| 
実行可能ファイルのdscli.exeパス
 a| 
への完全パス ``dscli.exe``ユーティリティ。

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリのポーリング間隔（デフォルトは 40 分）



 a| 
ストレージ表示名
 a| 
IBM DS ストレージアレイの名前



 a| 
インベントリ除外デバイス
 a| 
インベントリ収集の対象から除外するデバイスのシリアル番号をカンマで区切ったリスト



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）



 a| 
パフォーマンスフィルタタイプ
 a| 
Include ：リストのデバイスからのみデータを収集します。Exclude ：リストのデバイスからデータを収集しません



 a| 
パフォーマンスフィルタのデバイスリスト
 a| 
パフォーマンス収集の対象に含めるか除外するデバイスの ID をカンマで区切ったリスト

|===