---
permalink: config-admin/ibm-svc-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: IBM SVCデータソースは、SSHを使用してインベントリとパフォーマンスのデータを収集し、SVCオペレーティングシステムを実行するさまざまなデバイスをサポートします。サポートされるデバイスには、 SVC 、 v7000 、 v5000 、 v3700 などのモデルが含まれます。サポートされるモデルとファームウェアバージョンについては、Insightデータソースサポートマトリックスを参照してください。 
---
= IBM SVCデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM SVCデータソースは、SSHを使用してインベントリとパフォーマンスのデータを収集し、SVCオペレーティングシステムを実行するさまざまなデバイスをサポートします。サポートされるデバイスには、 SVC 、 v7000 、 v5000 、 v3700 などのモデルが含まれます。サポートされるモデルとファームウェアバージョンについては、Insightデータソースサポートマトリックスを参照してください。



== 用語集

OnCommand Insight では、IBM SVCデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
ドライブ
 a| 
ディスク



 a| 
クラスタ
 a| 
ストレージ



 a| 
ノード
 a| 
ストレージノード



 a| 
mdisk グループ
 a| 
ストレージプール



 a| 
仮想ディスク
 a| 
ボリューム



 a| 
mdisk
 a| 
バックエンド LUN

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== インベントリの要件

* 各 SVC クラスタの IP アドレス
* ポート 22 を使用できます
* 公開鍵と秘密鍵のペア。Insightで生成するか、SVCですでに使用しているキーペアを再利用します
+
既存のキーペアを再利用する場合は、それらのキーペアをPutty形式からOpenSSH形式に変換する必要があります。

* 公開鍵をSVCクラスタにインストールします
* 秘密鍵をデータソースで識別する必要があります
* アクセスの検証：開く `ssh` 秘密鍵を使用したSVCクラスタへのセッション


[NOTE]
====
他社製ソフトウェアをインストールする必要はありません。

====


== パフォーマンス要件

* SVC コンソールはすべての SVC クラスタに必須であり、 SVC 検出基本パッケージに必要です。
* クラスタノードから構成ノードにパフォーマンスデータファイルをコピーする場合にのみ必要な管理アクセスレベル。
+
[NOTE]
====
このアクセスレベルはSVC基本検出パッケージには必要ないため、SVC基本ユーザが正常に機能しない場合があります。

====
* ポート22が必要です
* このユーザのSSHキーと公開鍵を生成し、Acquisition Unitからアクセスできるように秘密鍵を格納する必要があります。SVC基本ユーザに適切な権限があれば、同じユーザとキーが機能します。インベントリデータとパフォーマンスデータに同じSSHキーを使用できます。
* データ収集を有効にするには、SSHを使用してSVCクラスタに接続し、次のコマンドを実行します。 `svctask startstats -interval 1`
+
[NOTE]
====
または、SVC管理ユーザインターフェイスを使用してデータ収集を有効にします。

====




== 親シリアル番号の説明

従来、Insightでは、ストレージアレイのシリアル番号や個 々 のストレージノードのシリアル番号をレポートすることができました。ただし、一部のストレージアレイアーキテクチャはこれに適切に対応していません。SVCクラスタは1~4台のアプライアンスで構成でき、各アプライアンスには2つのノードがあります。アプライアンス自体のシリアル番号がある場合、そのシリアル番号はクラスタのシリアル番号でもノードのシリアル番号でもありません。

IBM SVCアレイのストレージノードオブジェクトの「Parent Serial Number」属性は、個 々 のノードが大規模なクラスタの一部にすぎない中間アプライアンス/エンクロージャ内に配置されている場合に適切に設定されます。



== 設定

|===


| * フィールド * | * 概要 * 


 a| 
クラスタ/秒IP
 a| 
SVCストレージの完全修飾ドメイン名のIPアドレス



 a| 
クレデンシャルタイプを指定するには、「 Password 」または「 OpenSSH Key File 」を選択してください
 a| 
SSH経由でデバイスに接続するために使用するクレデンシャルタイプ



 a| 
Inventory User Name の略
 a| 
SVC CLI のユーザ名



 a| 
Inventory Password （インベントリパスワード）
 a| 
SVC CLI のパスワード



 a| 
Inventory Private Key への完全パス
 a| 
インベントリの秘密鍵ファイルの完全パス



 a| 
Performance User Nameの略
 a| 
パフォーマンス収集用のSVC CLIのユーザ名



 a| 
パフォーマンスパスワード
 a| 
パフォーマンス収集に使用するSVC CLIのパスワード



 a| 
パフォーマンス秘密鍵への完全パス
 a| 
パフォーマンスの秘密鍵ファイルの完全パス

|===


== 高度な設定

|===


| * フィールド * | * 概要 * 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリのポーリング間隔（デフォルトは 40 分）



 a| 
デバイスを除外します
 a| 
インベントリ収集の対象から除外するデバイスのIDをカンマで区切ったリスト



 a| 
SSHプロセス待機タイムアウト（秒）
 a| 
SSHプロセスのタイムアウト（デフォルトは200秒）



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）



 a| 
Performance Exclude Devicesを参照してください
 a| 
パフォーマンス収集の対象から除外するデバイスのIDをカンマで区切ったリスト



 a| 
パフォーマンスSSHプロセス待機タイムアウト（秒）
 a| 
SSHプロセスのタイムアウト（デフォルトは200秒）



 a| 
ダンプされた統計情報ファイルをクリーンアップする場合
 a| 
ダンプされた統計ファイルをクリーンアップする場合に選択します

|===