---
permalink: config-admin/importing-and-exporting-user-data.html 
sidebar: sidebar 
keywords:  
summary: インポートとエクスポートの機能では、アノテーション、アノテーションルール、クエリ、パフォーマンスポリシー、カスタムダッシュボードを1つのファイルにエクスポートできます。このファイルは、別のOnCommand Insight サーバにインポートできます。 
---
= ユーザーデータのインポートとエクスポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インポートとエクスポートの機能では、アノテーション、アノテーションルール、クエリ、パフォーマンスポリシー、カスタムダッシュボードを1つのファイルにエクスポートできます。このファイルは、別のOnCommand Insight サーバにインポートできます。

エクスポートおよびインポート機能は、同じバージョンのOnCommand Insight を実行しているサーバ間でのみサポートされます。

ユーザーデータをエクスポートまたはインポートするには、* Admin *をクリックして* Setup *を選択し、* Import/Export user data *タブを選択します。

インポート処理では、インポートするオブジェクトとオブジェクトタイプに応じて、データの追加、マージ、または置換が行われます。

* アノテーションタイプ
+
** 同じ名前のアノテーションがターゲットシステムにない場合、アノテーションが追加されます。
** 同じ名前のアノテーションがターゲットシステムにある場合、アノテーションタイプがリストであれば、アノテーションがマージされます。
** 同じ名前のアノテーションがターゲットシステムにある場合、アノテーションタイプがリスト以外であれば、アノテーションが置き換えられます。


+
[NOTE]
====
名前が同じでタイプが異なるアノテーションがターゲットシステムにあると、インポートは失敗します。失敗したアノテーションにオブジェクトが依存している場合、誤った情報や不要な情報が表示されることがあります。インポート処理の完了後、すべてのアノテーションの依存関係を確認してください。

====
* アノテーションルール
+
** 同じ名前のアノテーションルールがターゲットシステムにない場合は、アノテーションルールが追加されます。
** 同じ名前のアノテーションルールがターゲットシステムにある場合、アノテーションルールが置き換えられます。


+
[NOTE]
====
アノテーションルールは、クエリとアノテーションの両方に依存します。インポート処理の完了後に、すべてのアノテーションルールに間違いがないかどうかを確認する必要があります。

====
* ポリシー
+
** 同じ名前のポリシーがターゲットシステムに存在しない場合は、ポリシーが追加されます。
** 同じ名前のポリシーがターゲットシステムに存在する場合は、ポリシーが置き換えられます。


+
[NOTE]
====
インポート処理の完了後にポリシーの順序が乱れている可能性があります。インポート後にポリシーの順序を確認する必要があります。アノテーションが正しくないと、アノテーションに依存するポリシーが失敗することがあります。インポート後に、すべてのアノテーションの依存関係を確認する必要があります。

[+]

====
* クエリ
+
** 同じ名前のクエリがターゲットシステムに存在しない場合は、クエリを追加します。
** 同じ名前のクエリがターゲットシステムに存在する場合、クエリのリソースタイプが異なる場合でもクエリが置き換えられます。


+
[NOTE]
====
クエリのリソースタイプが異なる場合、インポート後にそのクエリを使用するダッシュボードウィジェットに不要な結果や誤った結果が表示されることがあります。インポートの完了後、クエリベースのすべてのウィジェットが正しく機能しているかどうかを確認する必要があります。アノテーションが正しくないと、アノテーションに依存するクエリが失敗することがあります。インポート後に、すべてのアノテーションの依存関係を確認する必要があります。

[+]

====
* ダッシュボード
+
** 同じ名前のダッシュボードがターゲットシステムに存在しない場合は、ダッシュボードが追加されます。
** 同じ名前のダッシュボードがターゲットシステムにある場合、クエリのリソースタイプが異なっていても、ダッシュボードが置き換えられます。


+
[NOTE]
====
インポートの完了後、ダッシュボードでクエリベースのすべてのウィジェットが正しく機能しているかどうかを確認する必要があります。ソースサーバーに同じ名前のダッシュボードが複数ある場合は、すべてエクスポートされます。ただし、ターゲットサーバにインポートされるのは最初のサーバだけです。インポート時のエラーを回避するには、エクスポートする前にダッシュボードの名前が一意であることを確認する必要があります。

[+]

====

