---
permalink: config-admin/importing-data-sources-from-a-spreadsheet.html 
sidebar: sidebar 
keywords:  
summary: スプレッドシートからOnCommand Insight に複数のデータソースをインポートできます。これは、検出デバイスをスプレッドシートですでに管理している場合に役立ちます。このプロセスでは新しいデータソースが追加されますが、既存のデータソースの更新には使用できません。 
---
= スプレッドシートからデータソースをインポートする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スプレッドシートからOnCommand Insight に複数のデータソースをインポートできます。これは、検出デバイスをスプレッドシートですでに管理している場合に役立ちます。このプロセスでは新しいデータソースが追加されますが、既存のデータソースの更新には使用できません。



== このタスクについて

OnCommand Insight には、データソースの作成に役立つスプレッドシートが用意されています。このスプレッドシートには次の属性があります。

* このスプレッドシートは、Microsoft Excel 2003以降で使用できます。
* 各タブには、Brocade SSH/CLIなど、1つのデータソースタイプが表示されます。
* 各行は、作成される新しいデータソースのインスタンスを表します。


スプレッドシートには、OnCommand Insight で新しいデータソースを作成するマクロが含まれています。



== 手順

. でスプレッドシートを探します `<install_directory>/SANscreen/acq/bin/acqcli/SiteSurvey_DataSourceImporter_w_Macro.zip`。
. スプレッドシートで、色の付いたセルにデータソース情報を入力します。
. 空の行を削除します。
. スプレッドシートからを実行します `CreateDataSources` マクロを使用してデータソースを作成します。
. クレデンシャルの入力を求められたら、OnCommand Insight サーバの管理ユーザ名とパスワードを入力します。
+
収集結果が収集ログに記録されます。

. マクロを実行しているマシンにOnCommand Insight がインストールされているかどうかを確認するプロンプトが表示されます。
+
次のいずれかを選択します。

+
** いいえ：OnCommand Insight マシンで実行する必要があるバッチファイルを作成する場合は、[いいえ]を選択します。インストールディレクトリからこのバッチファイルを実行します。
** Yes：OnCommand Insight がすでにインストールされていて、データソース情報を生成するための追加の手順が不要な場合は、[Yes]を選択します。


. データソースが追加されたかどうかを確認するには、ブラウザでInsightを開きます。
. Insightのツールバーで、*[Admin]*をクリックします。
. [Data sources]リストで、インポートしたデータソースを確認します。

