---
permalink: config-admin/locating-required-information-for-new-disk-model.html 
sidebar: sidebar 
keywords:  
summary: ディスクモデルの情報を確認するには、ベンダーとモデル番号を特定し、インターネットで検索します。 
---
= 新しいディスクモデルの必要な情報の参照
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ディスクモデルの情報を確認するには、ベンダーとモデル番号を特定し、インターネットで検索します。



== このタスクについて

ディスクモデルの情報は、インターネットで検索するだけで簡単に見つけることができます。検索する前に、ベンダー名とディスクモデル番号をメモしておいてください。



== 手順

. インターネットでベンダー、モデル、ドキュメントタイプ「`pdf'」の高度な検索を使用して、ベンダーのデータシートやドライブのインストールガイドを検索することをお勧めします。通常、これらのデータシートは、ベンダーディスク情報の最良のソースです。
. ベンダーの仕様では、完全なモデル番号に基づいて、必要なすべての情報が提供されるとは限りません。多くの場合、ベンダーのサイトでモデル番号の文字列のさまざまな部分を検索して、すべての情報を見つけると便利です。
. OnCommand Insight で新しいディスクモデルを定義するには、ディスクのベンダー名、完全なモデル番号、ディスクのサイズと速度、およびインターフェイスタイプを確認します。次の表に記載されている情報を参考にしてください。
+
|===


| このフィールド： | これは次のとおりです。 | 入力内容： 


 a| 
モデル番号（別名キー）
 a| 
必須
 a| 



 a| 
ベンダー
 a| 
必須
 a| 



 a| 
ディスク速度（rpm）
 a| 
必須
 a| 



 a| 
サイズ（GB）
 a| 
必須
 a| 



 a| 
インターフェイスタイプ（1つ選択）
 a| 
必須
 a| 
ATA、SATA、SATA2、SATA3、FC、 SAS、FATA、SSD、その他



 a| 
シーク時間（ミリ秒）
 a| 
任意。
 a| 



 a| 
最大転送速度（MB/秒）
 a| 
任意。
 a| 



 a| 
インターフェイスの転送速度（MB/秒）
 a| 
任意。
 a| 



 a| 
ベンダー/モデル情報へのリンク
 a| 
オプションですが、推奨されます
 a| 

|===
. にその情報を入力します `new_disk_models.txt` ファイル。を参照してください link:content-of-the-new-disk-models-txt-file.md#["new_disk_models.txtファイルの内容"] 形式、順序、および例については、を参照してください。

