---
permalink: config-admin/managing-security-on-an-rau.html 
sidebar: sidebar 
keywords: rekey 
summary: securityadminツールを使用すると、RAUのセキュリティオプションを管理できます。場合によっては、ヴォールト設定のバックアップやリストア、暗号化キーの変更、Acquisition Unitのパスワードの更新が必要になることがあります。 
---
= RAUでのセキュリティの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 `securityadmin` ツールを使用すると、RAUのセキュリティオプションを管理できます。場合によっては、ヴォールト設定のバックアップやリストア、暗号化キーの変更、Acquisition Unitのパスワードの更新が必要になることがあります。



== このタスクについて

を使用します `securityadmin` セキュリティ管理ツール：

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`


LAU（RAU）のセキュリティ設定を更新する1つのシナリオは、サーバで「acquisition」ユーザのパスワードが変更されたときに「acquisition」ユーザのパスワードを更新することです。すべてのRAUおよびLAUでは、サーバとの通信にサーバ「acquisition」ユーザのパスワードと同じパスワードを使用します。

[NOTE]
====

====
「acquisition」ユーザが存在するのはInsight Serverだけです。RAUまたはLAUは、サーバに接続するときにそのユーザとしてログインします。

RAUでセキュリティオプションを管理するには、次の手順を実行します。



== 手順

. RAUを実行しているサーバへのリモートログインを実行します
. 対話型モードでセキュリティ管理ツールを起動します。 `Windows - C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i``Linux - /bin/oci-securityadmin.sh -i`
+
ログインクレデンシャルが要求されます。

. 「Admin」クレデンシャルを持つアカウントのユーザ名とパスワードを入力します。
+
RAUのメニューが表示されます。

+
** * バックアップ *
+
すべてのパスワードとキーが格納されているバックアップのzipファイルを作成し、そのファイルをユーザが指定した場所、または次のデフォルトの場所に置きます。

+
*** Windows - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** * 復元 *
+
作成したバックアップのzipファイルをリストアします。リストアすると、すべてのパスワードとキーがバックアップ作成時の既存の値に戻ります。

+
[NOTE]
====
リストアを使用すると、複数のサーバのパスワードとキーを同期できます。例：- 1つのサーバで暗号化キーを変更-ヴォールトのバックアップを作成-ヴォールトバックアップを2つ目のサーバにリストアします

[+]

====
** *暗号化キーの変更*
+
デバイスパスワードの暗号化または復号化に使用するRAU暗号化キーを変更します。

+
[NOTE]
====
暗号化キーを変更する場合は、アップグレードまたはインストール後にリストアできるように、新しいセキュリティ設定をバックアップする必要があります。

====
** *パスワードの更新*
+
「acquisition」ユーザアカウントのパスワードを変更します。

+
[NOTE]
====
一部のアカウントは、パスワードを変更したときに同期する必要があります。たとえば、サーバで「acquisition」ユーザのパスワードを変更した場合は、LAU、RAU、DWHでも「acquisition」ユーザのパスワードを同じパスワードに変更する必要があります。また、パスワードを変更する場合は、アップグレードまたはインストール後に復元できるように、新しいセキュリティ設定をバックアップする必要があります。

====
** *デフォルトにリセット*
+
暗号化キーとパスワードをデフォルト値にリセットします。デフォルト値はインストール時に指定された値です。

** * 終了 *
+
を終了します `securityadmin` ツール。




