---
permalink: config-admin/managing-security-on-the-local-acquisition-unit.html 
sidebar: sidebar 
keywords:  
summary: securityadminツールを使用すると、ローカル取得ユーザ\（LAU \）のセキュリティオプションを管理できます。セキュリティの管理には、キーとパスワードの管理、作成したセキュリティ設定の保存とリストア、またはデフォルト設定への設定のリストアが含まれます。 
---
= Local Acquisition Unit上のセキュリティの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 `securityadmin` ツールを使用すると、Local Acquisition User（LAU；ローカル収集ユーザ）のセキュリティオプションを管理できます。セキュリティの管理には、キーとパスワードの管理、作成したセキュリティ設定の保存とリストア、またはデフォルト設定への設定のリストアが含まれます。



== 作業を開始する前に

が必要です `admin` セキュリティ設定タスクを実行するための権限。



== このタスクについて

を使用します `securityadmin` セキュリティ管理ツール：

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`




== 手順

. Insight Serverへのリモートログインを実行します。
. 対話型モードでセキュリティ管理ツールを起動します。
+
** Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i`
** Linux - `/bin/oci-securityadmin.sh -i`
+
ログインクレデンシャルが要求されます。



. 「Admin」クレデンシャルを持つアカウントのユーザ名とパスワードを入力します。
. Local Acquisition Unit *を選択して、Local Acquisition Unitのセキュリティ設定を再設定します。
+
次のオプションが表示されます。

+
** * バックアップ *
+
すべてのパスワードとキーが格納されているバックアップのzipファイルを作成し、そのファイルをユーザが指定した場所、または次のデフォルトの場所に置きます。

+
*** Windows - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** * 復元 *
+
作成したバックアップのzipファイルをリストアします。リストアすると、すべてのパスワードとキーがバックアップ作成時の既存の値に戻ります。

+
[NOTE]
====
リストアを使用すると、複数のサーバのパスワードとキーを同期できます。例：- LAUで暗号化キーを変更-ヴォールトのバックアップを作成-各RAUにヴォールトバックアップをリストアします

====
** *暗号化キーの変更*
+
デバイスのパスワードの暗号化または復号化に使用するAU暗号化キーを変更します。

+
[NOTE]
====
暗号化キーを変更する場合は、アップグレードまたはインストール後にリストアできるように、新しいセキュリティ設定をバックアップする必要があります。

====
** *パスワードの更新*
+
「acquisition」ユーザアカウントのパスワードを変更します。

+
[NOTE]
====
一部のアカウントは、パスワードを変更したときに同期する必要があります。たとえば、サーバで「acquisition」ユーザのパスワードを変更した場合は、LAU、RAU、DWHでも「acquisition」ユーザのパスワードを同じパスワードに変更する必要があります。また、パスワードを変更する場合は、アップグレードまたはインストール後に復元できるように、新しいセキュリティ設定をバックアップする必要があります。

====
** *デフォルトにリセット*
+
acquisitionユーザのパスワードとacquisitionユーザの暗号化キーをデフォルト値にリセットします。デフォルト値はインストール時に指定したパスワードと暗号化キーです。

** * 終了 *
+
を終了します `securityadmin` ツール。



. 設定するオプションを選択し、プロンプトの指示に従います。

