---
permalink: config-admin/managing-security-on-the-insight-server.html 
sidebar: sidebar 
keywords:  
summary: securityadminツールを使用すると、Insight Serverのセキュリティオプションを管理できます。セキュリティの管理には、パスワードの変更、新しいキーの生成、作成したセキュリティ設定の保存とリストア、デフォルト設定への設定のリストアが含まれます。 
---
= Insight Serverでセキュリティを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 `securityadmin` ツールを使用すると、Insight Serverでセキュリティオプションを管理できます。セキュリティの管理には、パスワードの変更、新しいキーの生成、作成したセキュリティ設定の保存とリストア、デフォルト設定への設定のリストアが含まれます。



== このタスクについて

を使用します `securityadmin` セキュリティ管理ツール：

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`




== 手順

. Insight Serverへのリモートログインを実行します。
. 対話型モードでセキュリティ管理ツールを起動します。 `securityadmin -i`
+
ログインクレデンシャルが要求されます。

. 「Admin」クレデンシャルを持つアカウントのユーザ名とパスワードを入力します。
. 「 * サーバー * 」を選択します。
+
次のサーバ設定オプションを使用できます。

+
** * バックアップ *
+
すべてのパスワードとキーが格納されているバックアップのzipファイルを作成し、そのファイルをユーザが指定した場所、または次のデフォルトの場所に置きます。

+
*** Windows - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** * 復元 *
+
作成したバックアップのzipファイルをリストアします。リストアすると、すべてのパスワードとキーがバックアップ作成時の既存の値に戻ります。

+
[NOTE]
====
リストアを使用すると、複数のサーバのパスワードとキーを同期できます。例：- 1台のサーバでサーバ暗号化キーを変更-ヴォールトのバックアップを作成-ヴォールトバックアップを2台目のサーバにリストアします

[+]

====
** *暗号化キーの変更*
+
プロキシユーザパスワード、SMTPユーザパスワード、LDAPユーザパスワードなどの暗号化または復号化に使用するサーバ暗号化キーを変更します。

+
[NOTE]
====
暗号化キーを変更する場合は、アップグレードまたはインストール後にリストアできるように、新しいセキュリティ設定をバックアップする必要があります。

====
** *パスワードの更新*
+
Insightで使用される内部アカウントのパスワードを変更します。次のオプションが表示されます。

+
*** _internal
*** 取得
*** cognos_adminをクリックします
*** dwh_internalの略
*** ホスト
*** 在庫
*** ルート




+
[NOTE]
====
一部のアカウントは、パスワードを変更したときに同期する必要があります。たとえば、サーバで「acquisition」ユーザのパスワードを変更した場合は、LAU、RAU、DWHでも「acquisition」ユーザのパスワードを同じパスワードに変更する必要があります。また、パスワードを変更する場合は、アップグレードまたはインストール後に復元できるように、新しいセキュリティ設定をバックアップする必要があります。

====
+
** *デフォルトにリセット*
+
キーとパスワードをデフォルト値にリセットします。デフォルト値はインストール時に指定された値です。

** * 終了 *
+
を終了します `securityadmin` ツール。



. 変更するオプションを選択し、プロンプトの指示に従います。

