---
permalink: config-admin/managing-insight.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight は環境を監視し、危機が報告される前に潜在的な問題を調査できるようにします。[Assets Dashboard]には、概要を示す円グラフ、IOPSのヒートマップ、および利用率が高い上位10個のストレージプールを示す対話型のグラフが表示されます。' 
---
= Insightの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight は環境を監視し、危機が報告される前に潜在的な問題を調査できるようにします。[Assets Dashboard]には、概要を示す円グラフ、IOPSのヒートマップ、および利用率が高い上位10個のストレージプールを示す対話型のグラフが表示されます。



== 手順

. Insight ** Assets Dashboard **を開き、円グラフの上にカーソルを移動して、次の3つのグラフでアセットの分布を確認します。
+
** [Capacity by Vendor]には、各ベンダーのストレージの合計物理容量が表示されます。
** [Capacity by Tier]には、各ストレージ階層の使用可能な合計容量が表示されます。
** [Switch Ports]円グラフには、ポートのメーカーと使用済みポートの割合が表示されます。


. [Facts About Your Environment]*を表示して、環境の使用済み容量、容量の効率、消費されているFCリソース、および仮想インフラの統計に関する情報を確認できます。
. [Top 10 Utilized Pools]*グラフのストレージプールのバーにカーソルを合わせ、ストレージプールの使用済み容量と未使用容量を確認します。
. [Storage IOP]*ヒートマップで大きな文字で表示されているアセット（問題のあるアセット）の名前をクリックすると、そのアセットの現在の状態をまとめたページが表示されます。
. [Assets Dashboard]*の右下隅にある*[Virtual Machine IOPS]*ヒートマップで、大きなテキストで表示されているアセット（問題のあるアセット）の名前をクリックすると、アセットの現在の状態をまとめたページが表示されます。
. Insightのツールバーで、*[Admin]*をクリックします。
. 赤い丸が表示されている領域に注意してください。
+
OnCommand InsightWeb UIでは、潜在的な問題が赤い丸で示されます。

. [データソース]*をクリックして、監視しているすべてのデータソースのリストを確認します。
+
[ステータス]*列に赤い丸で囲まれたメッセージが表示され、[影響]*が[高]または[中]になっているデータソースを確認します。これらはテーブルの上にあります。これらのデータソースの問題は、ネットワークの大部分に影響を及ぼします。この問題に対処する必要があります。

. [Acquisition Units]*をクリックして、Insightを実行している各IPアドレスのステータスを確認し、必要に応じてAcquisition Unitを再起動します
. Insightサーバのインスタンス監視の概要を表示するには、*[健全性]*をクリックします。

