---
permalink: config-admin/managing-security-on-the-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: securityadminツールを使用すると、Data Warehouseサーバのセキュリティオプションを管理できます。セキュリティの管理には、DWHサーバで内部ユーザの内部パスワードを更新したり、セキュリティ設定のバックアップを作成したり、設定をデフォルトの設定にリストアしたりする作業があります。 
---
= Data Warehouseでセキュリティを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 `securityadmin` ツールを使用すると、Data Warehouseサーバのセキュリティオプションを管理できます。セキュリティの管理には、DWHサーバで内部ユーザの内部パスワードを更新したり、セキュリティ設定のバックアップを作成したり、設定をデフォルトの設定にリストアしたりする作業があります。



== このタスクについて

を使用します `securityadmin` セキュリティ管理ツール：

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`




== 手順

. Data Warehouseサーバへのリモートログインを実行します。
. 対話型モードでセキュリティ管理ツールを起動します。
+
** Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i`
** Linux - `/bin/oci-securityadmin.sh -i`
+
ログインクレデンシャルが要求されます。



. 「Admin」クレデンシャルを持つアカウントのユーザ名とパスワードを入力します。
+
Data Warehouseのセキュリティ管理メニューが表示されます。

+
** * バックアップ *
+
すべてのパスワードとキーが格納されたバックアップのzipファイルを作成し、ユーザが指定した場所、またはデフォルトの場所にファイルを配置します。

+
*** Windows - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** * 復元 *
+
作成したバックアップのzipファイルをリストアします。リストアすると、すべてのパスワードとキーがバックアップ作成時の既存の値に戻ります。

+
[NOTE]
====
リストアを使用すると、複数のサーバのパスワードとキーを同期できます。例：- 1つのサーバで暗号化キーを変更-ヴォールトのバックアップを作成-ヴォールトバックアップを2つ目のサーバにリストアします

[+]

====
** *暗号化キーの変更*
+
コネクタのパスワードやSMPTのパスワードなど、パスワードの暗号化や復号化に使用するDWH暗号化キーを変更します。

** *パスワードの更新*
+
特定のユーザアカウントのパスワードを変更します。

+
*** _internal
*** 取得
*** cognos_adminをクリックします
*** DWH
*** dwh_internalの略
*** 誰だ
*** ホスト
*** 在庫
*** ルート




+
[NOTE]
====
dwhuser、hosts、inventory、またはrootのパスワードを変更する場合は、SHA-256パスワードハッシュを使用できます。このオプションでは、アカウントにアクセスするすべてのクライアントがSSL接続を使用する必要があります。

====
+
** *デフォルトにリセット*
+
暗号化キーとパスワードをデフォルト値にリセットします。デフォルト値はインストール時に指定された値です。

** * 終了 *
+
を終了します `securityadmin` ツール。




