---
permalink: config-admin/metric-definitions.html 
sidebar: sidebar 
keywords:  
summary: アセットページのエキスパートビューセクションには、アセットに対して選択した期間に関する複数の指標が表示されます。各指標は独自のパフォーマンスチャートに表示されます。確認が必要なデータに応じて、チャートに表示する指標や関連するアセットを追加したり削除したりできます。 
---
= エキスパートビューの指標の定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アセットページのエキスパートビューセクションには、アセットに対して選択した期間に関する複数の指標が表示されます。各指標は独自のパフォーマンスチャートに表示されます。確認が必要なデータに応じて、チャートに表示する指標や関連するアセットを追加したり削除したりできます。

|===


| メートル法 | 説明 


 a| 
BB クレジットのゼロ受信、転送
 a| 
サンプリング期間中に受信 / 送信のバッファ間クレジット数がゼロになった回数。この指標は、接続されたポートで提供できるクレジットを使い果たしたために転送が中止された回数を表します。



 a| 
BB クレジットのゼロ期間の転送
 a| 
サンプリング期間中に送信 BB クレジットがゼロになっていた時間（ミリ秒）。



 a| 
キャッシュヒット率（合計、読み取り、書き込み）
 a| 
キャッシュにヒットする要求の割合。ボリュームへのアクセス数に対するヒット数の割合が高いほど、パフォーマンスが高くなります。この列は、キャッシュヒット情報を収集しないストレージアレイについては空になります。



 a| 
キャッシュ使用率（合計）
 a| 
キャッシュにヒットするキャッシュ要求の合計割合



 a| 
クラス 3 は破棄されます
 a| 
ファイバチャネルのクラス 3 データ転送が破棄された回数。



 a| 
CPU 利用率（合計）
 a| 
使用可能な合計（すべての仮想 CPU ）に対する使用中のアクティブな CPU リソースの割合。



 a| 
CRC エラーです
 a| 
サンプリング期間中にポートで無効な Cyclic Redundancy Check （ CRC ；巡回冗長検査）が検出されたフレーム数



 a| 
フレームレート
 a| 
転送フレームレート（ 1 秒あたりのフレーム数）。



 a| 
フレームサイズ平均（ Rx 、 Tx ）
 a| 
フレームサイズに対するトラフィックの比率。この指標から、ファブリック内にフレームのオーバーヘッドがないかどうかを特定できます。



 a| 
フレームサイズが長すぎます
 a| 
ファイバチャネルの長すぎるデータ転送フレームの数。



 a| 
フレームサイズが短すぎます
 a| 
ファイバチャネルの短すぎるデータ転送フレームの数。



 a| 
I/O 密度（合計、読み取り、書き込み）
 a| 
ボリューム、内部ボリューム、またはストレージ要素の使用済み容量（データソースの最新のインベントリポーリングから取得）で IOPS を割った値。1 秒間の TB あたりの I/O 処理数で測定されます。



 a| 
IOPS （合計、読み取り、書き込み）
 a| 
I/O チャネルまたはそのチャネルの一部を通過する読み取り / 書き込み I/O サービス要求の単位時間あたりの数（ 1 秒あたりの I/O 数で測定）



 a| 
IP スループット（合計、読み取り、書き込み）
 a| 
合計： IP データの転送および受信速度の合計。 1 秒あたりのメガバイト数で示されます。Read：IP Throughput（Receive）：IPデータの平均受信速度（1秒あたりのメガバイト数）。

Write：IP Throughput（Transmit）：IPデータの平均転送速度（1秒あたりのメガバイト数）。



 a| 
レイテンシ（合計、読み取り、書き込み）
 a| 
Latency （ R&W ）：一定の時間内にデータが仮想マシンに対して読み取りまたは書き込みされるレート。1 秒あたりのメガバイト数で測定されます。

Latency：データストア内の仮想マシンからの平均応答時間。

Top Latency：データストア内の仮想マシンからの最大応答時間。



 a| 
リンク障害です
 a| 
サンプリング期間中にポートで検出されたリンク障害の数。



 a| 
リンクリセット Rx 、 Tx
 a| 
サンプリング期間中に受信または送信されたリセットリンクの数。この指標は、このポートに対して接続されたポートから発行されたリンクリセットの数を表します。



 a| 
メモリ使用率（合計）
 a| 
ホストで使用されるメモリのしきい値。



 a| 
部分的 R/W （合計） %
 a| 
RAID 5 、 RAID 1/0 、または RAID 0 の LUN において、読み取り / 書き込み処理がディスクモジュールのストライプ境界を越えた合計回数。通常、ストライプを越えると、各 LUN で追加の I/O が必要になるため、ストライプを越えることは効果がありませんこの割合が低いほど、ストライプ要素のサイズは効率的であり、ボリューム（ネットアップの LUN ）のアライメントは不適切であることを示します。

CLARiX については、ストライプを越えた回数を IOPS の合計で割った値が示されます。



 a| 
ポートエラーです
 a| 
サンプリング期間中または一定の期間に検出されたポートエラーのレポート。



 a| 
信号損失回数
 a| 
信号損失エラーの数。信号損失エラーが発生した場合は、電気的接続がなく、物理的な問題があります。



 a| 
スワップレート（合計レート、インレート、アウトレート）
 a| 
サンプリング期間中にディスクとアクティブメモリの間にスワップイン速度、スワップアウト速度、またはその両方が発生した速度。これは環境仮想マシンのカウンタです。



 a| 
同期損失の数
 a| 
同期損失エラーの数同期損失エラーが発生した場合、ハードウェアはトラフィックを認識できないか、ロックオンされません。すべての機器のデータ速度が同じでないか、光接続または物理接続の品質が低下している可能性があります。このエラーが発生するたびにポートの再同期が必要になるため、システムのパフォーマンスに影響します。単位は KB/ 秒です



 a| 
スループット（合計、読み取り、書き込み）
 a| 
I/O サービス要求への応答として一定の時間内に送受信されたデータのレート（ 1 秒あたりの MB で測定）。



 a| 
タイムアウト廃棄フレーム数 - Tx
 a| 
送信フレームがタイムアウトで破棄された回数。



 a| 
トラフィック速度（合計、読み取り、書き込み）
 a| 
サンプリング期間中に送受信されたトラフィックの量（ 1 秒あたりのメビバイト数）。



 a| 
トラフィック利用率（合計、読み取り、書き込み）
 a| 
サンプリング期間中の送受信トラフィックの比率、受信 / 送信 / 合計容量に対するトラフィックの比率。



 a| 
利用率（合計、読み取り、書き込み）
 a| 
送信（ Tx ）と受信（ Rx ）に使用できる帯域幅の割合。



 a| 
書き込み保留（合計）
 a| 
保留中の書き込み I/O サービス要求の数。

|===