---
permalink: config-admin/monitoring-oncommand-insight-system-health.html 
sidebar: sidebar 
keywords:  
summary: 'Insightシステムコンポーネントの現在のステータスを[Health]ページで定期的に確認する必要があります。このページには、各コンポーネントのステータスが表示され、問題 がある場合はアラートが表示されます。' 
---
= OnCommand Insight システムヘルスを監視しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Insightシステムコンポーネントの現在のステータスを[Health]ページで定期的に確認する必要があります。このページには、各コンポーネントのステータスが表示され、問題 がある場合はアラートが表示されます。



== 手順

. InsightWeb UIにログインします。
. [管理]*をクリックし、*[ヘルス]*を選択します。
+
[Health]ページが表示されます。

. コンポーネントの現在のステータスを確認します。[* Details]*列のステータスの前に赤い丸が表示されている場合は、すぐに対処が必要な問題 を示しているため、特に注意してください。
+
[Health]ページには、Insightのコンポーネントのうち、システム構成に基づいて次のいずれかまたはすべてのコンポーネントに関する情報が表示されます。

+
|===


| コンポーネント | テスト | 詳細 | 表示されます 


 a| 
取得
 a| 
インベントリデータの処理
 a| 
Local Acquisition Unitのステータス
 a| 
同時にポーリングするデータソースの数が実行プールの最大数の75%未満（デフォルトの最大数は30）の場合、「OK」。「Acquisition is busy」は、使用率が75%を超える場合に使用します。ポーリング間隔を長くするか、Remote Acquisition Unitを追加することを推奨します。



 a| 
DWH
 a| 
バックアップ
 a| 
Data Warehouseのスケジュールされたバックアップのステータス
 a| 
DWHのスケジュールされたバックアップが有効になっている場合は、「OK」と前回成功したDWHのバックアップ時刻が表示されます。それ以外の場合は、検出されたエラーに関する情報が表示されます。



 a| 
DWH
 a| 
ETL
 a| 
Data WarehouseのETLのステータス
 a| 
「OK」と、エラーがなければ前回成功したDWHのビルド時間が表示されます。それ以外の場合は、検出されたエラーに関する情報が表示されます。



 a| 
サーバ
 a| 
ASUP
 a| 
ASUPのステータス
 a| 
「ASUP Enabled」と前回成功したPhonehome時間（該当する場合）。「ASUP Failed」は、Phonehomeが有効になっているが問題が発生した場合に表示されます。

+バックアップディレクトリが無効な場合は、「Invalid backup location（バックアップの場所が無効です）」。

+ Phonehomeが最後に成功した時刻と、最後に失敗した時刻（使用可能な場合）を表示します。

+「ASUP Disabled」（Phonehomeが無効な場合）



 a| 
サーバ
 a| 
自動解決
 a| 
自動デバイス解決のステータス
 a| 
エラーがなければ「OK」。識別エラーが解決の進行を妨げている場合は、「自動解決はブロックされています」と表示されます。

一般的なデバイスの75%未満を識別できる場合は、+"`Low success rate'"。



 a| 
サーバ
 a| 
Elasticsearch を指定します
 a| 
Elasticsearchデータストアのステータス
 a| 
エラーがなければ「OK」。Elastic Searchサービスに接続できない場合は、「Service Unavailable」と入力します。

+複数のノードが検出された場合は「Cluster mode detected」

+「High memory utilization」（ヒープ領域の使用率が85%を超えている場合）

+「ステータス：赤」は、Elasticsearchでエラーが報告されたことを示します。エラーに関する情報を表示し、カスタマーサポートに問い合わせることを推奨します。



 a| 
サーバ
 a| 
CPU
 a| 
InsightのCPU使用率
 a| 
CPU負荷が65%未満の場合は「OK」。"`SシステムのCPU負荷が高くなっています。CPUの負荷を軽減します。 CPU負荷が65%を超えている場合。



 a| 
サーバ
 a| 
ディスクスペース
 a| 
ディスクスペースのステータス
 a| 
空きディスクスペース、Insightで使用されているディスクスペース、およびInsight用に予約されている推奨ディスクスペース。ディスク使用率が80%を超えている場合は「Low Disk Space（ディスクスペースが不足しています）」。



 a| 
サーバ
 a| 
EventBusの略
 a| 
EventBusのステータス
 a| 
EventBusキューが空の場合は「`EventBus is empty`」、それ以外の場合はEventBusキューのステータスが表示されます。



 a| 
サーバ
 a| 
インベントリデータの処理
 a| 
Insight Serverのインベントリデータ処理機能のステータス
 a| 
Insight Serverがビジー状態でない場合は「OK」。サーバが過去1時間の75%以上の時間でビジー状態になっている場合、「サーバはビジー状態です」と表示されます。では、データソースを追加しないようにし、環境を複数のサーバに分割することを推奨しています。



 a| 
サーバ
 a| 
MySQL
 a| 
MySQLデータベースのステータス
 a| 
問題が検出されない場合は「OK」。"'データベースにパフォーマンスの問題があります。低速クエリの数が5%を超えると、一部のクエリの実行に時間がかかりすぎます。

+"'データベース・ログ・ファイルが過去1時間に<size> を超えて増加しましたエラーログが20 KBを超える場合は、MySQLログファイルを確認してください。



 a| 
サーバ
 a| 
パフォーマンスアーカイブ
 a| 
パフォーマンスアーカイブのステータス
 a| 
「Performance archive is enabled」または「Performance archive is not enabled」というメッセージが表示されます。



 a| 
サーバ
 a| 
物理メモリ
 a| 
物理メモリのステータス
 a| 
メモリ使用率が85%未満の場合は「OK」。"`memory usage is high.メモリ使用率が85%を超える場合は、システムの安定性のために全体的なメモリフットプリントを削減します。



 a| 
サーバ
 a| 
サービスパック
 a| 
サービスパックの有無
 a| 
Insightで使用可能なサービスパックがあるかどうかが表示されます。サービスパックが使用可能な場合は、指示が表示されます。



 a| 
サーバ
 a| 
使用状況の情報
 a| 
使用状況情報の送信ステータス
 a| 
使用状況に関する情報のネットアップへの送信が有効か無効かが表示されます。無効な場合は有効にすることをお勧め最後に試行された、または最後に成功した送信時刻を表示します

+発生した問題に関する情報を表示します。



 a| 
サーバ
 a| 
違反です
 a| 
未解決の違反のステータス
 a| 
未解決の違反の数が上限の75%未満の場合は「OK」。未解決の違反の数が上限の75%を超えている場合は、「Maximum number of open violations allowed is <number> 」と表示されます。パフォーマンスポリシーの設定を確認することを推奨します。

+「違反マネージャはブロックされています」は、未解決の違反の数が上限に達している場合に表示されます。

+新しい違反は作成できないので、パフォーマンスポリシーの設定を確認することを推奨します。



 a| 
サーバ
 a| 
週次バックアップ
 a| 
週次バックアップのステータス
 a| 
週次バックアップが有効になっている場合は「OK」、有効になっていない場合は「週次バックアップは有効になっていません」と表示されます。

|===

