---
permalink: config-admin/monitoring-fabric-inventory-and-performance.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insightのファイバチャネルアセットページを使用して、環境内のファブリックのパフォーマンスとインベントリを監視し、原因 の問題の可能性がある変更を把握することができます。 
---
= ファイバチャネル環境の監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insightのファイバチャネルアセットページを使用して、環境内のファブリックのパフォーマンスとインベントリを監視し、原因 の問題の可能性がある変更を把握することができます。



== Fibre Channelアセットページ

Insightのアセットページには、リソースに関する概要情報、トポロジ（デバイスとその接続）、パフォーマンスチャート、関連するリソースの表が表示されます。ファブリック、スイッチ、およびポートアセットのページを使用して、Fibre Channel環境を監視できます。ファイバチャネル問題 のトラブルシューティングを行う場合は、各ポートアセットのパフォーマンスチャートが特に役立ちます。このチャートには、最も影響が大きいポートのトラフィックが表示されます。また、バッファ間クレジットの指標やポートエラーも表示できます。Insightでは指標ごとに個別のパフォーマンスチャートが表示されます。



== ポート指標のパフォーマンスポリシー

Insightでは、パフォーマンスポリシーを作成して、さまざまなしきい値に基づいてネットワークを監視し、それらのしきい値を超えたときにアラートを生成することができます。使用可能なポート指標に基づいて、ポートのパフォーマンスポリシーを作成できます。しきい値の違反が発生すると、Insightによって検出され、関連するアセットページに赤い丸で表示されます。設定されている場合はEメールで通知されるほか、[Violations Dashboard]や違反を報告するカスタムダッシュボードにも表示されます。
