---
permalink: config-admin/netapp-data-ontap-operating-in-7-mode-data-source.html 
sidebar: sidebar 
keywords:  
summary: Data ONTAP 7-Modeソフトウェアを使用するストレージシステムの場合は、ONTAPIデータソースを使用します。このデータソースでは、CLIを使用して容量の値を取得します。 
---
= NetApp Data ONTAP 7-Modeデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Data ONTAP 7-Modeソフトウェアを使用するストレージシステムの場合は、ONTAPIデータソースを使用します。このデータソースでは、CLIを使用して容量の値を取得します。



== 用語集

OnCommand Insight では、NetApp Data ONTAP 7-Modeデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
ディスク
 a| 
ディスク



 a| 
RAID グループ
 a| 
ディスクグループ



 a| 
ストレージシステム
 a| 
ストレージ



 a| 
ストレージシステム
 a| 
ストレージノード



 a| 
アグリゲート
 a| 
ストレージプール



 a| 
LUN
 a| 
ボリューム



 a| 
ボリューム
 a| 
内部ボリューム

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* FAS ストレージコントローラおよびパートナーのIPアドレス
* ポート 443
* コントローラとパートナーのユーザ名とパスワード
* 7-Mode 用の次のロール権限を持つコントローラとパートナーコントローラのカスタムの管理者レベルのユーザ名とパスワードです。
+
** 「 api- * 」：すべてのネットアップストレージ API コマンドの実行を OnCommand Insight に許可します。
** 「 login-http-admin 」： HTTP 経由で OnCommand Insight がネットアップストレージに接続できるようにします。
** 「 security-api-vfiler 」： vFiler ユニットの情報を取得する NetApp ストレージ API コマンドの実行を OnCommand Insight に許可します。
** 「 cli-options 」：ストレージシステムオプションを読み取るために使用します。
** 「 cli-lun 」： LUN 管理用コマンドにアクセスします。指定した LUN または LUN のクラスのステータス（ LUN のパス、サイズ、オンライン / オフライン状態、共有状態）が表示されます。
** 「 cli-df 」：空きディスクスペースを表示する場合に使用します。
** 「 cli-ifconfig 」：インターフェイスと IP アドレスを表示します。






== 設定

|===


| * フィールド * | * 概要 * 


 a| 
Filerのアドレス
 a| 
ネットアップファイラーのIPアドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
NetApp Filerのユーザ名



 a| 
パスワード
 a| 
NetApp Filerのパスワード



 a| 
クラスタ内のHAパートナーファイラーのアドレス
 a| 
HAパートナーファイラーのIPアドレスまたは完全修飾ドメイン名



 a| 
クラスタ内のHAパートナーファイラーのユーザ名
 a| 
ネットアップHAパートナーファイラーのユーザ名



 a| 
クラスタ内の HA パートナーファイラーのパスワード
 a| 
ネットアップHAパートナーファイラーのパスワード

|===


== 高度な設定

|===


| * フィールド * | * 概要 * 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは20分）



 a| 
接続タイプ
 a| 
接続タイプを選択します



 a| 
接続ポート
 a| 
NetApp API に使用するポート



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）

|===


== ストレージシステム接続

このデータソースでデフォルトの管理ユーザを使用する代わりに、ネットアップストレージシステムに対する管理者権限を持つユーザを設定して、このデータソースがネットアップストレージシステムからデータを取得できるようにすることもできます。

ネットアップストレージシステムに接続するには、メインの pfiler （ストレージシステムが存在する pfiler ）の取得時に次の条件を満たすユーザを指定する必要があります。

* ユーザは vfiler0 （ルートファイラー / pfiler ）に属している必要があります。
+
メインの pfiler を取得するときにストレージシステムが取得されます。

* 次のコマンドで、ユーザロールの機能を定義します。
+
** 「 api- * 」：すべてのネットアップストレージ API コマンドの実行を OnCommand Insight に許可します。このコマンドは、 ZAPI を使用する場合は必須です。
** 「 login-http-admin 」： HTTP 経由で OnCommand Insight がネットアップストレージに接続できるようにします。このコマンドは、 ZAPI を使用する場合は必須です。
** 「 security-api-vfiler 」： vFiler ユニットの情報を取得する NetApp ストレージ API コマンドの実行を OnCommand Insight に許可します。
** 「 cli-options 」：「 options 」コマンドで、パートナーの IP と有効なライセンスを取得するために使用されます。
** 「cli-lun」：LUNを管理するためのコマンドにアクセスします。指定した LUN または LUN のクラスのステータス（ LUN のパス、サイズ、オンライン / オフライン状態、共有状態）が表示されます。
** 「 cli-df 」：「 df -s 」、「 df -r 」、「 df -A -r 」コマンドで、空きスペースを表示するために使用されます。
** 「 cli-ifconfig 」：「 ifconfig -a 」コマンドで、ファイラーの IP アドレスを取得するために使用されます。
** 「 cli-rdfile 」：「 rdfile /etc/netgroup 」コマンドで、ネットグループを取得するために使用されます。
** 「 cli-date 」：「 date 」コマンドで、 Snapshot コピーを取得する完全な日付を取得するために使用されます。
** 「 cli-snap 」：「 snap list 」コマンドで、 Snapshot コピーを取得するために使用されます。




cli-date または cli-snap の権限が付与されていない場合、データ収集は完了できますが、 Snapshot コピーは報告されません。

7-Mode データソースを正常に取得し、ストレージシステムで警告が生成されないようにするには、次のいずれかのコマンド文字列を使用してユーザロールを定義する必要があります。2 つ目の文字列は、 1 つ目の文字列を簡潔に表したものです。

[listing]
----
login-http-admin,api-*,security-api-vfile,cli-rdfile,cli-options,cli-df,cli-lun,cli-ifconfig,cli-date,cli-snap,
or
login-http-admin,api-*,security-api-vfile,cli-*
----