---
permalink: config-admin/netapp-host-and-vm-filesystems-data-source.html 
sidebar: sidebar 
keywords:  
summary: NetApp Host and VM File Systemsデータソースを使用して、すべてのMicrosoft WindowsホストとVM\（仮想マシン\）ファイルシステム、およびサポートされているすべてのLinux VM（仮想的にマッピングされているVMのみ\）について、ファイルシステムの詳細とストレージリソースのマッピングを取得できます。 設定済みのCompute Resource Group（CRG\）でアノテートされているInsight Server内の既存のファイル。 
---
= NetApp Host and VM File Systemsデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Host and VM File Systemsデータソースを使用して、すべてのMicrosoft WindowsホストおよびVM（仮想マシン）ファイルシステム、およびサポートされているすべてのLinux VM（仮想的にマッピングされたVMのみ）について、ファイルシステムの詳細とストレージリソースのマッピングを取得できます。 設定済みのCompute Resource Group（CRG；コンピューティングリソースグループ）でアノテートされているInsightサーバ内の既存のファイル。



== 一般要件

* この機能は別途購入する必要があります。
+
詳細については、Insightの担当者にお問い合わせください。

* Insightのサポートマトリックスで、お使いのホストまたは仮想マシンのオペレーティングシステムがサポートされていることを確認してください。
+
ファイルシステムからストレージリソースへのリンクが作成されていることを確認するには、関連するストレージベンダーまたは仮想化ベンダーのタイプとバージョンで、必要なボリュームまたは仮想ディスクの識別データが報告されていることを確認します。





== Microsoft Windowsの要件

* このデータソースは、Window Management Instrumentation（WMI）データ構造を使用してデータを取得します。
+
このサービスは動作しており、リモートで利用できる必要があります。特に、ポート135にアクセスできる必要があり、ファイアウォールの背後にある場合は開いておく必要があります。

* Windowsドメインユーザには、WMI構造にアクセスするための適切な権限が必要です。
* 管理者権限が必要です。
* Windows 2003以前に1024～65535が割り当てられた動的TCPポート
* ポート49152～-65535（Windows 2008の場合）


[NOTE]
====
原則として、Insight、AU、およびこのデータソースの間にファイアウォールを使用する場合は、Microsoftチームに相談して、必要と思われるポートを特定する必要があります。

====


== Linuxの要件

* このデータソースは、Secure Shell（SSH）接続を使用してLinux VMに対してコマンドを実行します。
+
SSHサービスが動作していて、リモートで使用できる必要があります。特に、ポート22にアクセスできる必要があり、ファイアウォールの背後にある場合はポート22を開く必要があります。

* SSHユーザには、Linux VMに対して読み取り専用コマンドを実行するためのsudo権限が必要です。
+
SSHへのログインとsudoパスワードチャレンジの回答 へのログインには、同じパスワードを使用する必要があります。





== 使用上の推奨事項

* オペレーティングシステムのクレデンシャルが同じホストおよび仮想マシンのグループには、同じ[Compute Resource Group]アノテーションをアノテートする必要があります。
+
各グループにこのデータソースのインスタンスが割り当てられ、それらのホストおよび仮想マシンからファイルシステムの詳細が検出されます。

* このデータソースのインスタンスで成功率が低い場合（たとえば、グループ内の1、000台のホストおよび仮想マシンのうち、OnCommand Insight でファイルシステムの詳細が検出されるのは50台のみ）、 検出に成功したホストと仮想マシンを別のコンピューティングリソースグループに移動する必要があります。




== 設定

|===


| フィールド | 説明 


 a| 
ユーザ名
 a| 
適切な権限を持つオペレーティングシステムユーザーWindowsオペレーティングシステムユーザーのファイルシステムデータを取得するには、ドメインプレフィックスを含める必要があります。



 a| 
パスワード
 a| 
オペレーティングシステムユーザのパスワード



 a| 
コンピュートリソースグループ
 a| 
データソースでファイルシステムを検出するホストおよび仮想マシンのフラグとして使用されるアノテーション値。値が空の場合は、現在いずれのコンピューティングリソースグループもアノテートされていないすべてのホストおよび仮想マシンのファイルシステムがデータソースで検出されます。

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
インベントリのポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは360分）

|===