---
permalink: config-admin/netapp-clustered-data-ontap-data-source.html 
sidebar: sidebar 
keywords:  
summary: このデータソースは、clustered Data ONTAP を使用するストレージシステムに使用します。読み取り専用のAPI呼び出しに使用する管理者アカウントが必要です。 
---
= NetApp clustered Data ONTAP データソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このデータソースは、clustered Data ONTAP を使用するストレージシステムに使用します。読み取り専用のAPI呼び出しに使用する管理者アカウントが必要です。



== 用語集

OnCommand Insight では、clustered Data ONTAP データソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
ディスク
 a| 
ディスク



 a| 
RAID グループ
 a| 
ディスクグループ



 a| 
クラスタ
 a| 
ストレージ



 a| 
ノード
 a| 
ストレージノード



 a| 
アグリゲート
 a| 
ストレージプール



 a| 
LUN
 a| 
ボリューム



 a| 
ボリューム
 a| 
内部ボリューム

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* 読み取り専用のAPI呼び出しに使用する管理者アカウント
* ターゲットIPはクラスタ管理LIFです
* ネットアップクラスタにログインするためのユーザ名（デフォルトのSVMに対するONTAPIアプリケーションの読み取り専用ロール名を使用）とパスワード
* ポートの要件： 80 または 443
* ライセンス要件：FCPライセンスと、検出に必要なマッピング/マスクされたボリューム




== 設定

|===


| * フィールド * | * 概要 * 


 a| 
ネットアップ管理 IP
 a| 
ネットアップクラスタの IP アドレスまたは完全修飾ドメイン名



 a| 
ユーザ名
 a| 
ネットアップクラスタのユーザ名



 a| 
パスワード
 a| 
ネットアップクラスタのパスワード

|===


== 高度な設定

|===


| * フィールド * | * 概要 * 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは20分）



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）

|===