---
permalink: config-admin/oracle-zfs-data-source.html 
sidebar: sidebar 
keywords:  
summary: Oracle ZFSデータソースで、インベントリとパフォーマンスの収集がサポートされるようになりました。 
---
= Oracle ZFSデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle ZFSデータソースで、インベントリとパフォーマンスの収集がサポートされるようになりました。



== 用語集

OnCommand Insight では、このデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
ディスク（SDD）
 a| 
ディスク



 a| 
クラスタ
 a| 
ストレージ



 a| 
コントローラ
 a| 
ストレージノード



 a| 
LUN
 a| 
ボリューム



 a| 
LUN マップ
 a| 
ボリュームマップ



 a| 
イニシエータ、ターゲット
 a| 
ボリュームマスク



 a| 
共有
 a| 
内部ボリューム

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

このデータソースの設定に関する要件は次のとおりです。

* ZFS Controller-1 および ZFS Controller-2 のホスト名
* 管理者のユーザ名とクレデンシャル
* ポート要件： 215 HTTP/HTTPS




== 設定

|===


|  |  


 a| 
ZFS Controller-1 ホスト名
 a| 
ストレージコントローラ 1 のホスト名



 a| 
ZFS Controller-2 ホスト名
 a| 
ストレージコントローラ 2 のホスト名



 a| 
ユーザ名
 a| 
ストレージシステム管理者ユーザアカウントのユーザ名



 a| 
パスワード
 a| 
管理者ユーザアカウントのパスワード

|===


== 高度な設定

|===


| フィールド | 説明 


 a| 
TCP ポート
 a| 
ZFSへの接続に使用するTCPポート（デフォルトは215）



 a| 
接続タイプ
 a| 
HTTPまたはHTTPS



 a| 
インベントリのポーリング間隔
 a| 
インベントリのポーリング間隔（デフォルトは60分）



 a| 
接続タイムアウト
 a| 
デフォルトは60秒です



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）

|===


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。

|===


| 問題 | 次の操作を実行します 


 a| 
" 無効なログイン資格情報 "
 a| 
ZFS ユーザーアカウントとパスワードを検証します



 a| 
「Configuration error」と「Rest Service is disabled」というエラーメッセージが表示されます。
 a| 
このデバイスで REST サービスが有効になっていることを確認します。



 a| 
「Configuration error」と表示され、「User unauthorized for command」というエラーメッセージが表示されます。
 a| 
特定のロール（「advanced_analytics」など）が設定されているユーザ<userName> に含まれていない可能性があります。考えられる解決策 ：

* 読み取り専用ロールを持つユーザー$｛user｝のAnalytics（統計）スコープを修正します。-[構成]→[ユーザー]画面で、ロールの上にマウスを置き、ダブルクリックして編集を許可します
* [Scope]ドロップダウンメニューから[Analytics]を選択します。使用可能なプロパティのリストが表示されます。
* 一番上のチェックボックスをクリックすると、3つのプロパティがすべて選択されます。-右側の[追加]ボタンをクリックします。
* ポップアップウィンドウの右上にある[適用]ボタンをクリックします。ポップアップウィンドウが閉じます。


|===