---
permalink: config-admin/performance-policy-precedence.html 
sidebar: sidebar 
keywords:  
summary: '[パフォーマンスポリシー]ページでは、オブジェクトタイプ別にポリシーがグループ化され、オブジェクトのパフォーマンスポリシーのリストに表示される順序でポリシーが評価されます。ネットワークで最も重要な情報を表示するために、Insightでポリシーが評価される順序を変更することができます。' 
---
= パフォーマンスポリシーの評価順序
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[パフォーマンスポリシー]ページでは、オブジェクトタイプ別にポリシーがグループ化され、オブジェクトのパフォーマンスポリシーのリストに表示される順序でポリシーが評価されます。ネットワークで最も重要な情報を表示するために、Insightでポリシーが評価される順序を変更することができます。

Insightでは、オブジェクトのパフォーマンスデータのサンプルがシステムに取り込まれると、そのオブジェクトに該当するすべてのポリシーが順番に評価されます。ただし、アノテーションによっては、すべてのポリシーが1つのオブジェクトグループに適用されるわけではありません。たとえば、内部ボリュームに次のポリシーが設定されているとします。

* ポリシー1（Insightが提供するデフォルトポリシー）
* ポリシー2（アノテーション「`Service Level=Silver`」、*[Stop processing further policies if alert is generated]*オプションが指定
* ポリシー3（アノテーション「`Service Level=Gold」）
* ポリシー4.


アノテーションがGoldの内部ボリューム階層の場合、Insightではポリシー1が評価され、ポリシー2は無視されてからポリシー3とポリシー4が評価されます。階層にアノテーションが設定されていない場合は、ポリシーの順序に従って評価されます。そのため、ポリシー1とポリシー4のみが評価されます。Silverのアノテーションが設定された内部ボリューム階層については、ポリシー1とポリシー2が評価されます。 ただし、ポリシーのしきい値を1回超えたときにアラートがトリガーされ、ポリシーで指定された時間内にそのポリシーを超えると、リスト内の他のポリシーは評価されず、オブジェクトの現在のカウンタが評価されます。Insightでオブジェクトの次のパフォーマンスサンプルのセットがキャプチャされると、フィルタと順序に基づいてオブジェクトのパフォーマンスポリシーの評価が再開されます。
