---
permalink: config-admin/performance-policy-management.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight では、パフォーマンスポリシーを作成して、さまざまなしきい値に基づいてネットワークを監視し、それらのしきい値を超えたときにアラートを生成することができます。パフォーマンスポリシーを使用すると、しきい値の違反を即座に検出してその影響を特定し、問題の影響と根本原因 を分析して迅速かつ効果的に対処できます。 
---
= パフォーマンスポリシーの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight では、パフォーマンスポリシーを作成して、さまざまなしきい値に基づいてネットワークを監視し、それらのしきい値を超えたときにアラートを生成することができます。パフォーマンスポリシーを使用すると、しきい値の違反を即座に検出してその影響を特定し、問題の影響と根本原因 を分析して迅速かつ効果的に対処できます。

パフォーマンスポリシーを使用すると、任意のオブジェクト（データストア、ディスク、ハイパーバイザー、内部ボリューム、ポート、 ストレージ、ストレージノード、ストレージプール、VMDK、仮想マシン、 とvolume）を使用し、パフォーマンスカウンタ（合計IOPSなど）が報告されていることを確認します。しきい値の違反が発生すると、Insightによって検出され、関連するアセットページに赤い丸で表示されます。設定されている場合はEメールで通知されるほか、[Violations Dashboard]や違反を報告するカスタムダッシュボードにも表示されます。

Insightには、次のオブジェクトに対するデフォルトのパフォーマンスポリシーがいくつか用意されています。これらのポリシーは、環境に応じて変更または削除できます。

* ハイパーバイザー
+
ESXスワッピングとESX利用に関するポリシーが用意されています。

* 内部ボリュームとボリューム
+
リソースごとに2つのレイテンシポリシーがあり、1つはティア1用にアノテートされ、もう1つはティア2用にアノテートされます。

* ポート
+
BBクレジットゼロのポリシーがあります。

* ストレージノード
+
ノード利用率に関するポリシーが用意されています。

* 仮想マシン
+
VMスワッピングとESXのCPUおよびメモリに関するポリシーが用意されています。

* ボリューム
+
階層別およびミスアライメントされたボリュームポリシー別のレイテンシがあります。


