---
permalink: config-admin/predefined-annotation-types.html 
sidebar: sidebar 
keywords:  
summary: OnCommandInsightには、デフォルトのアノテーションタイプがいくつか用意されています。これらのアノテーションを使用して、データをフィルタまたはグループ化したり、データレポートをフィルタリングしたりできます。 
---
= デフォルトのアノテーションタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommandInsightには、デフォルトのアノテーションタイプがいくつか用意されています。これらのアノテーションを使用して、データをフィルタまたはグループ化したり、データレポートをフィルタリングしたりできます。

次のようなデフォルトのアノテーションタイプをアセットに関連付けることができます。

* アセットのライフサイクル：開始日、停止日、終了日など
* デバイスの場所の情報。データセンター、建物、フロアなど
* 品質（階層）、接続デバイス（スイッチレベル）、サービスレベルなどのアセットの分類
* ステータス（ホット（高利用率）など）


次の表に、デフォルトのアノテーションタイプを示します。これらのアノテーションの名前は必要に応じて編集できます。

|===


| アノテーションタイプ | 説明 | を入力します 


 a| 
エイリアス
 a| 
リソースのフレンドリ名。
 a| 
テキスト（ Text ）



 a| 
誕生日
 a| 
デバイスがオンラインになった日付、またはオンラインになる予定の日付。
 a| 
日付



 a| 
建物
 a| 
ホスト、ストレージ、スイッチ、およびテープリソースの物理的な場所。
 a| 
リスト



 a| 
市区町村
 a| 
ホスト、ストレージ、スイッチ、およびテープリソースが配置されている自治体。
 a| 
リスト



 a| 
コンピュートリソースグループ
 a| 
Host and VM File Systemsデータソースで使用されるグループ割り当て。
 a| 
リスト



 a| 
大陸
 a| 
ホスト、ストレージ、スイッチ、およびテープリソースの地理的な場所。
 a| 
リスト



 a| 
国名
 a| 
ホスト、ストレージ、スイッチ、およびテープリソースが配置されている国。
 a| 
リスト



 a| 
データセンター
 a| 
リソースの物理的な場所。ホスト、ストレージアレイ、スイッチ、およびテープで使用できます。
 a| 
リスト



 a| 
直接接続
 a| 
ストレージリソースがホストに直接接続されているかどうか（[Yes]または[No]）を示します。
 a| 
ブール値



 a| 
サポート終了
 a| 
リースの期限が切れた場合やハードウェアが撤去される場合など、デバイスがオフラインになる日付。
 a| 
日付



 a| 
ファブリックエイリアス
 a| 
ファブリックのフレンドリ名。
 a| 
テキスト（ Text ）



 a| 
床
 a| 
建物のフロア上のデバイスの場所。ホスト、ストレージアレイ、スイッチ、およびテープに対して設定できます。
 a| 
リスト



 a| 
ホット
 a| 
定期的に頻繁に使用されている、または容量のしきい値に達しているデバイス。
 a| 
ブール値



 a| 
注
 a| 
リソースに関連付けるコメント。
 a| 
テキスト（ Text ）



 a| 
ラック
 a| 
リソースが配置されているラック。
 a| 
テキスト（ Text ）



 a| 
部屋
 a| 
ホスト、ストレージ、スイッチ、およびテープリソースが配置されている建物内の部屋。
 a| 
リスト



 a| 
SAN
 a| 
ネットワークの論理パーティション。ホスト、ストレージアレイ、テープ、スイッチ、アプリケーションで使用できます。
 a| 
リスト



 a| 
サービスレベル
 a| 
リソースに割り当てることができる一連のサポート対象サービスレベル。内部ボリューム、 qtree 、およびボリュームの番号付きのオプションのリストが用意されています。サービスレベルを編集して、各レベルのパフォーマンスポリシーを設定できます。
 a| 
リスト



 a| 
都道府県
 a| 
リソースが配置されている都道府県。
 a| 
リスト



 a| 
日没
 a| 
そのデバイスに新しい割り当てを実行できないしきい値。計画的な移行や保留中のネットワークの変更に役立ちます。
 a| 
日付



 a| 
スイッチレベル
 a| 
スイッチのカテゴリを設定するための事前定義されたオプションが含まれています。通常、これらの指定はデバイスの寿命の間維持されますが、必要に応じて編集できます。スイッチに対してのみ設定できます。
 a| 
リスト



 a| 
階層
 a| 
を使用すると、環境内のさまざまなサービスレベルを定義できます。階層では、必要な速度などのレベルを定義できます（例： Gold や Silver ）。この機能は、内部ボリューム、 qtree 、ストレージアレイ、ストレージプール、およびボリュームに対してのみ使用できます。
 a| 
リスト



 a| 
違反の重大度
 a| 
違反（ホストポートの欠落や冗長性の欠如など）のランク（例： Major ）。重要度の高い順に階層化されています。
 a| 
リスト

|===
[NOTE]
====
エイリアス、データセンター、ホット、サービスレベル、サンセット、 スイッチレベル、サービスレベル、階層、および違反の重大度はシステムレベルのアノテーションであり、削除や名前変更はできません。変更できるのは割り当てられている値のみです。

====