---
permalink: config-admin/researching-a-failed-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'データソースに「Inventory failed！」というメッセージが表示されている場合 または「Performance failed！」 メッセージと[影響度が高]または[影響度が中]の場合は、データソースの概要ページとリンクされた情報を使用して、この問題を調査する必要があります。' 
---
= データソースの問題を調査しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データソースに「* Inventory failed！*」または「* Performance failed！*」というメッセージが表示され、[Impact]が[High]または[Medium]になっている場合は、データソースの概要ページにリンクされた情報を使用してこの問題を調査する必要があり



== 手順

. データソースのリンクされた* Name *をクリックして、Summaryページを開きます。
. [Summary]ページで[* Comments]領域を確認し、この問題を調査している可能性のある別のエンジニアが残したメモを確認します。
. パフォーマンスのメッセージを確認します。
. このデータソースに適用されているパッチがある場合は、リンクをクリックして*パッチページ*を確認し、それが問題の原因であるかどうかを確認します。
. 追加情報 を表示するには、*イベントタイムライン*グラフのセグメントの上にマウスポインタを移動します。
. イベントタイムラインの下に表示されるデバイスのエラーメッセージを選択し、メッセージの右側に表示される*エラーの詳細*アイコンをクリックします。
+
エラーの詳細には、エラーメッセージのテキスト、考えられる原因、使用中の情報、問題を修正するために試すことができる推奨事項が含まれています。

. [Devices reported by this data source]領域で、リストをフィルタして目的のデバイスのみを表示できます。また、デバイスのリンクされた* Name *をクリックすると、そのデバイスの_asset page_が表示されます。
. 以前に表示したページに戻るには、次のいずれかの方法を使用します。
+
** ブラウザの戻る矢印をクリックします。
** 戻る矢印を右クリックしてページのリストを表示し、目的のページを選択します。


. 他のリソースに関する詳細情報を表示するには、[その他のリンクされた名前]をクリックします。
. データソースの概要ページに戻ったら、ページ下部の*変更*領域で、最近の変更が問題の原因になっていないかどうかを確認します。

