---
permalink: config-admin/scrubbing-data-for-transfer-to-support-webui.html 
sidebar: sidebar 
keywords:  
summary: セキュアな環境を構築しているお客様は、発生した問題をトラブルシューティングするために、ネットアップカスタマーサービスと通信し、データベース情報を犠牲にすることはありません。OnCommand Insight スクラブユーティリティを使用すると、キーワードとパターンの包括的な辞書を設定して、機密データを「クレンジング」し、スクラビングされたファイルをカスタマーサポートに送信できます。 
---
= サポートへの転送用にデータをスクラビングしています
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュアな環境を構築しているお客様は、発生した問題をトラブルシューティングするために、ネットアップカスタマーサービスと通信し、データベース情報を犠牲にすることはありません。OnCommand Insight スクラブユーティリティを使用すると、キーワードとパターンの包括的な辞書を設定して、機密データを「クレンジング」し、スクラビングされたファイルをカスタマーサポートに送信できます。



== 手順

. Web UIで、*[Admin]*をクリックし、*[Troubleshooting]*を選択します。
. ページ下部の[その他のタスク]領域で、*[スクラブユーティリティ]*リンクをクリックします。
+
[Lookup in Dictionary]、[Scrub data]、[Build dictionary]、[Custom keywords]、および[Regular expressions]という複数のスクラビングセクションがあります。

. 
+
.. [**Lookup in dictionary**]セクションで、置換する値を表示するコードを入力するか、置換するコードを表示する値を入力します。注:ルックアップを実行する前に、サポートデータからスクラブする値を識別するためのディクショナリを*ビルド*する必要があります。


. サポートデータからスクラブする独自のキーワードを追加するには、*カスタムキーワード*セクションで、メニューの[アクション][カスタムキーワードの追加]をクリックします。キーワードを入力し、*[保存]*をクリックします。キーワードがディクショナリに追加されます。
. [*パターン（regexp）]*を展開します。[追加（Add）]*をクリックして、新しいパターンを入力するためのダイアログボックスを表示します。
. スクラビングする単語やフレーズを識別するために正規表現を使用するには、* regular expressions *セクションにパターンを入力します。[メニュー:アクション][正規表現の追加]をクリックし、フィールドにパターンの名前と正規表現を入力して*[保存]*をクリックします。情報がディクショナリに追加されました。
+
[NOTE]
====
正規表現キャプチャグループを識別するには、パターンを丸括弧で囲む必要があります。

====
. [**Build dictionary*]セクションで、[Build*]をクリックして、OnCommand Insight データベースから機密と識別されたすべての単語の辞書のコンパイルを開始します。
+
完了すると、改訂されたディクショナリが使用可能であることを通知するプロンプトが表示されます。Database概要 には、ディクショナリ内のキーワードの数を示す行が含まれています。辞書でキーワードの正確さを確認してください。問題が見つかった場合に辞書を再構築するには、[データベース]ブロックの*[リセット]*をクリックして、OnCommand Insight データベースから収集されたすべてのキーワードを辞書から削除します。プロンプトが示すように、他のキーワードは削除されません。Scrubユーティリティに戻り、カスタムキーワードをもう一度入力します。

. Scrubディクショナリを作成したら、そのディクショナリを使用してログ、XML、またはその他のテキストファイルをスクラビングし、データを匿名にすることができます。
. ログ、XML、またはその他のテキストファイルをスクラビングするには、* Scrub data *セクションで参照してファイルを探し、* Scrub file *をクリックします。

