---
permalink: config-admin/setting-up-and-managing-user-accounts.html 
sidebar: sidebar 
keywords:  
summary: ユーザアカウント、ユーザ認証、およびユーザ許可は、Microsoft Active Directory\（バージョン2または3\）LDAP\（Lightweight Directory Access Protocol\）サーバ、または内部OnCommand Insight ユーザデータベースのいずれかの方法で定義および管理できます。ユーザごとに異なるユーザアカウントを設定することで、アクセス権、個 々 の設定、およびアカウンタビリティを制御できます。この操作には、管理者権限を持つアカウントを使用してください。 
---
= ユーザアカウントの設定と管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザアカウント、ユーザ認証、およびユーザ許可は、Microsoft Active Directory（バージョン2または3）LDAP（Lightweight Directory Access Protocol）サーバ、または内部OnCommand Insight ユーザデータベースのいずれかの方法で定義および管理できます。ユーザごとに異なるユーザアカウントを設定することで、アクセス権、個 々 の設定、およびアカウンタビリティを制御できます。この操作には、管理者権限を持つアカウントを使用してください。



== 作業を開始する前に

次の作業を完了しておきます。

* OnCommand Insight ライセンスをインストールします。
* 各ユーザに一意のユーザ名を割り当てます。
* 使用するパスワードを決定します。
* 正しいユーザロールを割り当てます。



NOTE: LDAP証明書をインポートする際に、を使用して_server.keystore_and/or_server.trustore_passwordsを変更した場合はlink:../config-admin/security-management.html["securityadmin"]、SANscreen証明書をインポートする前に_ldap_serviceを再起動してください。

[NOTE]
====
セキュリティのベストプラクティスでは、管理者がホストオペレーティングシステムを設定して、管理者以外のユーザや標準ユーザが対話的にログインできないようにすることを推奨しています。

====


== 手順

. ブラウザでInsightを開きます。
. Insightのツールバーで、*[Admin]*をクリックします。
. [設定]*をクリックします。
. [**ユーザー**]タブを選択します。
. 新しいユーザを作成するには、*[Actions]*ボタンをクリックし、*[Add user]*を選択します。
+
[名前]、[パスワード]、[電子メール]のいずれかのアドレスを入力し、[管理者]、[ユーザ]、[ゲスト]のいずれかのユーザを選択します。

. ユーザーの情報を変更するには、リストからユーザーを選択し、ユーザー概要 の右側にある*ユーザーアカウントの編集*記号をクリックします。
. OnCommand Insight システムからユーザを削除するには、リストからユーザを選択し、ユーザ概要 の右側にある*[ユーザアカウントの削除]*をクリックします。




== 結果

ユーザがOnCommand Insight にログインすると、LDAPが有効になっている場合、サーバは最初にLDAPによる認証を試みます。ユーザがLDAPサーバで見つからない場合、OnCommand Insight はローカルのInsightデータベースで検索します。
