---
permalink: config-admin/setting-up-weekly-backups-for-your-oci-database.html 
sidebar: sidebar 
keywords:  
summary: データを保護するために、Insightデータベースの自動週次バックアップを設定することができます。これらの自動バックアップでは、指定したバックアップディレクトリ内のファイルが上書きされます。 
---
= Insightデータベースの週次バックアップの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データを保護するために、Insightデータベースの自動週次バックアップを設定することができます。これらの自動バックアップでは、指定したバックアップディレクトリ内のファイルが上書きされます。



== このタスクについて

*ベストプラクティス*：OCIデータベースの週次バックアップを設定する場合は、そのサーバで障害が発生した場合に備えて、Insightで使用しているサーバとは別のサーバにバックアップを保存する必要があります。週次バックアップではディレクトリ内のファイルが上書きされるため、週次バックアップディレクトリに手動バックアップを保存しないでください。

バックアップファイルには次の内容が含まれます。

* インベントリデータ
* 最大7日分のパフォーマンスデータ




== 手順

. Insightのツールバーで、* Admin *>* Setup *をクリックします。
. [バックアップとアーカイブ]*タブをクリックします。
. [Weekly Backup]セクションで、*[Enable weekly backup]*を選択します。
. バックアップ先*へのパスを入力します。これは、ローカルのInsight Server上のに配置することも、Insight Serverからアクセスできるリモートサーバ上に配置することもできます。
+
[NOTE]
====
バックアップの場所の設定はバックアップ自体に含まれているため、別のシステムにバックアップをリストアする場合は、新しいシステムではバックアップフォルダの場所が無効である可能性があることに注意してください。バックアップのリストア後に、バックアップの場所の設定を再確認してください。

====
. [Cleanup]*オプションを選択して、バックアップを2つまたは5つ保持します。
. [ 保存（ Save ） ] をクリックします。




== 結果

* Admin *>* Troubleshooting *に移動して、オンデマンドバックアップを作成することもできます。
