---
permalink: config-admin/using-options-in-the-preferences-tab.html 
sidebar: sidebar 
keywords:  
summary: デバイス解決のプリファレンスタブでは、自動解決スケジュールの作成、識別情報を含めるストレージベンダーやテープベンダーの指定、および DNS 検索オプションの設定を行うことができます。 
---
= [ 環境設定 ] タブでオプションを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デバイス解決のプリファレンスタブでは、自動解決スケジュールの作成、識別情報を含めるストレージベンダーやテープベンダーの指定、および DNS 検索オプションの設定を行うことができます。



== 自動解決スケジュール

自動デバイス解決を実行するスケジュールを指定できます。

|===


| オプション | 説明 


 a| 
間隔
 a| 
曜日、時間、または分単位で自動デバイス解決を実行する場合は、このオプションを使用します。



 a| 
毎日
 a| 
このオプションは、自動デバイス解決を特定の時刻に毎日実行する場合に使用します。



 a| 
手動で実行する
 a| 
このオプションは、自動デバイス解決を手動でのみ実行する場合に使用します。



 a| 
環境が変化するたびに
 a| 
このオプションは、環境に変更があったときに自動デバイス解決を実行する場合に使用します。

|===
手動でを指定すると、夜間の自動デバイス解決は無効になります。



== DNS の処理オプション

DNS の処理オプションでは、次の機能を選択できます。

* DNS ルックアップの結果の処理を有効にすると、解決されたデバイスに付加する DNS 名のリストを追加できます。
* 「IPの自動解決：」を選択すると、DNSルックアップを使用して、iSCSIイニシエータおよびNFS共有にアクセスするホストに対して自動ホスト解決を有効にできます。指定しない場合は、 FC ベースの解決のみが実行されます。
* ホスト名にアンダースコアを使用できるようにすることも、標準のポートエイリアスの代わりに「接続先」のエイリアスを使用することもできます。




== ストレージやテープの特定のベンダーを含めるか、除外します

ストレージやテープの特定のベンダーを自動解決の対象に含めたり除外したりできます。レガシーホストとなり、新しい環境から除外する必要があることがわかっているホストがある場合などは、特定のベンダーを除外することができます。除外したベンダーを再度追加することもできます。

[NOTE]
====
テープのデバイス解決ルールは、ベンダー環境設定でそのWWNのベンダーが*テープのみとして含まれる*に設定されているWWNに対してのみ機能します。

====