---
permalink: config-admin/vmware-vsphere-web-services-data-source.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere\（Web Services\）データソースはESXホスト情報を収集します。Virtual Center内のすべてのオブジェクトに対する読み取り専用の権限が必要です。 
---
= VMware vSphereデータソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere（Web Services）データソースはESXホスト情報を収集し、Virtual Center内のすべてのオブジェクトに対して_read-only_privilegesを必要とします。



== 用語集

OnCommand Insight では、VMware vSphereデータソースから次のインベントリ情報を取得します。Insightで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータソースを表示またはトラブルシューティングするときは、次の用語に注意してください。

|===


| ベンダー / モデルの用語 | Insightの用語 


 a| 
仮想ディスク
 a| 
ディスク



 a| 
ホスト
 a| 
ホスト



 a| 
仮想マシン
 a| 
仮想マシン



 a| 
データストア
 a| 
データストア



 a| 
LUN
 a| 
LUN



 a| 
ファイバチャネルポート
 a| 
ポート

|===
[NOTE]
====
これらは一般的な用語のマッピングであり、このデータソースのすべてのケースを表しているとは限りません。

====


== 要件

* Virtual Center サーバの IP アドレス
* Virtual Center の読み取り専用のユーザ名とパスワード
* Virtual Center内のすべてのオブジェクトに対する読み取り専用権限。
* Virtual Centerサーバ上のSDKアクセス
* ポート要件： http - 80 https-443
* ユーザ名とパスワードを使用してVirtual Center Clientにログインし、と入力してSDKが有効になっていることを確認して、アクセスを検証します `telnet <vc_ip\> 443`。




== 設定

|===
| * フィールド * 


| * 概要 * 


 a| 
Virtual Center Addressの略



 a| 
Virtual CenterまたはvSphereサーバのネットワークアドレス。IP_（nnn.nnn.nnn.nnn_format）アドレス、またはDNSで解決できるホスト名で指定します。



 a| 
ユーザ名



 a| 
VMwareサーバのユーザ名。



 a| 
パスワード



 a| 
VMwareサーバのパスワード。

|===


== 高度な設定

|===


| * フィールド * | * 概要 * 


 a| 
インベントリポーリング間隔（分）
 a| 
インベントリポーリングの間隔（デフォルトは20分）



 a| 
接続タイムアウト（ミリ秒）
 a| 
接続タイムアウト（デフォルトは60000ミリ秒）



 a| 
で VM をフィルタリングします
 a| 
VMをフィルタする方法を選択します



 a| 
「除外」または「含める」を選択してリストを指定します
 a| 
以下のリストにあるVMをデータの収集時に対象に含めるか除外するかを指定します



 a| 
フィルタするVMのリスト（カンマ区切り、値にカンマを使用する場合はセミコロン区切り）
 a| 
ポーリングの対象または対象から除外するVMをカンマまたはセミコロンで区切ったリスト



 a| 
vCenterへの要求の再試行回数
 a| 
vCenter要求の再試行回数



 a| 
通信ポート
 a| 
VMwareサーバに使用するポート



 a| 
パフォーマンスポーリング間隔（秒）
 a| 
パフォーマンスのポーリング間隔（デフォルトは 300 秒）

|===