---
permalink: faq/faq-additional-information.html 
sidebar: sidebar 
keywords: redhat,Linux 
summary: 追加情報 はどこで入手できますか。 
---
= 追加情報
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
追加情報 for OnCommand Insight の最終版はどこで入手できますか。



== データソースのサポート

Insightでサポートされているデータソースについては、OnCommand Insight のデータソースサポートマトリックスを参照してください。NetApp Support Siteのクレデンシャルでログインするように求められます。

link:https://mysupport.netapp.com/api/content-service/staticcontents/content/products/oncommandinsight/DatasourceSupportMatrix_7.3.x.pdf["OnCommand Insight データソースサポートマトリックス"]現在サポートされているOnCommand Insight のバージョンのサポートマトリックス。



== サポート

link:https://mysupport.netapp.com/matrix["ネットアップの Interoperability Matrix Tool （ IMT ）"]OnCommand Insight でサポートされるデバイスとプラットフォームについて説明します。

link:https://mysupport.netapp.com/site/products/all/details/oncommand-insight/guideme-tab["ネットアップのGuided Problem Solving"]Guided Problem Solvingには、厳選された技術コンテンツ、How-To、トラブルシューティング手順が製品、機能、タスク別にまとめられています。チャットを使用すると、ケースを開始したりテクニカルサポートに電話したりすることなく、問題を迅速に解決できます。

ネットアップナレッジベースでは、製品の管理に関する技術記事を参照できます。ナレッジベースの一部は一般に公開されています。登録ユーザは、より広範な技術知識ベースの記事にアクセスできます。

ネットアップグローバルサービスのお問い合わせ地域のサポートセンターにお問い合わせください。



== コミュニティ

ネットアップStorefrontネットアップが提供する豊富なレポートテンプレート、解決策 Pack、データコレクタ、OnCommand Insight 向けスクリプトの例をダウンロードできます。

OnCommand Insight ビデオOnCommand Insight 製品のビデオプレイリストから、さまざまなトピックに関するビデオを視聴できます。

INSIGHTコミュニティのディスカッションOnCommand Insight のディスカッションに参加しましょう。



== その他

IBM Cognos Documentation for IBM CognosのWebサイト
