---
settings:
  name: OnCommand Insight
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: OnCommand Insight のドキュメント
    url: "/index.html"
  - section: relnotes
  - section: overview
  - section: install-linux
  - section: install-windows
  - section: config-admin
  - section: dwh
  - section: reporting
  - section: faq
  - section: howto
  - title: Data Collector サポートマトリックス
    url: "/config-admin/reference_data_collector_support_matrix.html"
  - title: 法的通知
    url: "/legal-notices.html"
