---
permalink: reporting/data-model-overview.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight には、レポート開発で使用する複数のデータモデルが用意されています。各データモデルは、クエリや検索ができるようにデータを集約したものです。たとえば、キャパシティプランニングに関するレポートでは、Capacityデータモデルを使用します。 
---
= データモデルの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight には、レポート開発で使用する複数のデータモデルが用意されています。各データモデルは、クエリや検索ができるようにデータを集約したものです。たとえば、キャパシティプランニングに関するレポートでは、Capacityデータモデルを使用します。

OnCommand Insight エンタープライズレポートデータモデルは、データ要素とデータ要素間のインタラクティブな関係を提供し、データのビジネスビューを提供します。これらのデータ要素と関係を使用して、ネットアップが推奨するIBM Cognos Analyticsレポート生成ツールを使用してレポートを作成できます。

OnCommand Insight には、独自のSQLクエリの開発に使用できるデータマートも用意されています。これらのSQLクエリデータマートとレポートに使用されるデータモデルには違いがあります。個 々 のOnCommand Insight Reportingデータモデルは、データマートで提供される基盤となるOnCommand Insight データベーススキーマを使用します。ただし、データモデルは追加のテーブルを使用し、場合によってはテーブル内の新しい要素を使用します。たとえば、このデータモデルには、データベーススキーマおよびデータマートのCapacityファクトテーブルに基づいて、Storage CapacityデータモデルにMonthly Capacityファクトテーブルが含まれています。データモデルは、データベーススキーマテーブルの値をフィルタリングして、月の情報のみを表示します。

データマートで使用されるデータベーススキーマとデータモデルの違いを示すもう1つの例として、[Violation]テーブルと[Violation Type]列があります。データモデルは、データベース内のプログラムによって指定された値を、OnCommand Insight Web UIに表示されるテキストと一致するように変換します。
