---
permalink: reporting/oncommand-insight-data-model-descriptions.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight には複数のデータモデルが用意されており、事前定義されたレポートを選択することも、独自のカスタムレポートを作成することもできます。 
---
= OnCommand Insight データモデル
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight には複数のデータモデルが用意されており、事前定義されたレポートを選択することも、独自のカスタムレポートを作成することもできます。

各データモデルにはシンプルなデータマートと高度なデータマートが含まれています。

* シンプルなデータマートを使用すると、よく使用されるデータ要素にすばやくアクセスできます。Data Warehouseデータの最新のSnapshotのみが含まれ、履歴データは含まれません。
* 高度なデータマートは、シンプルなデータマートから利用可能なすべての値と詳細を提供し、履歴データ値へのアクセスを含みます。
* *容量データモデル*
+
ストレージ容量、ファイルシステム利用率、内部ボリュームの容量、ポート容量、 qtree 容量に関する回答の情報を表示します。 仮想マシン（ VM ）の容量が必要です。Capacity データモデルは、複数の容量データモデルをまとめたコンテナです。このデータモデルを使用して、さまざまなタイプの情報を収集したレポートを作成できます。

+
** *ストレージおよびストレージプール容量データモデル*
+
ストレージとストレージプール、および物理ストレージプールと仮想ストレージプールの両方のデータについて、ストレージ容量のリソース計画に関する回答の情報を確認できます。このシンプルなデータモデルを使用すると、フロアの容量に関連する回答の質問や、一定期間にわたる階層別およびデータセンター別のストレージプールの使用容量に関する情報を確認できます。

+
容量に関するレポートを初めて作成する場合は、シンプルでターゲットが限定されたこのデータモデルを使用してください。このデータモデルを使用すると、次のような回答の情報を確認できます。

+
*** 物理ストレージの容量しきい値の 80% に達するまでの予測日
*** 特定の階層のアレイ上の物理ストレージ容量
*** メーカー、ファミリー、およびデータセンター別のストレージ容量
*** すべての階層のアレイにおけるストレージ利用率のトレンド
*** 利用率が最も高い上位 10 個のストレージシステム
*** ストレージプールのストレージ利用率のトレンド
*** 割り当て済みの容量
*** 割り当て可能な容量


** * File System Utilizationデータモデル*
+
ファイルシステム利用率に関する情報を回答 で確認できます。このデータモデルを使用すると、ファイルシステムレベルでホスト別の容量利用率を確認できます。管理者は、ファイルシステムごとの割り当て済み容量と使用済み容量、およびファイルシステムタイプを確認したり、ファイルシステムタイプ別のトレンドを特定したりできます。このデータモデルを使用すると、次の情報を回答で確認できます。

+
*** ファイルシステムのサイズ
*** データはどこに保管され、どのようにアクセスされるか（ローカル、 SAN など）。
*** ファイルシステム容量の過去の傾向は何ですか。そして、これに基づいて、将来のニーズにどのような対応を期待できますか？


** *内部ボリューム容量データモデル*
+
一定期間にわたる内部ボリュームの使用済み容量、割り当て済みの容量、および使用容量に関する回答の情報を確認できます。

+
*** 利用率が事前に定義されたしきい値を上回っている内部ボリューム
*** トレンドに基づいて容量が不足する危険がある内部ボリュームはどれですか？
*** 内部ボリュームの使用済み容量と割り当て済み容量の割合


** * Port Capacityデータモデル*
+
一定期間にわたるスイッチポートの接続、ポートのステータス、およびポートの速度に関する回答の情報を確認できます。次のような回答 の質問は、新しいスイッチの購入を計画するのに役立ちます。

+
*** （データセンター、スイッチベンダー、ポート速度に応じて）リソース（ポート）の可用性を予測するポート消費予測を作成するには、どうすればよいですか。
*** 容量不足になり、データ速度、データセンター、ベンダー、ホストポートとストレージポートの数が提供される可能性があるポートはどれですか？
*** 一定期間にわたるスイッチポートの容量のトレンド
*** ポートの速度
*** 必要なポート容量のタイプ、および特定のポートタイプまたはベンダーで容量が不足しそうな組織
*** いつまでに容量を購入して利用可能にするべきか


** * Qtree Capacityデータモデル*
+
一定期間にわたる qtree 利用率のトレンドを（使用済み容量と割り当て済み容量の比較などのデータを使用して）確認できます。さまざまなディメンション（ビジネスエンティティ、アプリケーション、階層、サービスレベルなど）別に情報を表示できます。このデータモデルを使用すると、次の情報を回答で確認できます。

+
*** アプリケーションまたはビジネスエンティティごとに設定されている制限値に対する qtree の使用済み容量
*** キャパシティプランニングを実施するための使用済み容量と空き容量のトレンド
*** 使用容量が最も多いビジネスエンティティ
*** 使用容量が最も多いアプリケーション


** * VM Capacityデータモデル*
+
仮想環境とその使用容量を報告できます。このデータモデルを使用すると、 VM とデータストアの一定期間にわたる使用容量の変化を報告できます。このデータモデルは、シンプロビジョニングと仮想マシンのチャージバックデータも提供します。

+
*** VM とデータストアにプロビジョニングされた容量に基づいて容量のチャージバックを決定する方法
*** VM で使用されていない容量、およびそのうちの空き容量、孤立している容量、その他の状態の容量
*** 消費傾向に基づいて何を購入する必要がありますか？
*** ストレージのシンプロビジョニングと重複排除のテクノロジを使用することで達成される Storage Efficiency による削減効果VM Capacity データモデルの容量は、仮想ディスク（ VMDK ）から取得されます。つまり、 VM Capacity データモデルを使用した場合の VM のプロビジョニング済みサイズは、その VM の仮想ディスクのサイズです。これは、OnCommand Insight の[Virtual Machines]ビューに表示されるプロビジョニング済み容量とは異なります。この容量には、VM自体のプロビジョニング済みサイズが表示されます。


** *ボリューム容量データモデル*
+
環境内のボリュームのすべての要素を分析し、ベンダー、モデル、階層、サービスレベル、およびデータセンター別にデータを整理できます。孤立ボリューム、未使用ボリューム、および保護ボリューム（レプリケーションに使用）に関連する容量を表示できます。また、さまざまなボリュームテクノロジ（ iSCSI または FC ）を表示したり、アレイの仮想化の問題について仮想ボリュームと非仮想ボリュームを比較したりすることもできます。このデータモデルを使用すると、次のような回答の情報を確認できます。

+
*** 利用率が事前に定義されたしきい値を上回っているボリューム
*** 孤立ボリューム容量のデータセンターにおけるトレンド
*** 仮想化またはシンプロビジョニングされているデータセンター容量
*** レプリケーション用に予約する必要があるデータセンター容量




* *チャージバックデータモデル*
+
ストレージリソース（ボリューム、内部ボリューム、 qtree ）の使用済み容量と割り当て済み容量に関する回答の情報を確認できます。このデータモデルは、ストレージ容量のチャージバックとアカウンタビリティの情報をホスト、アプリケーション、およびビジネスエンティティ別に提供します。現在のデータと履歴データの両方が含まれます。レポートデータは、サービスレベルとストレージ階層で分類できます。

+
このデータモデルを使用すると、ビジネスエンティティで使用されている容量を検出することでチャージバックレポートを生成できます。このデータモデルでは、複数のプロトコル（ NAS 、 SAN 、 FC 、 iSCSI など）についてのレポートをまとめて作成できます。

+
** 内部ボリュームがないストレージの場合、チャージバックレポートにはボリューム別のチャージバックが表示されます。
** 内部ボリュームがあるストレージの場合：
+
*** ビジネスエンティティがボリュームに割り当てられている場合、チャージバックレポートにはボリューム別のチャージバックが表示されます。
*** ビジネスエンティティがボリュームではなく qtree に割り当てられている場合、チャージバックレポートには qtree 別のチャージバックが表示されます。
*** ビジネスエンティティがボリュームにも qtree にも割り当てられていない場合、チャージバックレポートには内部ボリュームが表示されます。
*** ボリューム別、 qtree 別、または内部ボリューム別のチャージバックを表示するかどうかは内部ボリュームごとに決定されるため、同じストレージプール内の別々の内部ボリュームで異なるレベルのチャージバックが表示される可能性があります。容量ファクトはデフォルトの期間後にパージされます。詳細については、 Data Warehouse のプロセスを参照してください。




+
Chargebackデータモデルを使用するレポートには、Storage Capacityデータモデルを使用するレポートと異なる値が表示されることがあります。

+
** ネットアップストレージシステムでないストレージアレイの場合、両方のデータモデルのデータは同じです。
** NetApp および Celerra のストレージシステムの場合、 Chargeback データモデルは（ボリューム、内部ボリューム、または qtree の） 1 つのレイヤを使用して料金を請求し、 Storage Capacity データモデルは（ボリュームと内部ボリュームの）複数のレイヤを使用して料金を加算します。


* *在庫データモデル*
+
ホスト、ストレージシステム、スイッチ、ディスク、テープなどのインベントリリソースに関する回答の質問にお答えします。 qtree 、クォータ、仮想マシンとサーバ、および汎用デバイスです。Inventory データモデルには、レプリケーション、 FC パス、 iSCSI パス、 NFS パス、および違反に関する情報を表示するサブマートが複数含まれています。Inventory データモデルには履歴データは含まれません。このデータマートを使用して回答 を実行できる質問には、次のようなものがあります。

+
** 所有しているアセットとその場所
** アセットの使用者
** 所有しているデバイスの種類と、デバイスのコンポーネントを教えてください。
** OS あたりのホスト数とホスト上のポート数
** 各データセンターには、ベンダーごとにどのようなストレージアレイがありますか。
** 各データセンターには、ベンダーあたりいくつのスイッチがありますか。
** ライセンスが設定されていないポートの数
** どのベンダーのテープを使用していますか。また、各テープにはポートがいくつありますか。
** レポートの作成を開始する前に、すべての汎用デバイスが識別されていますか。
** ホストとストレージボリュームまたはテープ間のパス
** 汎用デバイスとストレージボリュームまたはテープ間のパス
** データセンターごとの各タイプの違反数
** レプリケートされた各ボリュームの、ソースボリュームとターゲットボリューム
** Fibre Channel ホストの HBA とスイッチとの間にファームウェアの互換性の問題またはポート速度の不一致があるか


* *パフォーマンスデータモデル*
+
ボリューム、アプリケーションボリューム、内部ボリューム、スイッチ、アプリケーションのパフォーマンスに関する回答の質問に回答できます。 VM 、 VMDK 、 ESX と VM 、ホスト、およびアプリケーションノードです。このデータモデルを使用すると、回答に複数のタイプのパフォーマンス管理に関する情報を記載したレポートを作成できます。

+
** 特定の期間に使用またはアクセスされていないボリュームまたは内部ボリューム
** アプリケーション用のストレージ（未使用）に関する潜在的な構成ミスを特定できるか？
** アプリケーションの全体的なアクセス動作パターン
** 特定のアプリケーションに階層型ボリュームが適切に割り当てられているか
** アプリケーションのパフォーマンスに影響を与えずに、実行中のアプリケーションに安価なストレージを使用できますか？
** 現在設定されているストレージへのアクセスが多いアプリケーションスイッチパフォーマンスのテーブルを使用すると、次の情報を取得できます。
** 接続されたポート経由でホストトラフィックが分散されているか。
** 多数のエラーが発生しているスイッチまたはポート
** ポートパフォーマンスに基づいて最も使用されているスイッチはどれですか？
** 使用率の低いスイッチのうち、ポートのパフォーマンスに基づくものは何ですか。
** ポートのパフォーマンスに基づくホストのトレンド分析スループット
** 特定の 1 つのホスト、ストレージシステム、テープ、またはスイッチの過去 X 日間のパフォーマンス利用率
** 特定のスイッチでトラフィックを生成しているデバイス（たとえば、利用率の高いスイッチを使用しているデバイス）
** 環境内の特定のビジネスユニットのスループットディスクパフォーマンスのテーブルを使用すると、次の情報を取得できます。
** ディスクのパフォーマンスデータに基づく、指定されたストレージプールのスループット
** 最も使用されているストレージプール
** 特定のストレージのディスク利用率の平均
** ディスクパフォーマンスデータに基づくストレージシステムまたはストレージプールの使用状況のトレンド
** 特定のストレージプールのディスク使用率のトレンドVM と VMDK のパフォーマンスのテーブルを使用すると、次の情報を取得できます。
** 仮想環境のパフォーマンスが最適化されているか
** 最も高いワークロードを報告している VMDK
** 異なるデータストアにマッピングされた VM から報告されたパフォーマンスを使用して、階層化の再決定を行うにはどうすればよいですか。パフォーマンスデータモデルには、階層の妥当性、アプリケーション用のストレージの構成ミス、およびボリュームと内部ボリュームの最終アクセス時刻を特定するための情報が含まれています。このデータモデルは、応答時間、 IOPS 、スループット、保留中の書き込み数、アクセスステータスなどのデータを提供します。


* * Storage Efficiencyデータモデル*
+
一定期間にわたるストレージの削減率と可能性を追跡できます。このデータモデルには、プロビジョニング済み容量のデータだけでなく、使用済みまたは消費済みの容量（物理的な測定値）も格納されます。たとえば、シンプロビジョニングが有効な場合、OnCommand Insight はデバイスから取得された容量を示します。また、このモデルを使用して、重複排除が有効な場合の効率を判断することもできます。Storage Efficiency データマートを使用すると、回答に関するさまざまな情報を確認できます。

+
** シンプロビジョニングと重複排除を実装した場合の Storage Efficiency による削減効果
** データセンター全体でのストレージ削減量
** 過去の容量のトレンドに基づいて、ストレージを追加購入する必要があるのはいつですか？
** シンプロビジョニングや重複排除などのテクノロジを有効にした場合の容量の増加
** ストレージ容量にリスクがありますか？



