---
permalink: reporting/reporting-user-roles.html 
sidebar: sidebar 
keywords:  
summary: 各ユーザアカウントには、一連の権限を持つロールが割り当てられます。ユーザーの数は、各ロールに関連付けられているReportingライセンスの数によって制限されます。 
---
= Reportingユーザのロール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各ユーザアカウントには、一連の権限を持つロールが割り当てられます。ユーザーの数は、各ロールに関連付けられているReportingライセンスの数によって制限されます。

各ロールで実行できる操作は次のとおりです。

* *受信者*
+
OnCommand Insight Reportingポータルのレポートを表示し、言語やタイムゾーンなどの個人設定を設定します。

+
[NOTE]
====
受信者は、レポートの作成、レポートの実行、レポートのスケジュール設定、レポートのエクスポート、および管理タスクの実行を行うことはできません。

====
* *ビジネスコンシューマ*
+
レポートを実行し、すべての受信者オプションを実行します。

* *ビジネス著者*
+
Business Consumerのすべてのオプションに加えて、スケジュールされたレポートの表示、対話形式でのレポートの実行、ストーリーの作成が可能です。

* * Pro Author *
+
Business Authorのすべてのオプションの実行に加えて、レポートの作成、パッケージおよびデータモジュールの作成を行います。

* *管理者*
+
レポート定義のインポートとエクスポート、レポートの設定、データソースの設定、レポートタスクのシャットダウンと再開など、レポート管理タスクを実行します。



次の表に、各ロールの権限と許可される最大ユーザ数を示します。

|===


| フィーチャー（ Feature ） | 受信者 | ビジネスパーソン | 著作家 | 作者プロ | 管理 


 a| 
[ チームコンテンツ ] タブでレポートを表示します
 a| 
はい。
 a| 
はい。
 a| 
はい。
 a| 
はい。
 a| 
はい。



 a| 
レポートを実行する
 a| 
いいえ
 a| 
はい。
 a| 
はい。
 a| 
はい。
 a| 
はい。



 a| 
レポートのスケジュールを設定する
 a| 
いいえ
 a| 
はい。
 a| 
はい。
 a| 
はい。
 a| 
はい。



 a| 
外部ファイルをアップロードします
 a| 
いいえ
 a| 
いいえ
 a| 
はい。
 a| 
はい。
 a| 
いいえ



 a| 
ストーリーを作成します
 a| 
いいえ
 a| 
いいえ
 a| 
はい。
 a| 
はい。
 a| 
いいえ



 a| 
レポートを作成します
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ
 a| 
はい。
 a| 
いいえ



 a| 
パッケージとデータモジュールを作成します
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ
 a| 
はい。
 a| 
いいえ



 a| 
管理タスクを実行
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ
 a| 
はい。



 a| 
ユーザ数
 a| 
OnCommand Insight ユーザの数
 a| 
20
 a| 
2.
 a| 
1.
 a| 
1.

|===
Data WarehouseとReportingの新しいユーザを追加したときにロールの制限を超えたユーザが「非アクティブ化」として追加されます。新しいユーザにメンバーシップを付与するには、そのロールを持つ別のユーザを非アクティブ化するか削除する必要があります。

[NOTE]
====
レポートオーサリング機能を使用するにはInsight Planのライセンスが必要です。Business AuthorユーザとPro Authorユーザを追加するには、ARAP（Additional Report Authoring Package）を購入します。詳細については、OnCommand Insight の担当者にお問い合わせください。

====
Reportingユーザのロールは、データベースへの直接アクセスには影響しません。Reportingユーザのロールは、データマートを使用してSQLクエリを作成する機能には影響しません。
