---
permalink: reporting/reporting-made-easy.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight Reportingポータルから事前定義済みのレポートを生成したり、他のユーザにEメールで送信したり、変更したりできます。複数のレポートを使用して、デバイス、ビジネスエンティティ、または階層でフィルタリングできます。このレポートツールは、 IBM Cognos をベースとしたツールで、さまざまなデータ表示オプションが用意されています。 
---
= レポート作成が容易に
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight Reportingポータルから事前定義済みのレポートを生成したり、他のユーザにEメールで送信したり、変更したりできます。複数のレポートを使用して、デバイス、ビジネスエンティティ、または階層でフィルタリングできます。このレポートツールは、 IBM Cognos をベースとしたツールで、さまざまなデータ表示オプションが用意されています。

* OnCommand Insight の事前定義済みレポートには、インベントリ、ストレージ容量、チャージバック、パフォーマンス、ストレージ効率、 クラウドのコストデータを削減できます。これらの事前定義済みレポートを変更して、変更内容を保存できます。


使用可能なレポートデータは、次のようないくつかの要素によって制御されます。

* ロールごとに定義されるOnCommand Insight Reportingポータルにログインします。
* レポートのデータを格納するOnCommand InsightData Warehouseのセットアップ。


HTML 、 PDF 、 CSV 、 XML などのさまざまな形式でレポートを生成できます。 Excel などです。

OnCommand Insight では、ユーザをビジネスユニットに関連付けることで、Reportingでマルチテナンシーを実現できます。この機能を使用すると、管理者は、ユーザーまたは所属先の属性に従ってデータまたはレポートを分離できます。

[NOTE]
====
Cognosバージョン11.1.2以降では、レポートURLは「安定している」とはみなされず、変更される場合があります。ブックマークされたレポートURLがある場合、これらのブックマークは失敗する可能性があります。詳細については、次のサイトを参照してください。 http://queryvision.com/ibm-analytics-11-x-urls-they-are-a-changing/[]

====
[NOTE]
====
OnCommand Insight では、新しいデータモジュール機能を使用しないかぎり、IBM Cognosのパッケージを使用して作成されたダッシュボードはサポートされません。

====