---
permalink: reporting/which-report-answers-your-question.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight には、レポート作成に関する一般的な要件に対応する事前定義済みのレポートが用意されており、関係者がストレージインフラに関する十分な情報に基づいて意思決定を行うために必要な重要な分析情報を得ることができます 
---
= 事前定義済みのレポートを使用した回答に関する一般的な質問への
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight には、レポート作成に関する一般的な要件に対応する事前定義済みのレポートが用意されており、関係者がストレージインフラに関する十分な情報に基づいて意思決定を行うために必要な重要な分析情報を得ることができます

以下の事前定義されたレポートは、*チームコンテンツ*>*レポート*または*チームコンテンツ*>*ベンダー固有のレポート*で使用できます。

NetApp Storage Automation Storeでは、新しいバージョンのレポートを入手できる場合があります。Automation Storeで定期的にレポートを確認する必要があります。

* * AWSクラウドのコストデータ*
+
クラウドコストレポートにはすべての資産がまとめて表示されるため、環境内で動的に拡張されるクラウドベースサービスとオンプレミスサービスの使用状況とコストを追跡、分析、最適化できます。

+
このレポートでは、インフラとコストの相関関係を示し、明確で実用的なレポートを提供して、集中的なキャパシティプランニングと廃棄物の検出を通じて適切なサイジングを確実に行うことができます。

* *アプリケーションサービスレベルの容量とパフォーマンス*
+
Application Service Level Capacity and Performance レポートには、アプリケーションの概要が表示されます。この情報は、キャパシティプランニングや移行計画に使用できます。

* *チャージバック*
+
Chargeback レポートには、ストレージ容量のチャージバックとアカウンタビリティの情報がホスト、アプリケーション、およびビジネスエンティティ別に表示され、現在のデータと履歴データの両方が含まれます。

+
データが二重に収集されないようにするために、 ESX サーバを対象から除外し、 VM のみを監視してください。

+
このレポートの最新版は、 NetApp Storage Automation Store から入手できます。

* *データソース*
+
Data Sources レポートには、サイトにインストールされているすべてのデータソース、データソースのステータス（ success / failure ）、およびステータスメッセージが表示されます。このレポートには、データソースのどこで問題が発生したかに関する情報が記載されていますデータソースが正しく機能しないと、Insightでのレポートの精度と製品の一般的な操作性に影響します。

* * ESXとVMのパフォーマンス*
+
ESX と VM のパフォーマンス比較レポートには、 ESX サーバと VM の平均および最大の IOPS 、スループット、レイテンシ、利用率が表示されます。データが二重に収集されないようにするために、 ESX サーバを対象から除外し、 VM のみを監視してください。

+
このレポートの最新版は、 NetApp Storage Automation Store から入手できます。

* *ファブリックの概要*
+
Fabric Summary レポートには、ポート数、ファームウェアバージョン、ライセンスステータスなど、スイッチとスイッチの情報が表示されます。このレポートには NPV スイッチポートは含まれません。

* *ホストHBA *
+
Host HBAs レポートには、環境内のホストの概要と、 HBA のベンダー、モデル、ファームウェアバージョン、および HBA が接続されているスイッチのファームウェアレベルが表示されます。このレポートを使用して、スイッチまたは HBA のファームウェアのアップグレードを計画する際にファームウェアの互換性を分析できます。

* *ホストのサービスレベルの容量とパフォーマンス*
+
Host Service Level Capacity and Performance レポートには、ブロック専用アプリケーションのホスト別のストレージ利用率の概要が表示されます。

* *ホストの概要*
+
Host Summary レポートには、選択した各ホストのストレージ利用率の概要と、 Fibre Channel ホストおよび iSCSI ホストの情報が表示されます。このレポートを使用して、ポートとパス、 Fibre Channel と iSCSI の容量、および違反数を比較できます。

* *ライセンスの詳細*
+
License Details レポートには、すべてのサイトで、ライセンスが付与されているリソースの数が表示されます。このレポートには、すべてのサイトでの実際のライセンス数の合計も表示されます。この合計には、複数のサーバで管理されるストレージアレイが重複してカウントされることがあります。

* *マッピングされているがマスクされていないボリューム*
+
Mapped but not Masked Volumes レポートには、 LUN は特定のホストにマッピングされているが、そのホストに対してマスクされていないボリュームが表示されます。このようなボリュームは、マスクが解除された、運用を終了した LUN である可能性があります。マスクされていないボリュームにはどのホストからもアクセスできるため、データが破損しやすくなります。

* *ネットアップの容量とパフォーマンス*
+
NetApp Capacity and Performance レポートには、割り当て済み容量、使用済み容量、コミット済み容量のグローバルデータ、および容量のトレンドとパフォーマンスデータが表示されます。

* * OCIスコアカード*
+
OCIスコアカードレポートには、OnCommand Insight によって検出されたすべてのアセットの概要と一般的なステータスが表示されます。ステータスは、緑色、黄色、赤色のフラグで示されます。

+
** 緑は正常な状態を示します
** 黄色は、環境内に潜在的な問題があることを示します
** 赤は、注意が必要な問題 を示します。レポートのすべてのフィールドは、レポートに付属のデータディクショナリに記載されています。


* *ストレージの概要*
+
Storage Summary レポートには、 raw 、割り当て済み、ストレージプール、およびボリュームについて、使用済み容量と未使用の容量のデータの概要が表示されます。このレポートは、検出されたすべてのストレージの概要を示します。

+
このレポートの新しいバージョンは、NetApp Storage Automation Storeで入手できます。

* * VMの容量とパフォーマンス*
+
仮想マシン（ VM ）環境とその使用容量が表示されます。VM の電源がオフになっている場合など、一部のデータを表示するには、 VM ツールを有効にする必要があります。

* * VMパス*
+
VM Paths レポートは、仮想マシンが実行されているホスト、どのホストがどの共有ボリュームにアクセスしているか、アクティブなアクセスパスが何であるか、および容量の割り当てと使用量がどのようなものであるかについて、データストアの容量データとパフォーマンスの指標を提供します。

* *シンプール別のHDS容量*
+
HDS Capacity by Thin Pool レポートには、シンプロビジョニングされたストレージプールで使用可能な容量が表示されます。

* *アグリゲート別のネットアップ容量*
+
NetApp Capacity by Aggregate レポートには、アグリゲートの合計 raw スペース、合計スペース、使用済みスペース、使用可能なスペース、およびコミット済みスペースが表示されます。

* *シック・アレイ別のSymmetrix容量*
+
Symmetrix Capacity by Thick Array レポートには、 raw 容量、使用可能な容量、空き容量、マッピングされた容量、マスクされた容量が表示されます。 合計空き容量を確認します。

* *シン・プール別のSymmetrix容量*
+
Symmetrix Capacity by Thin Pool レポートには、 raw 容量、使用可能な容量、使用済み容量、空き容量、使用済みの割合が表示されます。 サブスクライブ済み容量およびサブスクリプション率：

* *アレイ別のXIV容量*
+
XIV Capacity by Array レポートには、アレイの使用済み容量と未使用の容量が表示されます。

* *プール別のXIV容量*
+
XIV Capacity by Pool レポートには、ストレージプールの使用済み容量と未使用の容量が表示されます。


