---
permalink: install-windows/downloading-the-installation-packages.html 
sidebar: sidebar 
keywords:  
summary: アップグレードを選択する前に、Insight、Data Warehouse、およびRemote Acquisition Unit（該当する場合）のインストールパッケージをダウンロードしておく必要があります。パッケージ\（.msiファイル\）のダウンロード時間は、使用可能な帯域幅によって異なります。 
---
= OnCommand Insight インストールパッケージのダウンロード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードを選択する前に、Insight、Data Warehouse、およびRemote Acquisition Unit（該当する場合）のインストールパッケージをダウンロードしておく必要があります。パッケージのダウンロード時間 (`.msi` ファイル）は、使用可能な帯域幅によって異なります。



== このタスクについて

インストールパッケージは、Insight Web UIを使用するか、から該当するOnCommand Insight のリンクに移動してダウンロードできます http://support.netapp.com/NOW/cgi-bin/software[]。

Insight Serverからインストールパッケージをダウンロードするには、次の手順を実行します。



== 手順

. Webブラウザを開き、次のいずれかを入力してInsight Web UIを開きます。
+
** Insight Serverで、次の作業を行います。 `+https://localhost+`
** 任意の場所から： `+https://IP Address:port or fqdn:port+`
+
ポート番号は443か、Insight Serverのインストール時に設定したポートです。URLでポート番号を指定しない場合、ポート番号はデフォルトで443になります。



. Insightにログインします。
. [ヘルプ]アイコンをクリックし、*[アップデートの確認]*を選択します。
. 新しいバージョンが検出された場合は、メッセージボックスの指示に従います。
+
新しいバージョンのInsightDescriptionページに移動します。

. 概要 *ページで* Continue *をクリックします。
. エンドユーザライセンス契約（EULA）が表示されたら、*[同意する]*をクリックします。
. 各コンポーネント（Insight Server、Data Warehouse、Remote Acquisition Unitなど）のインストールパッケージのリンクをクリックし、*[名前を付けて保存]*をクリックしてインストールパッケージを保存します。
+
アップグレードの前に、Data WarehouseとRemote Acquisition Unitのインストールパッケージを、それぞれのサーバのローカルディスクにコピーしておく必要があります。

. [チェックサム]*をクリックし、各インストールパッケージに関連付けられている数値を書き留めます。
. ダウンロードしたインストールパッケージが完了し、エラーが発生していないことを確認します。
+
ファイル転送が不完全な場合、アップグレードプロセスで原因 の問題が発生する可能性があります。

+
インストールパッケージのMD5ハッシュ値を生成するには、Microsoftのようなサードパーティのユーティリティを使用しますlink:HTTP://SUPPORT.MICROSOFT.COM/KB/841290["File ChecksumIntegrity Verifierの略"] ユーティリティ。


