---
permalink: install-windows/insight-upgrade-checklist.html 
sidebar: sidebar 
keywords: 6.4 
summary: 提供されるチェックリストを使用して、アップグレードの準備中に進捗を記録できます。これらのタスクは、アップグレードが失敗するリスクを軽減し、リカバリとリストアの作業を迅速に行うことを目的としています。 
---
= OnCommand Insight のアップグレードチェックリスト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
提供されるチェックリストを使用して、アップグレードの準備中に進捗を記録できます。これらのタスクは、アップグレードが失敗するリスクを軽減し、リカバリとリストアの作業を迅速に行うことを目的としています。



== アップグレード準備のチェックリスト（必須）

|===


| 条件 | 完了? 


 a| 
すべてのInsight Serverに対して、アップグレードプロセスを実行するために必要なWindowsのローカル管理者権限があることを確認します。
 a| 



 a| 
Insight、Data Warehouse、またはRemote Acquisition Unitのサーバを32ビットプラットフォームにアップグレードする場合は、64ビットプラットフォームにアップグレードする必要があります。Insight 7.x以降では、64ビットプラットフォームでのみアップグレードできます。
 a| 



 a| 
環境内のすべてのサーバでウィルス対策ソフトウェアを変更または無効にするために必要な権限があることを確認します。ウィルススキャンソフトウェアがアクティブな場合に発生するアップグレードの失敗を回避するには、Insightのインストールディレクトリを除外する必要があります (`disk drive:\install directory\sanscreen` アップグレード中のウィルススキャンへのアクセスを許可します。すべてのコンポーネントをアップグレードしたら、ウィルス対策ソフトウェアを再アクティブ化してかまいません。ただし、Insightのインストールディレクトリについては、スキャンからすべて除外するように設定してください。

また、インストール後に、IBM/DB2フォルダ（例：_C：\Program Files\IBM\DB2_）をアンチウィルススキャンから除外する必要があります。
 a| 

|===


== アップグレード準備のチェックリスト（ベストプラクティス）

|===


| 条件 | 完了? 


 a| 
ほとんどのアップグレードには4～8時間以上かかり、大企業では時間がかかることを考慮して、いつアップグレードするかを計画します。アップグレードにかかる時間は、使用可能なリソース（アーキテクチャ、CPU、およびメモリ）、データベースのサイズ、環境内の監視対象オブジェクトの数によって異なります。
 a| 



 a| 
アップグレードプランについてアカウント担当者に問い合わせ、インストールされているInsightのバージョンとアップグレードするバージョンを伝えます。
 a| 



 a| 
Insight、Data Warehouse、およびRemote Acquisition Unitに現在割り当てられているリソースが、引き続き推奨される仕様を満たしていることを確認します。すべてのサーバーの推奨サイジングガイドラインを参照してください。または、アカウント担当者に連絡してサイジングガイドラインについて相談することもできます。
 a| 



 a| 
データベースのバックアップとリストアのプロセスに十分なディスクスペースがあることを確認してください。バックアッププロセスとリストアプロセスには、InsightサーバとData Warehouseサーバでバックアップファイルに使用されているディスクスペースの約5倍が必要です。たとえば、50GBのバックアップには、250~300GBの空きディスクスペースが必要です。
 a| 



 a| 
InsightおよびData Warehouseのデータベースをバックアップするときは、Firefox®またはChrome™ブラウザにアクセスできることを確認してください。4GBを超えるファイルをアップロードおよびダウンロードするときに問題が発生するため、Internet Explorerは推奨されません。
 a| 



 a| 
を削除します `.tmp` Insight Serverのファイル。次の場所にあります。 `<install directory>\SANscreen\wildfly\standalone\tmp`。
 a| 



 a| 
重複するデータソースと運用停止されたデータソースをInsight Clientから削除します。運用が停止されたデータソースや重複したデータソースを削除すると、アップグレードの実行に必要な時間が短縮され、データ破損の可能性が軽減されます。
 a| 



 a| 
Insightに付属のデフォルトのレポートに変更を加えた場合は、変更したレポートがシステムのアップグレードまたはリストア時に失われないように、別の名前で[Customer Reports]フォルダに保存してください。
 a| 



 a| 
自分でまたはプロフェッショナルサービスで作成したカスタムのData Warehouseレポートがある場合は、XML形式でエクスポートして[Customer Reports]フォルダに移動し、バックアップを作成します。バックアップがData Warehouseサーバに配置されていないことを確認します。レポートを推奨フォルダに移動しないと、アップグレードプロセスでバックアップされない可能性があります。以前のバージョンのInsightでは、レポートを適切なフォルダに配置しないと、カスタムレポートや変更したレポートが失われる可能性があります。
 a| 



 a| 
IBM Cognos Configurationユーティリティの設定はData Warehouseのバックアップには含まれないため、すべての設定を記録しておきます。これらの設定はアップグレード後に再設定する必要があります。ユーティリティはにあります `disk drive:\install directory\SANscreen\cognos\c10_64\bin64` Data Warehouseサーバ上のディレクトリ（を使用して実行） `cogconfigw` コマンド。または、Cognosの完全なバックアップを実行し、すべての設定をインポートすることもできます。詳細については、IBM Cognosのドキュメントを参照してください。
 a| 

|===


== アップグレード準備のチェックリスト（該当する場合）

|===


| 条件 | 完了? 


 a| 
ブラウザに表示されるセキュリティ警告を原因として、Insightのインストール時に作成された自己署名証明書を内部の認証局によって署名された証明書に置き換えた場合は、にあるキーストアファイルをバックアップします。 `disk drive:\install directory\SANscreen\wildfly\standalone\configuration` アップグレード後にリストアします。これにより、Insightで作成された自己署名証明書が自己署名証明書で置き換えられます。
 a| 



 a| 
環境に合わせて変更したデータソースがあり、変更内容がアップグレード後のInsightバージョンで有効かどうか不明な場合は、リカバリで問題が発生した場合にトラブルシューティングできるように、次のディレクトリのコピーを作成しておきます。 `disk drive:\install directory\SANscreen\wildfly\standalone\deployments\datasources.war`。
 a| 



 a| 
を使用して、すべてのカスタムデータベーステーブルおよびビューをバックアップします `mysqldump` コマンドラインツールカスタムデータベーステーブルを復元するには、特権データベースアクセスが必要です。これらのテーブルのリストアについては、テクニカルサポートにお問い合わせください。
 a| 



 a| 
カスタムの統合スクリプト、Insightデータソースに必要なサードパーティコンポーネント、バックアップなど、必要なデータがに保存されていないことを確認します `disk drive:\install directory\sanscreen` ディレクトリ。このディレクトリの内容はアップグレードプロセスによって削除されるためです。これらをから移動したことを確認してください `\sanscreen` ディレクトリを別の場所に移動します。たとえば、カスタムの統合スクリプトが環境に含まれている場合は、次のファイルを以外のディレクトリにコピーしてください `\sanscreen` ディレクトリ：

`\install_dir\SANscreen\wildfly\standalone\deployments\datasources.war\new_disk_models.txt`。
 a| 

|===