---
permalink: install-windows/installing-the-oncommand-insight-server.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight サーバは、OnCommand Insight セットアップウィザードを使用して簡単にインストールできます。 
---
= OnCommand Insight サーバをインストールしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight サーバは、OnCommand Insight セットアップウィザードを使用して簡単にインストールできます。



== 作業を開始する前に

インストールの前提条件をすべて満たしておく必要があります。


NOTE: OnCommand Insightをアップグレードする場合は、現在のバージョンをアンインストールまたはアップグレードする前に*ボルトをバックアップする必要があります。



== 手順

. 管理者権限があるアカウントでInsight Serverにログインします。
. Windowsエクスプローラを開き、インストールファイルが保存されているディレクトリに移動します。
. をダブルクリックします `.MSI` ダウンロードしたファイル。
. 「 * 次へ * 」をクリックして続行します。
. ライセンス契約を読み、*[I accept the terms in the License Agreement]*チェックボックスをオンにして、*[Next]*をクリックします。
. [Customer Information]ウィンドウに顧客名とサイト名を入力し、*[Next]*をクリックします。
+
*ベストプラクティス：*サイトのプレフィックスとしてお客様名を使用します（例：NetApp）。

. 管理者パスワードを入力します。パスワードを確認します。
. [お客様情報：NetApp ASUPの設定]*ウィンドウで、次の手順を実行します。
+
.. 次のいずれかのオプションを選択して、ASUPにアップロードするデータが格納されているデータベースを選択します。
+
*** *データベースバックアップなし*：バックアップはASUPに送信されません。
*** *パフォーマンスデータなしのバックアップ*：バックアップを作成してASUPに送信しますが、パフォーマンスデータは含まれません。
*** *パフォーマンスデータを使用したバックアップ*：パフォーマンスデータを含むバックアップが作成されますが、大量のデータが生成される可能性があります `*.gz` ファイル。




+
[NOTE]
====
ASUPはHTTPSプロトコルを使用して配信されます。

====
+
.. [ログ]*で、データソースを記録するログなし、ベースログ、拡張ログのいずれかを選択します。
.. 「 * 次へ * 」をクリックします。


. Insightの消費ライセンスモデルを使用している場合は、[使用状況情報を送信する]*セクションの*[使用状況情報をネットアップに送信する]*チェックボックスをオンにする必要があります。
. 「 * 次へ * 」をクリックします
. [サーバの設定]ウィンドウで、OnCommand Insight サーバを設定するための適切な設定パラメータを選択または設定します。
+
|===


| オプション | 説明 


 a| 
ポータルポート（HTTP）
 a| 
ユーザのWebサービス（管理タスクを実行するためのポータルなど）をサポートするためにOnCommand Insight サーバで使用されるポート。デフォルト（80）を使用します。ただし、デフォルトポートが使用中の場合は、別のポートに変更します。



 a| 
ポータルポート（HTTPS）
 a| 
Remote Acquisition Unitで、セキュアなチャネル経由でOnCommand Insight サーバにSAN変更情報を送信するために使用するポート。デフォルト（443）を使用します。ただし、デフォルトポートが使用中の場合は、別のポートに変更します。RAUの設定時に同じポート番号を指定します。



 a| 
内部データベースポート（SQL）
 a| 
OnCommand Insight サーバが実行されているPCによって内部的に使用されるポート。データベースへのアクセスポイントとして機能します。デフォルト（3306）を使用します。ただし、デフォルトポートが使用中の場合は、別のポートに変更します。

|===
. 「 * 次へ * 」をクリックします。
. 続行するには*[インストール]*をクリックしてください。
+
インストールには約20分かかります（インストールされているアプリケーションによって異なります）。

. [ 完了 ] をクリックします。
. Remote Acquisition Unit（RAU）をインストールする場合は、SecurityAdmin Toolを実行して_acquisition_userのパスワードを作成する必要があります。このパスワードは、RAUのインストール時に必要になります。
+
注:このパスワードを作成した場合は、以下に示すようにサーバーとRAUを同期する必要はありません。





== サーバをDWHおよびRAUと同期


IMPORTANT: Remote Acquisition UnitやData Warehouseのインストールが完了したら、RAU / DWHをOnCommand Insightサーバと同期する必要があります。以下の手順に従います。

link:../install-windows/installing-a-remote-acquisition-unit-rau.html#synchronize-server-and-rau["サーバとRAUの同期（Windows）"]

link:../install-windows/installing-the-oncommand-insight-data-warehouse-and-reporting.html#synchronize-server-and-dwh["サーバとDWHの同期（Windows）"]

link:../install-linux/installing-a-remote-acquisition-unit-rau-linux.html#synchronize-server-and-rau["サーバとRAUの同期（Linux）"]

link:../install-linux/installing-oncommand-insight-data-warehouse-linux.html#synchronize-server-and-dwh["サーバとDWHの同期（Linux）"]
