---
permalink: install-windows/installing-a-remote-acquisition-unit-rau.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 環境に1つ以上のRAUをインストールします。 
---
= Remote Acquisition Unit（RAU）のインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 環境に1つ以上のRAUをインストールします。



== 作業を開始する前に

インストールの前提条件をすべて満たしておく必要があります。

変更情報をサーバに転送するには、少なくとも1つのポートが開いていて、RAUサーバとOnCommand Insight サーバの間で使用可能である必要があります。不明な場合は、RAUコンピュータでWebブラウザを開き、OnCommand Insight サーバに移動して検証します。

[listing]
----
 https://< OnCommand Insight Server hostname >:< acquisition_port >
----
Acquisitionのデフォルトポートは443ですが、サーバのインストール時に変更されている可能性があります。接続に成功すると、OnCommand Insight 応答ページが表示され、RAUとOnCommand Insight サーバの間でポートが開いて使用可能になったことが示されます。



== 手順

. 管理者権限があるアカウントでRAUサーバにログインします。
. エクスプローラを開き、RAUインストールファイルが格納されているディレクトリに移動します。
. をダブルクリックします `.MSI` ファイルをクリックしてインストールを開始します。
. [次へ]*をクリックして、ライセンス契約のウィンドウに進みます。これを読んでライセンス契約の条項に同意し、*[次へ]*をクリックします。
. RAUをローカルハードドライブにインストールするか、機能全体をローカルハードドライブにインストールするかを選択します。（[Disk Usage]リンクをチェックして、十分なスペースがあることを確認できます。116MBが必要です）。 [次へ]*をクリックします。
. [構成]ウィンドウで、サイトに固有の次のパラメータを設定します。
+
** * OnCommand Insight **サーバー名またはアドレス*- OnCommand Insight サーバーを識別するホスト名またはIPアドレス。RAUはこの名前/ IPを使用してサーバとの通信リンクを開きます。ホスト名を指定する場合は、DNSで解決できることを確認してください。
** * Acquisition Unit Name *- RAUを識別する一意の名前。
** * OnCommand Insight Secured Remote Acquisition Port（HTTPS）*- Remote Acquisition Unitが環境の変更情報をOnCommand Insight サーバに送信するために使用するポート。この設定は、OnCommand Insight サーバのインストール時に入力した値と一致し、すべてのRAUで同じである必要があります。


. 選択内容を確認します。前に戻って変更を行うには、*[戻る]*をクリックします。「 * 次へ * 」をクリックします。
. [インストール]*をクリックしてインストールを開始します。
+
インストールが完了するまで待ちます。この処理には約5～10分かかります。





== 完了後

インストールが完了すると、最後のウィンドウが表示されます。[Start Remote Acquisition Service]*ボックスをクリックしてRAUを開始し、[Finish]*をクリックしてこの処理を終了します。
