---
permalink: install-windows/installing-data-source-patches.html 
sidebar: sidebar 
keywords:  
summary: 該当する場合は、最新の機能と拡張機能を活用するために、データソース用の最新のパッチをインストールする必要があります。データソースパッチをアップロードしたら、同じタイプのすべてのデータソースにインストールできます。 
---
= データソースパッチをインストールしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
該当する場合は、最新の機能と拡張機能を活用するために、データソース用の最新のパッチをインストールする必要があります。データソースパッチをアップロードしたら、同じタイプのすべてのデータソースにインストールできます。



== 作業を開始する前に

テクニカルサポートに連絡してを入手しておく必要があります `.zip` 最新のデータソースパッチを含むファイル。アップグレード前のバージョンとアップグレード後のバージョンを提供します。



== 手順

. パッチファイルをInsight Serverに配置します。
. Insightのツールバーで、*[Admin]*をクリックします。
. [パッチ]*をクリックします。
. [Actions]ボタンから、*[Apply patch]*を選択します。
. [Apply data source patch]*ダイアログボックスで、*[Browse]*をクリックして、アップロードしたパッチファイルを指定します。
. [パッチ名]*、*[概要 ]*、*[影響を受けるデータソースタイプ]*を確認します。
. 選択したパッチが正しい場合は、*パッチの適用*をクリックします。
+
同じタイプのすべてのデータソースがこのパッチで更新されます。データソースを追加すると、データ収集が自動的に再開されます。ノードやインターフェイスの追加や削除など、ネットワークトポロジの変更も検出されます。

. 検出プロセスを手動で強制的に実行するには、*[Data Sources]*をクリックし、データソースの横にある*[Poll Again]*をクリックして、データの収集をただちに強制します。
+
データソースがすでに取得プロセス中の場合、再ポーリング要求は無視されます。


