---
permalink: install-windows/installing-the-anomaly-detection-software.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight には、Insightデータに機械学習の異常検出を適用するソフトウェアが含まれています。このソフトウェアは、他のOnCommand Insight コンポーネントとは別にインストールできます。 
---
= 異常検出ソフトウェアをインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight には、Insightデータに機械学習の異常検出を適用するソフトウェアが含まれています。このソフトウェアは、他のOnCommand Insight コンポーネントとは別にインストールできます。



== 作業を開始する前に

インストールの前提条件をすべて満たしておく必要があります。



== 手順

. sudo権限があるアカウントで異常検出サーバにログインします。
. をコピーします `.zip` ファイルをLinuxサーバに送信します。
. にファイルを展開します `oci-prelert-<version>-linux-x86_64` ディレクトリ。
. インストーラが格納されているディレクトリに移動します。 `cd oci-prelert-<version>-linux-x86_64`
. 異常検出ソフトウェアをインストールします。 `sudo ./oci-prelert-install.sh`
+
インストール中に、OnCommand Insight サーバのサーバ名またはIPアドレス、および管理者権限を持つアカウントのユーザ名とパスワードを入力するように求められます。

+
異常検出ソフトウェアを削除するには、次のコマンドを使用します。 `sudo /usr/bin/oci-prelert-uninstall.sh`





== 結果

ソフトウェアは、インストールで指定されたOnCommand Insight のインスタンスに自動的に登録されます。ソフトウェアは、登録先のOnCommand Insight インスタンスとのみ通信でき、OnCommand Insight サーバに登録できるソフトウェアのインスタンスは1つだけです。

異常検出ソフトウェアを実行しているサーバまたはInsight Serverを再起動すると、異常検出プロセスが自動的に再開されます。

[NOTE]
====
インストール時にパラメータの入力を求められるのではなく、コマンドラインでパラメータを指定して異常検出ソフトウェアをインストールすると、次のパラメータを指定しないと、Insight Serverへの登録が失敗します。 `--path rest/v1`

====