---
permalink: install-windows/installing-an-ethernet-monitoring-unit-linux.html 
sidebar: sidebar 
keywords:  
summary: 「Ethernet Monitoring Unit（EMU）は、ホストからストレージリソースへのネットワークトラフィックに関するパフォーマンスのトラブルシューティングを可能にするために、環境内のネットワークパケットを調べます。 
---
= Ethernet Monitoring Unitのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ethernet Monitoring Unit（EMU）は、ホストからストレージリソースへのネットワークトラフィックに関するパフォーマンスのトラブルシューティングを可能にするために、環境内のネットワークパケットを検査します。



== 作業を開始する前に

[NOTE]
====
OnCommand Insight バージョン7.3.12以降では、イーサネット監視ユニット（EMU）はサポートされません。

====
インストールの前提条件をすべて満たしておく必要があります。



== 手順

. sudo権限があるアカウントでEMUサーバにログインします。
. インストールファイルが保存されているサーバー上のディレクトリに移動し、次のコマンドを入力します。
+
`unzip oci-ethernet-<version>-linux-x86_64.zip`

+
ここで `<version>` は、ダウンロードしたファイル名に指定されているバージョン番号です。

. の構文、コマンド引数、およびパラメータの使用方法を確認できます `oci-install.sh`：
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh --help`

. インストールスクリプトを実行します。
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh`

. ライセンス契約を読み、同意します。
. 回答 各プロンプトは次のとおりです。
+
** * OnCommand Insight **サーバー名またはIPアドレス*- OnCommand Insight サーバーを識別するホスト名またはIPアドレス。EMUは、この名前/ IPを使用してサーバとの通信リンクを開きます。ホスト名を指定する場合は、DNSで解決できることを確認してください。
** * Acquisition Unit Name *- EMUを識別する一意の名前。
** * OnCommand Insight セキュアリモート収集ポート（HTTPS）*- EMUが環境変更情報をOnCommand Insight サーバに送信するために使用するポート。この設定は、OnCommand Insight サーバのインストール時に入力した値と一致し、すべてのEMUで同じである必要があります。
** *イーサネットPAS出力ディレクトリ*- PAS出力用のフォルダを入力します。
** *監視するイーサネットPASインターフェイス*-トラフィックを監視するインターフェイスを入力します。
** *ジャンボパケットを有効にする*-お客様の環境でジャンボパケットを使用している場合、EMUはそれらのパケットを読み取るための大きなパケットバッファを作成します。それ以外の場合、EMUは標準イーサネットパケットに使用可能なメモリプールを使用します。すべてのプロンプトを回答 にすると、インストールが開始されます。所要時間は約10分です（インストールされているアプリケーションによって異なります）。



