---
permalink: install-windows/installation-prerequisites.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight をインストールする前に、現在のソフトウェアバージョンをダウンロードし、適切なライセンスを取得して、環境をセットアップする必要があります。 
---
= インストールの前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight をインストールする前に、現在のソフトウェアバージョンをダウンロードし、適切なライセンスを取得して、環境をセットアップする必要があります。

OnCommand Insight をインストールする前に、次のものがあることを確認してください。

* ダウンロードしたインストールパッケージに含まれている最新バージョンのOnCommand Insight ソフトウェアファイル
* ダウンロードしたOnCommand Insight バージョンを操作するためのライセンス
* 最小限のハードウェアおよびソフトウェア環境
+
現在の製品では、以前のバージョンのOnCommand Insight 製品では使用されていなかった追加のハードウェアリソース（OnCommand Insight 製品の機能強化のため）が消費される可能性があります。

* OnCommand Insight サーバ、Data WarehouseとReporting、およびRemote Acquisition Unitのハードウェアとネットワークの構成を含む導入計画。
* Java 8 - OnCommand Insight Java UI用。
+

NOTE: OnCommand Insight には、Java SE 8用のOracle有料ライセンスが含まれています。Java SE 8ライセンスを追加で購入する必要はありません。このライセンスでは、Java SE 8をすべてのOCIコンポーネントで使用できます。を参照してください link:legal-notices.html["通知"] ページを参照してください。

* ウィルススキャンソフトウェアを無効にしました
+
OnCommand Insight のインストール中に、すべてのウイルススキャナを完全に無効にする必要があります。インストール後、Insightコンポーネントで使用されるパス（インストール、バックアップ、およびアーカイブの各パス）をウィルススキャンから除外し、全体を除外する必要があります `sanscreen` スキャンからのディレクトリ。

+
また、インストール後に、IBM/DB2フォルダ（例：_C：\Program Files\IBM\DB2_）をアンチウィルススキャンから除外する必要があります。



[NOTE]
====
アップグレードまたは新しいハードウェアへの移行としてフルインストールを実行し、既存のシステムにデフォルト以外のセキュリティ設定が含まれている場合は、インストールを実行する前にセキュリティ設定をバックアップする必要があります。インストールの完了後、Server（Local Acquisition Unitを含む）またはData Warehouseデータベースをリストアする前に、セキュリティ設定をリストアする必要があります。DWHデータベースをリストアする前に、セキュリティ設定をすべてのInsight Serverにリストアする必要があります。

インプレースアップグレード（Insight Serverでのみ使用可能）では、セキュリティ設定が適切に処理されるため、リストアする必要はありません。

を使用します `securityadmin` 構成のバックアップを作成し、保存されている構成を復元するツール。詳細については、を検索してください `securityadmin` OnCommand Insight ドキュメントセンター： http://docs.netapp.com/oci-73/index.jsp[]

====