---
permalink: install-windows/network-traffic-generated-by-oncommand-insight.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight で生成されるネットワークトラフィック、ネットワークを通過する処理データの量、およびOnCommand Insight によるデバイスへの負荷は、多くの要因によって異なります。 
---
= OnCommand Insight で生成されるネットワークトラフィック
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight で生成されるネットワークトラフィック、ネットワークを通過する処理データの量、およびOnCommand Insight によるデバイスへの負荷は、多くの要因によって異なります。

トラフィック、データ、および負荷は、次の要因に基づいて環境によって異なります。

* 生データ
* デバイスの構成
* OnCommand Insight の導入トポロジ
* インベントリデータやパフォーマンスデータソースのポーリング間隔が異なるため、低速なデバイスを検出したり帯域幅を節約したりするために、間隔を短くすることができます


OnCommand Insight で収集される生の構成データは大きく異なる場合があります。

次の例は、設定データがどのように変化し、多くの設定要因によってトラフィック、データ、および負荷がどのように影響するかを示しています。たとえば、2つのアレイにそれぞれ1、000本のディスクがあるとします。

* アレイ1：1、000本のSATAディスクがあり、すべて1TBです。1、000本のディスクがすべて1つのストレージプールに含まれ、ESXクラスタ内の同じ32ノードに対して1、000個のLUNが提供（マッピングおよびマスク）されます。
* アレイ2：2TBのデータディスクが400本、600GBのFCディスクが560本、SSDが40本あります。ストレージプールは3つありますが、FCディスクのうち320本が従来のRAIDグループで使用されています。RAIDグループに分割されたLUNは従来のマスキングタイプ（symmaskdb）を使用し、シンプロビジョニングされたプールベースのLUNは新しいマスキングタイプ（symaccess）を使用します。150の異なるホストに対して600個のLUNが提供されました。200個のBCV（600個のLUNのうち200個のフルブロックレプリカボリューム）があります。また、別のサイトのアレイ上に存在するボリュームのリモートレプリカボリュームである200個のR2ボリュームもあります。


それぞれ1、000本のディスクと1、000個の論理ボリュームで構成されています。データセンターで消費するラックスペースが物理的に同じである場合もあれば、同じファームウェアを実行している場合もありますが、2つ目のアレイの構成は1つ目のアレイよりもはるかに複雑です。
