---
permalink: install-windows/overview-of-insight-upgrade-process.html 
sidebar: sidebar 
keywords:  
summary: Insightのアップグレードを開始する前に、アップグレードプロセスについて理解しておくことが重要です。アップグレードプロセスは、Insightのほとんどのバージョンで同じです。 
---
= OnCommand Insight のアップグレードプロセスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Insightのアップグレードを開始する前に、アップグレードプロセスについて理解しておくことが重要です。アップグレードプロセスは、Insightのほとんどのバージョンで同じです。

[NOTE]
====
* OnCommand Insightをアップグレードする前に、ボルト*をバックアップする必要があります。

詳細については、手順を参照してlink:../config-admin\/security-management.html["securityadminツール"]ください。

====
Insightのアップグレードプロセスで実行する作業の概要は次のとおりです。

* インストールパッケージをダウンロードしています
* Data Warehouseデータベースをバックアップしています
+
データが誤ってレポートされないようにするには、Data WarehouseデータベースをInsightデータベースよりも先にバックアップしておく必要があります。

* Insightデータベースをバックアップしています
+
Insightデータベースは、インプレースアップグレードを実行すると自動的にバックアップされます。アップグレード前にデータベースをバックアップし、Insight Serverとは別の場所に保存することを推奨します。アップグレードプロセスでは、Insightは新しいデータを収集しません。収集されないデータの量を最小限に抑えるには、アップグレード予定時刻の1~2時間以内にデータベースバックアップを開始する必要があります。

* Data WarehouseおよびRemote Acquisition Unitのセキュリティ設定をデフォルトの設定から変更した場合はバックアップします。
+
デフォルト以外のセキュリティ設定は、アップグレードの完了後、Data Warehouseデータベースをシステムにリストアする前に、Data WarehouseおよびRAUサーバにリストアする必要があります。

* Data Warehouseのカスタムレポートをバックアップしています
+
Data Warehouseデータベースをバックアップすると、カスタムレポートも含まれます。Data Warehouseサーバにバックアップファイルが作成されます。Data Warehouseサーバとは別の場所にカスタムレポートをバックアップすることを推奨します。

* Data WarehouseとRemote Acquisition Unitソフトウェアのアンインストール（該当する場合
+
Insight Serverはインプレースアップグレードが可能なため、ソフトウェアをアンインストールする必要はありません。インプレースアップグレードでは、データベースがバックアップされ、ソフトウェアがアンインストールされ、新しいバージョンがインストールされてから、データベースがリストアされます。

* Insight Server、Data Warehouse、およびRemote Acquisition Unitでのソフトウェアのアップグレード
+
以前に適用されたライセンスはすべてレジストリに残ります。これらのライセンスを再適用する必要はありません。

* アップグレード後の手順の実行

