---
permalink: install-windows/remote-acquisition-unit-server-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: ファイアウォールの背後、リモートサイト、プライベートネットワーク、または異なるネットワークセグメントにあるSANデバイスから情報を取得するには、Remote Acquisition Unit（RAU\）をインストールする必要があります。RAUをインストールする前に、オペレーティングシステム、CPU、メモリ、およびディスクスペースの要件を満たしていることを確認する必要があります。 
---
= Remote Acquisition Unitサーバの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイアウォールの背後、リモートサイト、プライベートネットワーク、または異なるネットワークセグメントにあるSANデバイスから情報を取得するには、Remote Acquisition Unit（RAU）をインストールする必要があります。RAUをインストールする前に、オペレーティングシステム、CPU、メモリ、およびディスクスペースの要件を満たしていることを確認する必要があります。

|===


| コンポーネント | 要件 


 a| 
オペレーティングシステム
 a| 
64ビットのMicrosoft Windows Server 2012、2012 R2、2016、または2019を実行しているコンピュータ（最新のサービスパックを適用）



 a| 
CPU
 a| 
4 個の CPU コア



 a| 
メモリ
 a| 
16GB の RAM



 a| 
使用可能なディスクスペース
 a| 
40 GB



 a| 
ネットワーク
 a| 
100Mbps/1Gbpsイーサネット接続、静的IPアドレス、すべてのFCデバイスへのIP接続、OnCommand Insight サーバへの必要なポート（80または443）。



 a| 
権限
 a| 
RAUサーバに対するローカル管理者権限



 a| 
ウィルススキャン
 a| 
このOnCommand Insight コンポーネントのインストール中に、すべてのウイルススキャナを完全に無効にする必要があります。インストール後、Insightコンポーネントで使用されるパスをウィルススキャンから除外する必要があります。また、インストール後に、IBM/DB2フォルダ（例：_C：\Program Files\IBM\DB2_）をアンチウィルススキャンから除外する必要があります。

|===