---
permalink: install-windows/restoring-the-data-warehouse-database.html 
sidebar: sidebar 
keywords:  
summary: Data Warehouseデータベースをバックアップすると、Data Warehouseで.zipファイルが作成されます。このファイルを使用してあとで同じデータベースをリストアできます。 
---
= Data Warehouseデータベースをリストアしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Data Warehouseデータベースをバックアップすると、Data Warehouseでが作成されます `.zip` 同じデータベースをあとでリストアするために使用できるファイル。



== このタスクについて

Data Warehouseデータベースをリストアするときに、ユーザアカウント情報もバックアップからリストアできます。ユーザ管理テーブルは、Data WarehouseのみのインストールでData Warehouseレポートエンジンで使用されます。



== 手順

. Data Warehouseポータルにログインします `+https://fqdn/dwh+`。
. 左側のナビゲーションペインで、*[バックアップ/リストア]*をクリックします。
. [データベースとレポートのリストア]*セクションで、*[参照]*をクリックし、を探します `.zip` Data Warehouseのバックアップを保持するファイル。
. 次のオプションは両方とも選択したままにすることを推奨します。
+
** *データベースのリストア*
+
Data Warehouseの設定、データマート、接続、およびユーザアカウント情報が含まれます。

** *リストア・レポート*
+
カスタムレポート、事前定義済みレポート、事前定義済みレポートへの変更、およびReporting Connectionで行ったレポート設定が含まれます。



. [* リストア ] をクリックします。
+
リストアステータスから移動しないでください。このコマンドを実行すると、リストアステータスは表示されなくなり、リストア処理の完了を通知するメッセージは表示されません。

. アップグレードプロセスを確認するには、を表示します `dwh_upgrade.log` ファイル。次の場所にあります。 `<install directory>\SANscreen\wildfly\standalone\log`。
+
リストアプロセスが完了すると、*[リストア]*ボタンのすぐ下にメッセージが表示されます。リストアプロセスが正常に完了すると、成功したことを示すメッセージが表示されます。リストアプロセスが失敗した場合は、原因 に発生した特定の例外を示すメッセージが表示されます。この場合は、テクニカルサポートに連絡してを提供してください `dwh_upgrade.log` ファイル。例外が発生してリストア処理が失敗すると、元のデータベースは自動的にリセットされます。

+
[NOTE]
====
「Failed upgrading Cognos content store」というメッセージが表示されてリストア処理が失敗した場合は、レポートを含めずにData Warehouseデータベースをリストアし（データベースのみ）、XMLレポートのバックアップを使用してレポートをインポートします。

====

