---
permalink: install-windows/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: 必要な準備作業がすべて完了したら、Data Warehouseサーバにログインし、インストールパッケージを実行してアップグレードを完了できます。 
---
= Data Warehouseをアップグレードしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必要な準備作業がすべて完了したら、Data Warehouseサーバにログインし、インストールパッケージを実行してアップグレードを完了できます。



== このタスクについて

Data Warehouse（DWH）ではインラインアップグレードはサポートされません。DWHソフトウェアを新しいバージョンにアップグレードするには、次の手順を実行します。

[NOTE]
====
* DWHをアップグレードする前に、ボルト*をバックアップする必要があります。

詳細については、手順を参照してlink:../config-admin\/security-management.html["securityadminツール"]ください。

====


== 手順

Data Warehouseをアップグレードする場合は、次の操作を実行する必要があります。

. DWH 7.3.16をインストールしたら、次の順序でバックアップとデータベースをリストアします。
+
.. バックアップ
.. データベース


. Windowsのローカル管理者権限を持つアカウントでDWHサーバにログインします。
. DWHポータルインターフェイスを使用して、DWH DBとレポートのバックアップを作成します。
. ヴォールトをバックアップします。のドキュメントを参照してくださいlink:../config-admin/security-management.html["securityadmin"]。
. サーバからDWHソフトウェアをアンインストールします。
. サーバをリブートして、メモリからコンポーネントを削除します。
. DWHの新しいバージョンをサーバにインストールします。
+
インストールには約2時間かかります。デフォルトはすべて選択したままにすることを推奨します。

. ボルトをDWHサーバーにリストアします。
. DWHデータベースをサーバにリストアします。




== 完了後

アップグレード後にData Warehouseデータベースをリストアする必要があります。この処理には、アップグレードと同じかそれ以上の時間がかかることがあります。

[NOTE]
====
OnCommand Insight のアップグレード時に、お客様が別のInsightサーバに切り替えることがよくあります。Insightサーバを変更した場合は、Data Warehouseデータベースをリストアすると、既存のコネクタがサーバの以前のIPアドレスまたはホスト名を参照するようになります。エラーを回避するために、コネクタを削除して新しいコネクタを作成することを推奨します。

====