---
permalink: install-windows/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: 必要な準備作業がすべて完了したら、Data Warehouseサーバにログインし、インストールパッケージを実行してアップグレードを完了できます。 
---
= Data Warehouseをアップグレードしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必要な準備作業がすべて完了したら、Data Warehouseサーバにログインし、インストールパッケージを実行してアップグレードを完了できます。



== このタスクについて

Data Warehouse（DWH）ではインラインアップグレードはサポートされません。DWHソフトウェアを新しいバージョンにアップグレードするには、次の手順を実行します。

[NOTE]
====
DWHをアップグレードすると、_securityadmin_toolバックアップを含むフォルダが削除されます。DWHをアップグレードする前にバックアップをバックアップすることを強く推奨します。参考までに、デフォルトのボルトフォルダは次のとおりです。

* ボルトフォルダ（使用中のボルト）：``%SANSCREEN_HOME%\wildfly\standalone\configuration\vault``
* バックアップ： `%SANSCREEN_HOME%\backup\vault`


を参照してください http://ie-docs.rtp.openeng.netapp.com/oci-73_ram/topic/com.netapp.doc.oci-acg/GUID-E3351676-2088-4767-AAB5-CB1D8476291C.html?resultof=%22%76%61%75%6c%74%22%20["Data Warehouseでセキュリティを管理する"] を参照してください。

====


== 手順

. Windowsのローカル管理者権限を持つアカウントでDWHサーバにログインします。
. DWHポータルインターフェイスを使用して、DWH DBとレポートのバックアップを作成します。
. サーバがデフォルト以外のセキュリティ設定を使用している場合は、セキュリティ設定をバックアップします。
. サーバからDWHソフトウェアをアンインストールします。
. サーバをリブートして、メモリからコンポーネントを削除します。
. DWHの新しいバージョンをサーバにインストールします。
+
インストールには約2時間かかります。デフォルトはすべて選択したままにすることを推奨します。

. デフォルト以外のセキュリティ設定をDWHサーバにリストアします。
. DWHデータベースをサーバにリストアします。




== 完了後

アップグレード後にData Warehouseデータベースをリストアする必要があります。この処理には、アップグレードと同じかそれ以上の時間がかかることがあります。

[NOTE]
====
OnCommand Insight のアップグレード時に、お客様が別のInsightサーバに切り替えることがよくあります。Insightサーバを変更した場合は、Data Warehouseデータベースをリストアすると、既存のコネクタがサーバの以前のIPアドレスまたはホスト名を参照するようになります。エラーを回避するために、コネクタを削除して新しいコネクタを作成することを推奨します。

====