---
permalink: install-linux/anomaly-detection-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: 異常検出ソフトウェアには、特定のオペレーティングシステム、メモリ容量、CPUコア、およびディスクスペースが必要です。異常検出ソフトウェアをインストールするには、特定の要件に従う必要があります。 
---
= 異常検出の要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
異常検出ソフトウェアには、特定のオペレーティングシステム、メモリ容量、CPUコア、およびディスクスペースが必要です。異常検出ソフトウェアをインストールするには、特定の要件に従う必要があります。

|===


| コンポーネント | 必須 


 a| 
オペレーティングシステム
 a| 
次のいずれかのライセンスバージョンを実行しているコンピュータ。他のアプリケーションレベルのソフトウェアを実行していないコンピュータ。

* Red Hat Enterprise Linux 7.3、7.4、7.5、7.6、7.7、 7.8、7.9、8.1、8.2、8.3、 8.4、8.5
* CentOS 7.5、7.6、7.7、7.8、7.9、 CentOS 8ストリーム
* Oracle Enterprise Linux 7.5、7.6、7.7、7.8、7.9、 8.1、8.2、8.3、8.4、8.5
* SUSE Enterprise Linux 15.1、15.2、15.3
* openSUSE 15.1、15.2、15.3


ライセンスバージョンを使用すると、インストールに必要な依存関係がオペレーティングシステムによって自動的に解決されます。

専用のサーバを使用することを推奨します。



 a| 
仮想マシン（VM）
 a| 
異常検出は、インスタンスのCPUリソースとメモリリソースが予約されていれば、仮想環境で実行できます。



 a| 
CPUとメモリ
 a| 
8コア。64 GBのメモリサーバ。



 a| 
使用可能なディスクスペース
 a| 
サーバには、次のようにパーティショニングされた200GBの空きディスクスペースが必要です。

* 150 GBインチ `/var/lib`
* 25GBインチ `/var/log`
* 25GBインチ `/opt`


ソフトウェアをインストールするには、次のディスクスペースが必要です。

* 5GBインチ `/var/lib`
* 25GBインチ `/var/log`
* 25GBインチ `/opt`


マウントすることを推奨します ``/opt``および ルートファイルシステムとは別のディスクに配置します (`/`）。



 a| 
権限
 a| 
異常検出ソフトウェアをインストールするにはsudo権限が必要です。



 a| 
ネットワーク
 a| 
異常検出ソフトウェアをインストールするInsight Serverは、異常検出エンジンを実行しているサーバと同じネットワーク、または少なくとも同じサイトまたはデータセンターに配置する必要があります。異常検出ソフトウェアでは、ワイドエリアネットワーク（WAN）の設定はサポートされません。

VMでTCPポート8080および9200が開いている必要があります。



 a| 
前提条件
 a| 
有効なPerformライセンスが必要です。異常検出ソフトウェアをインストールするInsight ServerのIPアドレスが必要です。

デフォルトのポートを使用しない場合は、Insight Serverで別のポート番号を使用する必要があります。

VMでTCPポート8080および9200が開いている必要があります。

VMに対する管理者権限を持つアカウントのユーザ名とパスワードが必要です。

バックスラッシュを1つ含むユーザ名（company\user）には、バックスラッシュを2つ入力する必要があります。

ユーザ名にバックスラッシュ（company\\tom）のあとに「t」を含めることはできません。

|===
[NOTE]
====
サイジングに関するすべての推奨事項について、ネットアップの担当者に相談して検証する必要があります。

====