---
permalink: install-linux/data-warehouse-server-requirements-linux.html 
sidebar: sidebar 
keywords:  
summary: Data Warehouseサーバは、確立されているハードウェアおよびソフトウェアの要件に対応したコンピュータで実行する必要があります。Apache Webサーバまたはレポート作成ソフトウェアがこのマシンにインストールされていないことを確認する必要があります。 
---
= Data Warehouseサーバの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Data Warehouseサーバは、確立されているハードウェアおよびソフトウェアの要件に対応したコンピュータで実行する必要があります。Apache Webサーバまたはレポート作成ソフトウェアがこのマシンにインストールされていないことを確認する必要があります。

[NOTE]
====
OnCommand Insight のサイジングには、環境内のアセットの数、保持する履歴データの量など、さまざまな要素が関係します。次のData Warehouseのサイジング例はあくまでもガイドラインであり、Insightでテストされた一部の環境を示したものです。環境内でこれらの要素やその他の要素を変更すると、Insightのサイジング要件が変更される可能性があります。

====
詳細なサイジングガイダンスについては、Insightをインストールまたはアップグレードする前に、担当のセールスエンジニアに問い合わせることを推奨します。

*例：*

|===


| 環境要因： | テストしたディスク容量、CPU、メモリ： 


 a| 
ストレージアレイ18台、VM 3、400台

4、500個のスイッチポート
 a| 
200 GBのハードディスク8コア

32GBのRAM



 a| 
110台のストレージアレイ11、500台のVM

14、500個のスイッチポート
 a| 
300 GBハードディスク8コア

48GBのRAM

|===
*要件：*

|===


| コンポーネント | 必須 


 a| 
オペレーティングシステム
 a| 
次のいずれかのライセンスバージョンを実行しているコンピュータ。他のアプリケーションレベルのソフトウェアを実行していないコンピュータ。

* Red Hat Enterprise Linux 7.3、7.4、7.5、7.6、7.7、 7.8、7.9、8.1、8.2、8.3、 8.4、8.5、8.8、9.2
* CentOS 7.2、7.5、7.6、7.7、7.8、 7.9、CentOS 8 Stream、CentOS 9 Stream
* Oracle Enterprise Linux 7.5、7.6、7.7、7.8、7.9、 8.1、8.2、8.3、8.4、8.5、 8.8




 a| 
仮想マシン（VM）
 a| 
このコンポーネントは、インスタンスのCPUリソースとメモリリソースが予約されていれば、仮想環境で実行できます。



 a| 
CPU
 a| 
8~40個のCPUコア



 a| 
メモリ
 a| 
32GB~2TBのRAM



 a| 
利用可能なディスク容量
 a| 
200GB~512GBのディスクスペースには、少なくとも50GBの空きディスクスペースが必要です `/var/lib` にパーティションと25GBの空きディスクスペースがあります `/opt` および `/var/log` パーティション：



 a| 
ネットワーク
 a| 
* 100 Mbpsまたは1 Gbpsのイーサネット接続
* 静的IPアドレス
* OnCommand Insight DWHサーバプロセスの場合は、ポート80、443、1098、1099、 3873、8083、4444～4446
* MySQLの場合は、ポート3306


|===