---
permalink: install-linux/insight-server-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: 専用のサーバを使用することを推奨します。他のアプリケーションがインストールされているサーバにはInsightをインストールしないでください。製品の要件が満たされていれば、物理サーバと仮想サーバの両方がサポートされます。 
---
= Insight Serverの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
専用のサーバを使用することを推奨します。他のアプリケーションがインストールされているサーバにはInsightをインストールしないでください。製品の要件が満たされていれば、物理サーバと仮想サーバの両方がサポートされます。

OnCommand Insight サーバソフトウェアをインストールするには、sudo権限が必要です。

Insightのコンポーネントの中には、インストール時に依存パッケージが必要なものがあります。Insightをインストールする前に、YUMリポジトリにアクセスできることを確認してください。

[NOTE]
====
OnCommand Insight のサイジングには、データソースのタイプとサイズ、環境内のアセットの数、ポーリング間隔など、さまざまな要素を考慮する必要があります。次のサイジング例はあくまでもガイドラインであり、Insightでテストされた一部の環境を示したものです。環境内でこれらの要素やその他の要素を変更すると、Insightのサイジング要件が変更される可能性があります。これらのガイドラインには、最大90日間のパフォーマンスアーカイブデータ用のディスクスペースが含まれます。

====
詳細なサイジングガイダンスについては、Insightをインストールまたはアップグレードする前に、担当のセールスエンジニアに問い合わせることを推奨します。

*例：*

|===


| 環境要因： | テストしたディスク容量、CPU、メモリ： 


 a| 
80ストレージアレイ4、000ボリューム

4、000台のVM

4、000個のスイッチポート
 a| 
250GBディスクスペース8コア

32GBのRAM



 a| 
160個のストレージアレイ40、000個のボリューム

8、000台のVM

8、000個のスイッチポート
 a| 
1TBのディスクスペース12コア

48GBのRAM

|===
*要件：*

|===


| コンポーネント | 必須 


 a| 
オペレーティングシステム
 a| 
次のいずれかのライセンスバージョンを実行しているコンピュータ。他のアプリケーションレベルのソフトウェアを実行していないコンピュータ。

* Red Hat Enterprise Linux 7.3、7.4、7.5、7.6、7.7、 7.8、7.9、8.1、8.2、8.3、 8.4、8.5、8.8、9.2
* CentOS 7.2、7.5、7.6、7.7、7.8、 7.9、CentOS 8 Stream、CentOS 9 Stream
* Oracle Enterprise Linux 7.5、7.6、7.7、7.8、7.9、 8.1、8.2、8.3、8.4、8.5、 8.8


ライセンスバージョンを使用すると、インストールに必要な依存関係がオペレーティングシステムによって自動的に解決されます。

Insightをインストールする前に、MariaDBをアンインストールする必要があります。

[NOTE]
====
MariaDBをアンインストールすると、Postfix Mail Transport Agentも削除されます。

====
専用のサーバを使用することを推奨します。



 a| 
仮想マシン（VM）
 a| 
このコンポーネントは、インスタンスのCPUリソースとメモリリソースが予約されていれば、仮想環境で実行できます。



 a| 
メモリとCPU
 a| 
24~256GBのRAM

8~32コア



 a| 
使用可能なディスクスペース
 a| 
100GB~3TBのインストールディスクスペース

50 GB~1 TBのパフォーマンスアーカイブディスクスペース

500GB環境の例では、次のパーティション分割を推奨します。

* /optディレクトリ-- 50GB
* /var/logディレクトリ-- 100GB
* /var/libディレクトリ-- 350 GB


マウントすることを推奨します `/opt` および `/var` ルートファイルシステムとは別のディスクに配置します (`/`）。

InsightのインストールスペースにはSSDディスクを使用することを推奨します。



 a| 
ネットワーク
 a| 
イーサネット接続とポート：

* 専用の（静的な）IPアドレスを使用した100Mbpsまたは1Gbpsのイーサネット接続、およびSANのすべてのコンポーネント（FCデバイスやRemote Acquisition Unitなど）へのIP接続。
* OnCommand Insight サーバプロセスのポート要件は、80、443、1090~1100、3873、8083、 4444~4446、5445、5455、4712~4714、5500、 そして5501
* 取得プロセスには、ポート12123と5679が必要です。
* MySQLにはポート3306が必要です。
* Elasticsearchには、ポート9200と9310が必要です


ポート443および3306は、存在するファイアウォールを介した外部アクセスを必要とします。



 a| 
権限
 a| 
OnCommand Insight サーバに対するsudo権限が必要です。

次のフォルダのいずれかがシンボリックリンクである場合は、リンク先ディレクトリに「755」権限があることを確認してください。

* /opt/netapp
* /var/lib/netapp
* /var/log/netapp




 a| 
リモート接続
 a| 
インストールおよびインストール後のサポートを容易にするために、WebExアクセスまたはリモートデスクトップ接続を可能にするインターネット接続。



 a| 
アクセス性
 a| 
HTTPSアクセスが必要です。



 a| 
HTTPサーバまたはHTTPSサーバ
 a| 
Apache HTTPサーバやその他のHTTPSサーバは、OnCommand Insight サーバと同じポート（443）で競合しないようにし、自動的に起動しないようにしてください。ポート443をリスンする必要がある場合は、他のポートを使用するようにOnCommand Insight サーバを設定する必要があります。

|===