---
permalink: install-linux/installing-oncommand-insight-data-warehouse-linux.html 
sidebar: sidebar 
keywords:  
summary: インストールは自己完結型で、OnCommand Insight Data Warehouse（DWH\）の実行と運用に必要な要素が含まれています。 
---
= OnCommand Insight Data Warehouseをインストールしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インストールは自己完結型で、OnCommand Insight Data Warehouse（DWH）の実行と運用に必要な要素が含まれています。



== 作業を開始する前に

インストールの前提条件をすべて満たしておく必要があります。



== このタスクについて

Data WarehouseにはCognosのレポート機能があります。InsightをLinuxサーバにインストールする場合は、Data WarehouseをWindowsサーバにインストールする場合にのみ、これらの機能を使用できます。WindowsへのData WarehouseのインストールおよびCognosのレポート機能については、_ OnCommand Insight インストールガイド（Microsoft Windows_）を参照してください。



== 手順

. sudo権限があるアカウントでData Warehouseサーバにログインします。
. インストールファイルが保存されているサーバー上のディレクトリに移動し、次のコマンドを入力します。
+
`unzip oci-dwh-<version>-linux-x86_64.zip`

+
インストールファイルのバージョン番号を確認してください。バージョン番号は、コマンドに表示されているものとは異なる場合があります。

. の構文、コマンド引数、およびパラメータの使用方法を確認できます `oci-install.sh` インストールを開始する前に：
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh --help`

. インストールスクリプトを実行します。
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh`

+
Insight ServerまたはData WarehouseをCentOS 9 Stream、Red Hat Enterprise Linux 9.4、またはOracle Linux 9.4にインストールする場合は、まずインストーラファイルが格納されているディレクトリに移動し、コマンドラインオプション「-- install-mysql-dependencies」を使用してインストールコマンドを実行する必要があります。

+
....
cd /tmp/oci-7.3.16.1.297-linux-x86_64
sudo ./oci-install.sh --install-mysql-dependencies
....
. ライセンス契約を読み、同意して、画面の指示に従います。




== 結果

すべてのプロンプトを回答 にすると、インストールが開始されます。所要時間は約10分です（インストールされているアプリケーションによって異なります）。



== サーバとDWHの同期


IMPORTANT: Data Warehouseをインストールしたら、Data WarehouseとOnCommand Insightサーバを*同期する必要があります*。次の手順を実行します。

. OnCommand Insightサーバーシステムで、* SecurityAdmin*ツールをインタラクティブモードで起動します。
+
 securityadmin -i
. _inventory_and_dwh_internal_usersのパスワードを任意のパスワードに変更します。*以下に記載する必要があるため、これらのパスワードをメモしておいてください。
. DWHサービスを再開します。
. オン*各コネクター*では、* SecurityAdmin*ツールをインタラクティブモードで起動します。上記の手順2でメモしたパスワードが必要になります。
+
 securityadmin -i
. _inventory_and_dwh_internal_usersのパスワードを手順2で使用したパスワードに変更します。
. コネクタのサービスを再起動します。
. 手順2で_inventory_and_dwh_internal_usersのパスワードを使用して、コネクタをDWHに追加します。

