---
permalink: install-linux/installation-prerequisites.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight をインストールする前に、現在のソフトウェアバージョンをダウンロードし、適切なライセンスを取得して、環境をセットアップする必要があります。 
---
= インストールの前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight をインストールする前に、現在のソフトウェアバージョンをダウンロードし、適切なライセンスを取得して、環境をセットアップする必要があります。

OnCommand Insight をインストールする前に、次のものがあることを確認してください。

* ダウンロードしたインストールパッケージに含まれている最新バージョンのOnCommand Insight ソフトウェアファイル
* ダウンロードしたOnCommand Insight バージョンを操作するためのライセンス
* 最小限のハードウェアおよびソフトウェア環境
+
現在の製品では、以前のバージョンのOnCommand Insight 製品では使用されていなかった追加のハードウェアリソース（OnCommand Insight 製品の機能強化のため）が消費される可能性があります。

* OnCommand Insight サーバ、Data WarehouseとReporting、およびRemote Acquisition Unitのハードウェアとネットワークの構成を含む導入計画。
* Java 8 - OnCommand Insight Java UI用。
+

NOTE: OnCommand Insight には、Java SE 8用のOracle有料ライセンスが含まれています。Java SE 8ライセンスを追加で購入する必要はありません。このライセンスでは、Java SE 8をすべてのOCIコンポーネントで使用できます。を参照してください http://docs.netapp.com/oci-73/topic/com.netapp.ndc.notices/GUID-93BE9A1E-D79E-4A97-87A2-4DBE31372A16.html["通知"] ページを参照してください。


