---
permalink: install-linux/oncommand-insight-licenses.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight は、Insight Serverで特定の機能を有効にするライセンスで動作します。 
---
= OnCommand Insight ライセンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight は、Insight Serverで特定の機能を有効にするライセンスで動作します。

* * 発見 *
+
Discoverは、インベントリをサポートするInsightの基本ライセンスです。OnCommand Insight を使用するにはDiscoverライセンスが必要です。また、DiscoverライセンスをAssure、Perform、またはPlanの少なくとも1つのライセンスと組み合わせて使用する必要があります。

* *保証*
+
Assureライセンスは、グローバルパスポリシーやSANパスポリシー、違反管理などの保証機能をサポートします。脆弱性を表示および管理するには、Assureライセンスも必要です。

* *実行*
+
Performは、アセットページ、ダッシュボードウィジェット、クエリなどでのパフォーマンス監視、およびパフォーマンスポリシーや違反の管理をサポートするライセンスです。

* *計画*
+
Planライセンスは、リソースの使用状況や割り当てなどの計画機能をサポートします。

* * Host Utilization Pack *
+
Host Utilizationライセンスは、ホストおよび仮想マシンでのファイルシステムの使用をサポートします。

* *レポートオーサリング*
+
Report Authoringライセンスでは、レポートの作成者を追加できます。このライセンスにはPlanライセンスが必要です。



OnCommand Insight モジュールのライセンスは、年間または無期限で提供されます。

* Discover、Assure、Plan、Performモジュールの監視対象容量（テラバイト）
* Host Utilizationパックのホスト数
* Report Authoringに必要なCognos Pro-Authorsの追加単位数


ライセンスキーは、顧客ごとに生成される一意の文字列のセットです。ライセンスキーは、OnCommand Insight の担当者から入手できます。

インストールされているライセンスによって、ソフトウェアで使用できる次のオプションが制御されます。

* * 発見 *
+
インベントリの取得と管理（基盤）

+
変更を監視し、インベントリポリシーを管理します

* *保証*
+
SANパスのポリシーや違反を表示および管理します

+
脆弱性を確認および管理します

+
タスクと移行を表示および管理します

* *計画*
+
リクエストを表示および管理します

+
保留中のタスクを表示および管理します

+
リザベーション違反を表示および管理します

+
ポートバランス違反を表示および管理します

* *実行*
+
パフォーマンスデータ（ダッシュボードウィジェット、アセットページ、クエリのデータなど）を監視します

+
パフォーマンスポリシーや違反を表示および管理します



次の表に、adminユーザとadmin以外のユーザについて、Performライセンスがある場合とない場合に使用できる機能の詳細を示します。

|===


| 機能（admin） | Performライセンスあり | Performライセンスなし 


 a| 
アプリケーション
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
仮想マシン
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ハイパーバイザー
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ホスト
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
データストア
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
VMDK です
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
内部ボリューム
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ボリューム
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ストレージプール
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ディスク
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ストレージ
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ストレージノード
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ファブリック
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
スイッチポート
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません。「Port Errors」には「N/A」と表示されます。



 a| 
ストレージポート
 a| 
はい。
 a| 
はい。



 a| 
NPVポート
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
スイッチ
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
NPVスイッチ
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
qtree
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
クォータ
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
パス
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ゾーン
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ゾーンメンバー
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
汎用デバイス
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
テープ
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
マスキング
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
iSCSIセッション
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
ICSIネットワークポータル
 a| 
はい。
 a| 
パフォーマンスデータやグラフはありません



 a| 
検索
 a| 
はい。
 a| 
はい。



 a| 
管理
 a| 
はい。
 a| 
はい。



 a| 
ダッシュボード
 a| 
はい。
 a| 
はい。



 a| 
ウィジェット
 a| 
はい。
 a| 
一部使用可（アセット、クエリ、管理の各ウィジェットのみ使用可能）



 a| 
違反ダッシュボード
 a| 
はい。
 a| 
非表示



 a| 
アセットダッシュボード
 a| 
はい。
 a| 
一部使用可（ストレージIOPSとVM IOPSのウィジェットは非表示）



 a| 
パフォーマンスポリシーの管理
 a| 
はい。
 a| 
非表示



 a| 
アノテーションを管理します
 a| 
はい。
 a| 
はい。



 a| 
アノテーションルールを管理します
 a| 
はい。
 a| 
はい。



 a| 
アプリケーションを管理します
 a| 
はい。
 a| 
はい。



 a| 
クエリ
 a| 
はい。
 a| 
はい。



 a| 
ビジネスエンティティの管理
 a| 
はい。
 a| 
はい。

|===
|===


| フィーチャー（ Feature ） | ユーザ- Performライセンスあり | ゲスト- Performライセンスあり | ユーザ- Performライセンスなし | ゲスト- Performライセンスなし 


 a| 
アセットダッシュボード
 a| 
はい。
 a| 
はい。
 a| 
一部使用可（ストレージIOPSとVM IOPSのウィジェットは非表示）
 a| 
一部使用可（ストレージIOPSとVM IOPSのウィジェットは非表示）



 a| 
カスタムダッシュボード
 a| 
表示のみ（作成、編集、保存のオプションはありません）
 a| 
表示のみ（作成、編集、保存のオプションはありません）
 a| 
表示のみ（作成、編集、保存のオプションはありません）
 a| 
表示のみ（作成、編集、保存のオプションはありません）



 a| 
パフォーマンスポリシーの管理
 a| 
はい。
 a| 
非表示
 a| 
非表示
 a| 
非表示



 a| 
アノテーションを管理します
 a| 
はい。
 a| 
非表示
 a| 
はい。
 a| 
非表示



 a| 
アプリケーションを管理します
 a| 
はい。
 a| 
非表示
 a| 
はい。
 a| 
非表示



 a| 
ビジネスエンティティの管理
 a| 
はい。
 a| 
非表示
 a| 
はい。
 a| 
非表示



 a| 
クエリ
 a| 
はい。
 a| 
表示と編集のみ（保存オプションなし）
 a| 
はい。
 a| 
表示と編集のみ（保存オプションなし）

|===