---
permalink: dwh/adding-a-reporting-user.html 
sidebar: sidebar 
keywords:  
summary: Reportingポータルへのアクセスを必要とするユーザごとに新しいユーザアカウントを追加する必要があります。ユーザごとに異なるユーザアカウントを設定することで、アクセス権、個 々 の設定、およびアカウンタビリティを制御できます。 
---
= Reportingユーザを追加しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reportingポータルへのアクセスを必要とするユーザごとに新しいユーザアカウントを追加する必要があります。ユーザごとに異なるユーザアカウントを設定することで、アクセス権、個 々 の設定、およびアカウンタビリティを制御できます。



== 作業を開始する前に

Reportingユーザを追加する前に、一意のユーザ名を割り当て、使用するパスワードを決定し、正しいユーザロールを確認しておく必要があります。これらのロールはReportingポータルに特化されています。



== 手順

. Data Warehouseポータルに管理者としてログインします `+https://hostname/dwh+`、ここで `hostname` は、OnCommand Insight Data Warehouseがインストールされているシステムの名前です。
. 左側のナビゲーションペインで、*[ユーザ管理]*をクリックします。
. [ユーザー管理]ウィンドウで、*[新しいユーザーの追加]*をクリックします。
. 新しいReportingユーザについて、次の情報を入力します。
+
** * ユーザー名 *
+
アカウントのユーザ名（a~z、A~Z、0~9を含む英数字）

** *電子メールアドレス*
+
ユーザアカウントに関連付けられたEメールアドレス。ユーザがレポートをサブスクライブする場合に必要です

** * パスワード *
+
このユーザアカウントでOnCommand Insightにログインするためのパスワード。通常はユーザが選択し、インターフェイスで確認します

** * Insightロール*
+
適切な権限を持つユーザが使用できるロール

+
[NOTE]
====
OnCommand Insight ロールのオプションは、OnCommand Insight がレポーティングファシリティと同じマシンにインストールされている場合にのみ表示されます。これは一般的ではありません。

====
** *レポートロール*
+
このユーザアカウントのReportingロール（Pro Authorなど）

+
[NOTE]
====
Administratorロールは一意です。このロールは任意のユーザに追加できます。

====


. [ 追加（ Add ） ] をクリックします。

