---
permalink: dwh/annotations.html 
sidebar: sidebar 
keywords:  
summary: アノテーションを使用すると、環境内のオブジェクトに関連する情報を定義し、そのアノテーションに基づいてオブジェクトを追跡できます。たとえば、環境内のデバイスに建物番号やフロア番号のアノテーションを追加し、データセンターの1階にあるすべてのデバイスを返すクエリを作成できます。 
---
= アノテーションを使用して実行できる操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アノテーションを使用すると、環境内のオブジェクトに関連する情報を定義し、そのアノテーションに基づいてオブジェクトを追跡できます。たとえば、環境内のデバイスに建物番号やフロア番号のアノテーションを追加し、データセンターの1階にあるすべてのデバイスを返すクエリを作成できます。

また、特定のデータセンターまたはビジネスエンティティ内のすべてのデバイスを確認し、ティア1ストレージを最も多く使用しているビジネスエンティティを特定することもできます。そのためには、OnCommand Insight Web UIを使用して、データセンター、ビジネスエンティティ、または階層のアノテーションをデバイスに割り当てます。その後、選択したユーザ定義のアノテーションをOnCommand Insight からData Warehouseに取り込むことができます。これは、オブジェクトに割り当てられているアノテーション値をカスタムレポートに表示する場合に使用します。

Data Warehouseに伝播するユーザ定義のアノテーションを指定できます。アノテーションは、インベントリのオブジェクトテーブルおよびデータマートの関連するディメンションテーブルに列として追加されます。OnCommand Insight ユーザインターフェイスを使用してリソースのアノテーションを更新し、Data Warehouseのビルドを開始するか次回のビルドまで待機すると、次の表に結果が表示されます。

* dwh_inventory.annotation_value
* dwh_inventory.object_to_annotation


OnCommand Insight で入力したアノテーションがData Warehouseに含まれていることを確認するには、次の主要なプロセスを実行する必要があります。

* Data Warehouseにアノテーションをインポートする前に、アノテーションがOnCommand Insight で準備されていることを確認する必要があります。
+
そのためには、*トラブルシューティング*>* Data Warehouseのアノテーションの強制更新*オプションを手動で実行するか、スケジュールされた次の一時データ実行プロセスが実行されるまで待つことができます。アノテーションを強制的に更新する場合は、OnCommand Insight サーバで一時データ（アノテーション値など）が計算されてデータベーステーブルに格納され、Data WarehouseのETLプロセスがデータを読み取れるようになります。アノテーションデータは15分ごとに自動的に更新されますが、強制的に更新する頻度を増やすこともできます。

* 次に、Data Warehouse** Annotations**オプションを使用してData Warehouseにアノテーションをインポートします。
* OnCommand Insight Reportingポータルのレポートオーサリングツールを使用して作成するレポートにアノテーションを含める場合は、OnCommand Insight Reportingのメタデータモデルを更新する必要があります。


Data Warehouseをアップグレードすると、データベースのリストアプロセス中にアノテーションジョブが自動的に実行されます。アノテーションジョブは、WildFlyの起動時にも自動的に実行されます。

[NOTE]
====
WildFlyは、OnCommand Insight Javaコードを実行するアプリケーションサーバであり、OnCommand Insight サーバとデータウェアハウスの両方に必要です。

====