---
permalink: dwh/data-retention-and-time-periods.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight Data Warehouseでは、抽出、変換、ロード\（ETL\）プロセスから取得したデータが、データマートやデータの時間単位に基づいてさまざまな期間にわたって保持されます。 
---
= データ保持、ETL、および期間
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight Data Warehouseでは、抽出、変換、読み込み（ETL）プロセスで取得したデータが、データマートやデータの時間単位に基づいて、さまざまな期間にわたって保持されます。



== Performanceデータマートおよび時間単位（ボリュームおよび内部ボリューム）

OnCommand Insight Data Warehouseでは、1時間ごとの平均値、1時間ごとの最大値、および1日の各時間（24個のデータポイント）のアクセスビットが14日間記録されます。アクセスビットはブール値で、1時間のインターバルの間にボリュームがアクセスされた場合はtrue、アクセスされなかった場合はfalseになります。前日の24個のデータポイントはすべて、その日の最初のETLプロセスで取得されます。

ETLプロセスを1時間に1回実行して1時間ごとのデータポイントを収集する必要はありません。1日のうちに追加のETLプロセスを実行しても、OnCommand Insight Serverからパフォーマンス情報が取得されません。



== Performanceデータマートおよび日単位（ボリュームと内部ボリューム）

ETLが処理される毎日の平均値が計算され、Data Warehouseに入力されます。1日平均は、前日の24個のデータポイントの要約です。Performanceデータマートには、ボリュームと内部ボリュームの日単位の要約が13カ月間保持されます。



== Capacityデータマートおよび日単位

Capacityデータマートは、さまざまな容量ファクトの日単位の測定値を13カ月間提供します。Data Warehouse内の容量ファクトは、ETL前のデバイスの最後のデータソース収集時点の最新情報です。



== Capacityデータマートおよび月単位

Data Warehouseには、日単位の容量データが13カ月間保持されます。13カ月のしきい値に達すると、容量データが月単位で集計されます。月単位のデータは、月の代表日である日付によって反映される値に基づいています。

次の表に、月次サマリーに含まれる月次データを示します。

|===


| 日付 | 月代表値です | 割り当て容量 


 a| 
1月1日
 a| 
1（正しい）
 a| 
50TB



 a| 
1月2日
 a| 
0（False）
 a| 
52TB



 a| 
...
 a| 
...
 a| 
...



 a| 
1月31日
 a| 
0（False）
 a| 
65 TB



 a| 
2月1日
 a| 
1（正しい）
 a| 
65 TB

|===
この表を基にした月次レポートには、1月に50TBが割り当てられ、2月に65TBが割り当てられています。1月のそれ以外の容量の値は、月単位の要約には含まれません。



== Inventoryデータマート

Inventoryデータマートは履歴データではありません。ETLプロセスが実行されるたびに、Inventoryデータマートが消去されて再構築されます。そのため、Inventoryデータマートから生成されたレポートには、過去のインベントリ設定が反映されません。
