---
permalink: dwh/etl-frequency.html 
sidebar: sidebar 
keywords:  
summary: 抽出、変換、読み込み\（ETL\）プロセスは少なくとも1日に1回は実行する必要がありますが、必要に応じて何度も実行することを選択します。 
---
= ETLの頻度と日付データ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
抽出、変換、読み込み（ETL）プロセスは少なくとも1日に1回は実行する必要がありますが、必要に応じて何度も実行することを選択します。

Cognosのレポート作成エンジンでは、デフォルトですべての容量とパフォーマンスのファクトが追加で処理されます。そのため、適切な時間フィルタを使用せずにETLプロセスを1日に複数回実行すると、容量データが二重にカウントされるリスクがあります。

Dateディメンションの2つの日付データ要素は、日次ETLプロセスに関連しています。複数のデータモデルで使用されるDateディメンションには、ETLの影響を受ける次のデータ要素が含まれています。

* *はデイ代表*です
+
「Is Day Representative」データ要素は、1日の最初のETLプロセスの実行時に1（true）に設定されます。最初のETLプロセスが午前1時に実行される場合は、午前1時にロードされるすべてのデータについて、Is Day Representativeが1に設定されますETLプロセスそのあと（午後1時など）に2つ目のETLがスケジュールされている場合は、そのETLプロセスでロードされたデータに対して「Is Day Representative」が0（false）に設定されます。

* *が最新*です
+
「Is Latest」メンバーは、各ETLプロセスが完了すると1（true）に設定されます。最初のETLプロセスが午前1時に実行される場合は、午前1時のETLプロセスで読み込まれるすべてのデータに対して「Is Latest」が1に設定されますETLプロセスそのあと（午後1時など）に別のETLプロセスがスケジュールされている場合は、午後1時にロードされるデータに対して「Is Latest」が1に設定されますETLプロセスETLプロセスでは午前1時も設定されますETLロードの「Is Latest」エントリは0（false）です。


