---
permalink: dwh/restoring-the-data-warehouse-database.html 
sidebar: sidebar 
keywords:  
summary: Data Warehouseデータベースは、そのData Warehouseデータベースのバックアップ時に作成された.zipファイルを使用してリストアできます。 
---
= Data Warehouseデータベースをリストアしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Data Warehouseデータベースはを使用してリストアできます `.zip` Data Warehouseデータベースのバックアップ時に作成されたファイル。



== このタスクについて

Data Warehouseデータベースをリストアする場合は、ユーザアカウント情報もバックアップからリストアできます。ユーザ管理テーブルは、Data WarehouseのみのインストールでData Warehouseレポートエンジンで使用されます。



== 手順

. Data Warehouseポータルにログインします `+https://hostname/dwh+`、ここで `hostname` は、OnCommand Insight Data Warehouseがインストールされているシステムの名前です。
. 左側のナビゲーションペインで、*[バックアップ/リストア]*をクリックします。
. [データベースとレポートのリストア]*セクションで、*[参照]*をクリックし、を探します `.zip` Data Warehouseのバックアップを含むファイル。
. レポートまたはユーザアカウントデータをリストアする場合は、次のチェックボックスのいずれかまたは両方を選択します。
+
** *データベースのリストア*
+
Data Warehouseの設定、データマート、接続、およびユーザアカウント情報が含まれます。

** *リストア・レポート*
+
カスタムレポート、事前設計済みレポート、事前設計済みレポートに対する変更、Reporting Portalで作成したレポート設定が含まれます。

+
[NOTE]
====
名前にスラッシュ（/）または開いたブラケット（[）を含むカスタムレポートがデータベースバックアップに含まれている場合（たとえば、US IT Center Switch Port Boston/July）、リストア処理によってレポートの名前が変更され、スラッシュまたは開いたブラケットがアンダースコアに置き換えられます（例： US IT Center Switch Port Boston_July）。

====


. [* リストア ] をクリックします。
+
リストアプロセスが完了すると、[Restore]ボタンの下にメッセージが表示されます。リストアプロセスが正常に完了すると、成功したことを示すメッセージが表示されます。リストアプロセスが失敗した場合は、エラーの原因となった特定の例外がメッセージに表示されます。例外が発生してリストアプロセスが失敗すると、元のデータベースは自動的にリセットされます。


