---
permalink: dwh/setting-email-notifications.html 
sidebar: sidebar 
keywords:  
summary: Data Warehouseのジョブが正常に完了しなかった場合に、Data Warehouseから特定のEメールアドレスにEメールを送信するように設定できます。 
---
= Eメール通知の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Data Warehouseのジョブが正常に完了しなかった場合に、Data Warehouseから特定のEメールアドレスにEメールを送信するように設定できます。



== 手順

. Data Warehouseポータルにログインします `+https://hostname/dwh+`、ここで `hostname` は、OnCommand Insight Data Warehouseがインストールされているシステムの名前です。
. 左側のナビゲーションペインで、*[Email Notification]*をクリックします。
. 次のように入力します。
+
** SMTPサーバアドレス
+
組織内でSMTPサーバとして機能しているサーバを指定します。ホスト名またはIPアドレスをnn.nnn.nnn.nnn形式で指定します。ホスト名を指定する場合は、そのホスト名をDNSで解決できることを確認してください。

** SMTPサーバのユーザ名とパスワード
+
Eメールサーバにアクセスするためのユーザ名を指定します。SMTPサーバでユーザがサーバにログインする必要がある場合にのみ必要です。これは、アプリケーションへのログインとEメールへのアクセスに使用するユーザ名と同じです。

** 通知が有効です
+
*はい*通知を有効にします。*いいえ*通知を無効にします。

** 送信者のEメール
+
通知の送信に使用するEメールアドレスを指定します。組織内の有効なEメールアドレスを指定する必要があります。

** 受信者のEメール
+
常にEメールを受信するユーザー（複数可）のEメールアドレスを指定します。複数のアドレスを指定する場合はカンマで区切ります。

** E メールの件名
+
通知の件名を指定します。

** Eメールの署名
+
Eメールの一番下に表示される情報（部署名など）を指定します。




