---
permalink: dwh/setting-up-multiple-tenancy-in-reporting.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight Data Warehouseでは、ユーザを1つ以上のビジネスエンティティに関連付けることで、Reportingでマルチテナンシーを実現できます。\この機能を使用すると、管理者は、ユーザー属性またはユーザーの所属に応じてデータまたはレポートを分離できます。 
---
= レポートにマルチテナンシーを設定しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight Data Warehouseでは、ユーザを1つ以上のビジネスエンティティに関連付けることで、Reportingでマルチテナンシー（「マルチテナンシー」または「マルチテナンシー」と略されることがあります）に対応します。この機能を使用すると、管理者は、ユーザー属性またはユーザーの所属に応じてデータまたはレポートを分離できます。

ビジネスエンティティでは、容量チャージバックの目的で次の値を使用して階層を使用します。

* テナント：主にサービスプロバイダがリソースをお客様（ネットアップなど）に関連付けるために使用します。
* 基幹業務（LOB）：企業内の基幹業務（「ハードウェア」や「ソフトウェア」など）。
* Business Unit：「Sales」や「Marketing」などの従来のビジネスユニット。
* Project：容量チャージバックを割り当てるプロジェクト。


マルチテナンシーを設定するプロセスの主な手順は次のとおりです。

* Data Warehouseユーザアカウントを設定
* Reporting Portalでグループを作成します。
* ユーザを1つ以上のグループ（ビジネスエンティティ）に割り当てます。
* ユーザを1つ以上のビジネスエンティティに割り当てます。たとえば、「NetApp」に関連付けられているユーザは、テナントとして「NetApp」を持つすべてのビジネスエンティティにアクセスできます。
* ユーザが表示する必要のあるレポートのみを表示できることをテストします。


次の点は、ユーザがレポートデータにアクセスする方法をまとめたものです。

* どのグループにも割り当てられていないユーザは、すべてのデータにアクセスできます。
* どのグループにも割り当てられているユーザは、ビジネスエンティティがないとレコードにアクセスできません。


たとえば、次の部門があり、これらの部門内のユーザに対してレポートを分離する必要があるとします。

|===


| ユーザ | エンジニアリング | サポート | 財務 | 法律 


 a| 
ユーザ 1
 a| 
X
 a| 
X
 a| 
 a| 



 a| 
ユーザ 2
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
ユーザー3
 a| 
 a| 
X
 a| 
 a| 

|===