---
permalink: howto/collecting-integration-data.html 
sidebar: sidebar 
keywords:  
summary: 統合データをOnCommand Insight システムにインポートできます。データは、パフォーマンスデータを収集するデーモンとして実行されるオープンソースソフトウェアcollectdを使用してインポートすることも、一般的なSNMPデータを収集できる統合SNMPデータソースを使用してインポートすることもできます。 
---
= 統合データを収集しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
統合データをOnCommand Insight システムにインポートできます。データは、パフォーマンスデータを収集するデーモンとして実行されるオープンソースソフトウェアcollectdを使用してインポートすることも、一般的なSNMPデータを収集できる統合SNMPデータソースを使用してインポートすることもできます。



== 統合データのデータフロー

次の環境 OnCommand Insight サーバに提供できる統合データの総量。

* 100コールのキューが維持されます。
+
クライアントがキュー内で1分以上待機すると、タイムアウトエラーが発生します。

* 統合データの推奨取り込み速度は、クライアントごとに1分あたり1回です。
* 使用できる統合オブジェクトタイプは300に制限されています。




== collectdソフトウェアおよびドキュメントへのアクセス

出力ライタープラグインソフトウェアおよびcollectdのドキュメントは、ネットアップのGitHubサイトから入手できます。 https://github.com/NetApp/OCI_collectd[]



== 統合データのバックアップとリストア

統合データのバックアップとリストアは、OnCommand Insight パフォーマンスデータのバックアップとリストアのポリシーに従ってモデル化されます。パフォーマンスデータのバックアップが設定されている場合は、統合データもバックアップに含まれます。パフォーマンスバックアップと同様に、最新7日間の統合データがバックアップに含まれます。バックアップに含まれている統合データは、リストア処理でリストアされます。



== ライセンス

統合データをレポートするには、Performライセンスが必要です。Performライセンスが存在しない場合、エラーが発生し、「Perform license required to report integration data」というメッセージが表示されます。
