---
permalink: howto/configuring-data-center-annotations.html 
sidebar: sidebar 
keywords:  
summary: データセンターのアノテーションは、通常、ストレージアレイ、スイッチ、または物理ホストのアセットをデータセンターの場所に関連付けるときに使用します。データセンターのアノテーションを環境内の他のアセットに関連付けることもできます。 
---
= データセンターのアノテーションの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データセンターのアノテーションは、通常、ストレージアレイ、スイッチ、または物理ホストのアセットをデータセンターの場所に関連付けるときに使用します。データセンターのアノテーションを環境内の他のアセットに関連付けることもできます。

手順

* 管理者権限を持つユーザとして Insight にログインします。
* [管理]*>*[アノテーション]*を選択します。
* [Data Center]*アノテーションを選択し、*[Edit]*アイコンをクリックします。
* [+Add]*をクリックし、最初のデータセンターの名前と概要 をアノテーションリストに追加します。
* 他のデータセンターについても同じ手順を実行します。
* 完了したら、*[保存]*をクリックします。


データセンターのアノテーションの例：

|===


| 名前 | 説明 


 a| 
DC1_SVL
 a| 
サニーベールビル1



 a| 
DC2_SVLb3
 a| 
SVL Bldg3エンジン



 a| 
DC3_NY
 a| 
ニューヨーク



 a| 
DC4_ロンドン
 a| 
ロンドン



 a| 
...
 a| 

|===
Insightには、ニーズに合わせて値を定義または変更できるアノテーションタイプがいくつか用意されています。これらのデフォルトのアノテーションタイプは、Insight Web UIとレポートで常に使用できます。新しく作成したカスタムアノテーションはInsight Web UIに表示されますが、レポートで使用できるようにするには追加の手順が必要です。レポートにカスタムアノテーションを含める方法については、を参照してください。ネットアップのカスタマーサポート担当者にお問い合わせください。

[NOTE]
====
ユーザによっては、アセットの場所をデータセンターのアノテーションではなく国のアノテーションで設定したり、データセンターのアノテーションと組み合わせて設定したりする傾向があります。ただし、国のアノテーションはInsight Data Warehouseではカスタムのアノテーションタイプとして扱われるため、データセンターと同じようにレポートに表示されない場合があります。

====