---
permalink: howto/configuring-applications-for-your-company.html 
sidebar: sidebar 
keywords:  
summary: 会社の環境で使用されているアプリケーションを把握しておくと、資産の使用状況を追跡し、コストを報告するのに役立ちます。ここでは、会社のアプリケーションを設定し、適切なアセットに関連付けます。 
---
= 会社のアプリケーションを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
会社の環境で使用されているアプリケーションを理解すると、資産の使用状況を追跡し、コストを報告するのに役立ちます。ここでは、会社のアプリケーションを設定し、適切なアセットに関連付けます。



== このタスクについて

「company_sectionのビジネスエンティティの設定」セクションでは、いくつかのビジネスエンティティを作成しました。それぞれのビジネスエンティティに関連付けるすべてのアプリケーションをリストアップすることを推奨します。OnCommand Insight を使用すると、使用状況やコストレポートなどのアプリケーションに関連するデータを追跡できます。

環境で実行されているアプリケーションに関連付けられているデータを追跡するには、まずそれらのアプリケーションを定義し、適切なアセットに関連付ける必要があります。アプリケーションを関連付けることができるアセットは、ホスト、仮想マシン、ボリューム、内部ボリューム、 qtree 、 共有、ハイパーバイザー：

このチュートリアルでは、マーケティングチームがExchange電子メールに使用する仮想マシンの使用状況を追跡します。ビジネスエンティティを定義する際に作成した次の表を覚えておいてください。このワークシートに列を追加して、各ビジネスエンティティで使用されているアプリケーションを表示します。（この表はあくまでワークシートの例です。Insightのビジネスエンティティテーブルに[Applications]列は表示されません）。

|===


| テナント | 基幹業務部門 | ビジネスユニット | プロジェクト | アプリケーション 


 a| 
ネットアップ
 a| 
データストレージ
 a| 
法律
 a| 
特許
 a| 
Oracle Identity Manager 、 Oracle On Demand 、 PatentBuy



 a| 
ネットアップ
 a| 
データストレージ
 a| 
マーケティング
 a| 
セールスイベント
 a| 
Exchange 、 Oracle 共有データベース、 BlastOff Event Planner



 a| 
該当なし
 a| 
該当なし
 a| 
安全とセキュリティ
 a| 
該当なし
 a| 
該当なし



 a| 
...
 a| 
 a| 
 a| 
 a| 

|===
* Insightでのアプリケーションの作成：*



== 手順

. 管理者権限を持つユーザとして Insight にログインします。
. [管理]*>*[アプリケーション]*を選択します
. [+追加]*ボタンをクリックします
. アプリケーションの名前を入力します（この例では、「Exchange」と入力します）。
. アプリケーションの優先度を選択します
. アプリケーションをビジネスエンティティに関連付ける場合は、*[Business Entity]*ドロップダウンから1つ選択します。それ以外の場合は、「なし」のままにしておくことができます。
. 各ホストがクラスタ内の同じボリュームにアクセスできるようにする場合は、*[ボリューム共有の検証]*ボックスがオンになっていることを確認します。たとえば、高可用性クラスタのホストは、フェイルオーバーを可能にするために同じボリュームにマスクする必要があることがよくありますが、無関係なアプリケーションのホストは通常、同じ物理ボリュームにアクセスする必要はありません。また、セキュリティ上の理由から、関係のないアプリケーションによる同じ物理ボリュームへのアクセスを明示的に禁止するように規制ポリシーで規定されている場合があります。ボリューム共有を使用しない場合は、*[ボリューム共有の検証]*ボックスの選択を解除します。これにはAssureライセンスが必要です。
. [ 保存 ] をクリックします .
. 環境内の他のすべてのアプリケーションについて、この手順を繰り返します。




== 完了後

マーケティングチームがExchangeアプリケーションを使用していることがわかります。ストレージの追加がいつ必要になるかを予測するために、Exchangeでの仮想マシンの使用率を確認したいと考えています。次に、ExchangeアプリケーションをマーケティングのすべてのVMに関連付けます。これを実現する最も簡単な方法は、クエリを使用することです。

次の手順に従って、各アプリケーションを適切なアセットに関連付けることができます。

*アセットへのアプリケーションの関連付け：*

これでアプリケーションが作成され（必要に応じてビジネスエンティティに関連付けられました）、これらのアプリケーションを環境内のアセットに関連付けることができます。この例では、Exchangeアプリケーションを社内の複数の仮想マシンに関連付けます。これを行う最も簡単な方法は、クエリです。

. [Queries]>[*+New query]*を選択します。
. [Select Resource Type]*ドロップダウンで、[_Virtual Machine_]を選択します
. ここでは、マーケティングチームがアセットの名前に文字列「`_mktg_`」を付けると仮定します。[Name]フィルタボックスに「`_mktg_`」（引用符なし）と入力し、[apply]（チェックマーク）ボタンをクリックします。
. 「_mktg_」という文字列を含むすべてのVMのリストが表示されます。
. 必要に応じて、* More *ドロップダウンをクリックし、フィルタを追加します。
. Exchangeに使用するVMをVM名の横にあるチェックボックスをクリックして選択するか、列の上部にあるチェックボックスをクリックしてすべてのVMを選択します。
. 目的のVMを選択したら、*[Actions]*ボタンをクリックし、*[Add Application]*を選択します。
. [Assign Application]ダイアログで、*[Application]*ドロップダウンをクリックし、「Exchange」を選択します。
. [ 保存（ Save ） ] をクリックします。
. 必要に応じてこの手順を繰り返して、Exchangeアプリケーションを他のアセット（ホスト、ボリュームなど）に関連付けます。

