---
permalink: howto/creating-a-performance-policy-for-alerting.html 
sidebar: sidebar 
keywords:  
summary: パフォーマンスポリシーを使用すると、監視し、特定の条件が満たされたときにアラートを送信できます。 
---
= アラート用のパフォーマンスポリシーを作成しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスポリシーを使用すると、監視し、特定の条件が満たされたときにアラートを送信できます。



== このタスクについて

これでアセットのアノテートが完了しました。次に、Sunnyvale（DC1_SVL）データセンターのいずれかのストレージアレイでレイテンシが2ミリ秒を超えたときにアラートを表示するためのパフォーマンスポリシーを作成します。このような状況が発生した場合は、選択した受信者にEメールを送信します。



== 手順

. [管理]*>*[パフォーマンスポリシー]*を選択します。
+
[パフォーマンスポリシー]ページが開きます。いくつかのデフォルトポリシーがすでに設定されており、必要に応じて変更できます。ただし、新しいポリシーを作成します。

. [+追加]*ボタンをクリックします。
+
[ポリシーの追加]*ダイアログが開きます。

. [ポリシー名]フィールドに「SVL Data Center Latency policy」と入力します。
+
オブジェクトの他のすべてのポリシーとは異なる名前を使用する必要があります。たとえば、内部ボリュームの「 Latency 」という名前の 2 つのポリシーを使用することはできませんが、内部ボリュームの「 Latency 」ポリシーと別のボリュームの「 Latency 」ポリシーを使用できます。ベストプラクティスとしては、オブジェクトタイプに関係なく、すべてのポリシーに一意の名前を常に使用することを推奨します。

. [タイプのオブジェクトに適用]*で、*[ストレージ]*を選択します。
. [WITH ANNOTATION]*フィールドで、*[Data Center]*は「DC1_SVL」を選択します（または、ここで目的のデータセンターの名前を選択します）。
. *最初の発生*のウィンドウの後に適用します。
+
[First occurrence]オプションを指定すると、最初のデータサンプルでしきい値を超えたときにアラートがトリガーされます。それ以外のオプションでは、しきい値を超えたあと、その状態のまま一定の時間を経過した時点でアラートがトリガーされます。

. [重大度*あり]リストから*[警告]*を選択します。
. [Eメール受信者]*で、をクリックしてグローバル受信者リストを上書きします。**+**をクリックして最初に希望するアラート受信者のメールアドレスを追加し、*OK*をクリックします。他のEメール受信者についても、同じ手順を繰り返します。
. [Create alert if * any* of the following are true]はデフォルトの選択のままにします。これにより、設定されたいずれかのしきい値に達した場合にアラートが送信されます。設定されたしきい値の*すべて*を満たした場合にのみアラートを送信するように選択することもできます。
. 最初のしきい値を設定するには、ドロップダウンで* Latency - Total *を選択し、2ミリ秒を超える値に設定します。
. 必要に応じて、*[Add threshold]*ボタンをクリックして、アラートの対象となるしきい値を追加します。ポリシーを希望どおりにカスタマイズしたら、*[保存]*をクリックします。
. [Stop processing further policies if alert is generated]を選択することもできます。これにより、このポリシーの条件が満たされると、追加のポリシーアラートが停止します。
. 新しいポリシーを必要な数だけ追加して、ビジネスニーズに応じてさまざまな条件に基づいて他の受信者にアラートを設定できます。特定の受信者を指定せずに設定されたポリシーは、* Admin *>* Notifications *ページで設定されたグローバル受信者リストにアラートを送信します




== 完了後

新しいポリシーはそれぞれ保存時に自動的にアクティブ化され、ポリシーの条件（_violation_）が満たされると受信者にアラートが送信されます。これらの違反は、*[Dashboards]*>*[Violations Dashboard]*で監視することもできます。
