---
permalink: howto/creating-policies-and-thresholds-for-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: パフォーマンスポリシーを作成して、ストレージプールのアセットのしきい値を超えたときに通知するアラートをトリガーすることができます。 
---
= ストレージプールのパフォーマンスポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスポリシーを作成して、ストレージプールのアセットのしきい値を超えたときに通知するアラートをトリガーすることができます。



== 作業を開始する前に

この手順は、ストレージプールがシンプロビジョニングされていることを前提としています。



== このタスクについて

停止につながる可能性のあるストレージプールの変更を監視してレポートするポリシーを作成する。シンプロビジョニングされた物理ストレージプールでは、物理容量を監視し、オーバーコミット率を監視します。



== 手順

. ブラウザでOnCommand Insight を開きます。
. [管理]*>*[パフォーマンスポリシー]*を選択します
+
パフォーマンスポリシーページが表示されます。ポリシーはオブジェクト別に表示され、リストに表示されている順序で評価されます。通知が有効になっている場合（* Admin *>* Notifications *）、パフォーマンスポリシーに違反したときにEメールを送信するようにInsightを設定できます。

. [**+追加*]をクリックして、新しいポリシーを作成します。
. [ポリシー名]*に、ストレージプールのポリシー名を入力します。
. [タイプのオブジェクトに適用]*で[ストレージプール]を選択します。
. [ * Apply after window of * ] に、最初のオカレンスを入力する。
. [* （ * ） ] に重大度 * を入力します
. しきい値を超えたときに通知を受け取る E メール受信者を設定します。
+
デフォルトでは、ポリシー違反に関する E メールアラートはグローバル E メールリストの受信者に送信されます。この設定を上書きして、特定のポリシーのアラートを特定の受信者に送信するように設定することができます。

+
リンクをクリックして受信者リストを開き、 [+] ボタンをクリックして受信者を追加します。このポリシーに関する違反のアラートがリスト内のすべての受信者に送信されます。

. * 次のいずれかに該当する場合はアラートを作成します。 * 容量比率を入力してください - 使用済み >85%




== 結果

この構成では、ストレージプールの物理容量の 85% を超える容量が使用されている場合に、重大な警告メッセージが送信されます。物理メモリの 100% を使用すると、アプリケーションに障害が発生します。



== 追加のストレージプールポリシーを作成します



=== このタスクについて

追加の「容量比率-使用済み」ポリシーを作成します。このポリシーを使用すると、ストレージプールの使用済み容量が75%を超えたときに警告メッセージが表示されます。通知が有効になっている場合（* Admin *>* Notifications *）、パフォーマンスポリシーに違反したときにEメールを送信するようにInsightを設定できます。
