---
permalink: howto/creating-performance-policies-for-datastores.html 
sidebar: sidebar 
keywords: performance policy,Datastore 
summary: 監視対象のストレージプールに関連するデータストアに関連付けられた指標のしきい値を設定したパフォーマンスポリシーを作成できます。デフォルトでは、パフォーマンスポリシーは作成時に指定したタイプのすべてのデバイスに適用されます。特定のデバイスまたはデバイスセットのみをパフォーマンスポリシーに含める場合は、アノテーションを作成します。 
---
= データストアのパフォーマンスポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監視対象のストレージプールに関連するデータストアに関連付けられた指標のしきい値を設定したパフォーマンスポリシーを作成できます。デフォルトでは、パフォーマンスポリシーは作成時に指定したタイプのすべてのデバイスに適用されます。特定のデバイスまたはデバイスセットのみをパフォーマンスポリシーに含める場合は、アノテーションを作成します。



== 作業を開始する前に

パフォーマンスポリシーでアノテーションを使用する場合、ポリシーを作成する前にアノテーションが存在している必要があります。



== このタスクについて

監視しているデータストアが設定したしきい値を超えたときに通知するパフォーマンスポリシーを作成します。必要に応じてグローバルポリシーがすでにシステムに含まれている場合や、データストアにアノテーションをアノテートする場合はアノテーションを使用するポリシーも機能する場合があります。



== 手順

. Insightのツールバーで、*[管理]*>*[パフォーマンスポリシー]*を選択します
+
パフォーマンスポリシーページが表示されます。既存のパフォーマンスポリシーを確認し、監視するしきい値の指標に対応する既存のポリシーを特定します。

. [+追加]*をクリックして新しいポリシーを追加します
. 「ポリシー名」を追加します。
+
オブジェクトの他のすべてのポリシーとは異なる名前を使用する必要があります。たとえば、「Latency」という名前の2つのポリシーを内部ボリュームに使用することはできませんが、内部ボリュームには「Latency」ポリシー、データストアには「Latency」ポリシーを使用できます。ベストプラクティスとしては、オブジェクトタイプに関係なく、すべてのポリシーに一意の名前を常に使用することを推奨します。

. オブジェクトタイプとして「 Datastore 」を選択します
. "`First occurrence`"をクリックします。
+
[First occurrence]オプションを指定すると、最初のデータサンプルでしきい値を超えたときにアラートがトリガーされます。それ以外のオプションでは、しきい値を超えたあと、その状態のまま一定の時間を経過した時点でアラートがトリガーされます。

. 「警告」をクリックします。
. 「アラートの作成」では、* Capacity ratio-over commit *を選択し、*> 150 *に設定します
+
容量に関連するアラート（**Capacity total**やCapacity Used*など）を追加で作成することもできます。


