---
permalink: howto/custom-dashboard-roll-up.html 
sidebar: sidebar 
keywords:  
summary: ダッシュボードウィジェットに表示されるデータは、取得したデータポイントを集計したもので、ダッシュボードを柔軟かつ簡潔に表示できます。 
---
= ロールアップと集約
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ダッシュボードウィジェットに表示されるデータは、取得したデータポイントを集計したもので、ダッシュボードを柔軟かつ簡潔に表示できます。

各ウィジェットに表示されるデータは、収集中に収集された基盤となるデータポイントの集計です。たとえば、ストレージ IOPS の経過を示す折れ線グラフでは、データセンターごとにグラフ線を表示してデータをすばやく比較できます。このデータは、次のいずれかの方法で集計できます。

* * Avg * ：収集されたデータの平均値として各行を表示します。
* * 最大 * ：各行を基になるデータの _maximum_ として表示します。
* * 最小 * ：各行を基になるデータの _minimum_ として表示します。
* * 合計 * ：各行を基になるデータの _SUM_( 合計 ) として表示します。


そのためには、ウィジェットのクエリで、最初にアセットタイプ（_Storage_など）と指標（__IOPS-Tota__lなど）を選択します。[Roll up]*で、集計方法（_avg_など）を選択し、データの集計に使用する属性またはアノテーション（_Data Center_など）を選択します。ウィジェットが自動的に更新され、各データセンターの線が表示されます。

収集されたデータの_all_をグラフまたは表に集計することもできます。この場合、ウィジェットのクエリごとに1本の線が表示され、収集されたすべてのアセットについて、選択した指標の平均値、最小値、最大値、または合計値が表示されます。

クエリにフィルタを設定している場合は、フィルタされたデータに基づいて集計されます。

任意のフィールド（_Model_など）でウィジェットを集計する場合でも、そのフィールドのデータをグラフまたは表に正しく表示するには、そのフィールドのデータを* Filter by *で絞り込む必要があります。

*データの集計：*データポイントを分、時間、日のバケットに集計してから（選択した場合）データを属性別に集計することで、時系列グラフ（折れ線、領域など）をさらに調整できます。データポイントは、[Avg]、[Max]、[Min]、[Sum]のいずれかに基づいて集計するか、選択した間隔で収集された[Last data]ポイントで集計するかを選択できます。集計方法を選択するには、ウィジェットの「クエリ」セクションで「その他のオプション」をクリックします。

指定できる最小間隔は10分です。短い間隔と長い時間範囲を組み合わせると、「集計間隔の結果、データポイントが多すぎます」という結果になることがあります。 警告。間隔が短い場合は、ダッシュボードの期間を 7 日に延長するとこのように表示されることがあります。この場合、より短い期間を選択するまで、集約間隔は一時的に1時間に延長されます。

棒グラフウィジェットおよび単一値ウィジェットでデータを集約することもできます。

ほとんどのアセットカウンタは、デフォルトでは _Avg_ に集約されます。一部のカウンタは、デフォルトで_Max_、_Min_、または_Sum_に集約されます。たとえば、デフォルトでは、ポートエラーでアグリゲートは _sum に、ストレージ IOPS アグリゲートは _Avg_ になります。
