---
permalink: howto/custom-dashboard-concepts.html 
sidebar: sidebar 
keywords:  
summary: カスタムダッシュボードとウィジェットを使用すると、データの表示方法を柔軟に変更できます。ここでは、カスタムダッシュボードを最大限に活用するのに役立つ概念をいくつか紹介します。各概念については、以降のセクションで詳しく説明します。 
---
= カスタムダッシュボードの概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
カスタムダッシュボードとウィジェットを使用すると、データの表示方法を柔軟に変更できます。ここでは、カスタムダッシュボードを最大限に活用するのに役立つ概念をいくつか紹介します。各概念については、以降のセクションで詳しく説明します。

* 変数 *

変数を使用すると、ダッシュボードの一部またはすべてのウィジェットに表示するデータを一度に変更できます。各ウィジェットで共通の変数を使用するように設定することで、1か所で行われた変更は、各ウィジェットに表示されているデータを原因 して自動的に更新します。

*複数のクエリおよび/または式*

各時系列ウィジェット（折れ線グラフ、スプライングラフ、面グラフ、積み上げ面グラフ）には、表示するデータを決定するクエリや式を最大5つ設定でき、1つのグラフで異なるデータセットを比較できます。たとえば、折れ線グラフにストレージとVMの両方のIOPSを表示したり、すべてのストレージプールのスループットとレイテンシを1つのグラフで比較したりできます。

*ロールアップとグループ化*

各ウィジェットに表示されるデータは、収集されたデータポイントを集計したものです。このデータは、次のいずれかの方法で集計できます。

* Avg：収集されたデータの平均値を集計します
* Max：収集されたデータの最大値を集計します
* Min：収集されたデータの最小値を集計します
* Sum：収集されたデータの合計を集計します


デフォルトでは、収集されたすべてのデータが集計されて1つのエントリ（すべて）としてグラフまたは表に表示されます。データセンターや階層などの特定の属性のデータを集計して、必要なグループにデータを分散することもできます。ウィジェットには、選択した属性のデータのみが表示されます。

表ウィジェットでは、選択した属性に応じてデータをグループ化できます。たとえば、テーブルをデータセンター別にグループ化できます。グループは自由に展開または折りたたむことができます。表内のパフォーマンスデータは、ウィジェットで設定した集計方法（平均、最大、最小、または合計）に従ってグループヘッダーに集計されます。

表ウィジェットは任意の列でソートでき、列は必要に応じて移動またはサイズ変更できます。

*上/下*

グラフウィジェットの結果セットを制限したり、ウィジェットに上位N件の結果を表示するか、下位N件の結果を表示するかを選択したりする場合に使用します。このオプションは、データがロールアップされていない場合、または特定の属性別にロールアップされている場合に選択できます。

*ダッシュボード時間を上書き*

デフォルトでは、ダッシュボードに追加するほとんどのウィジェットには、ダッシュボードの時間範囲設定（3h、24h、3d、7d、30d、またはカスタムの範囲）に従ってデータが表示されます。ただし、この時間設定を個 々 のウィジェットで無効にして、ダッシュボードの時間設定に関係なく、特定の期間のデータを強制的に表示することができます。

これらの概念については、次のセクションで詳しく説明します。
