---
permalink: howto/custom-dashboards.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 7.3には、ユーザにとって重要なデータの運用ビューと、そのデータのワンストップビューを提供する、強化されたカスタムダッシュボード機能が含まれています。 
---
= カスタムダッシュボードの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 7.3には、ユーザにとって重要なデータの運用ビューと、そのデータのワンストップビューを提供する、強化されたカスタムダッシュボード機能が含まれています。

OnCommand Insight では、さまざまなウィジェットを使用してカスタムダッシュボードを作成できるため、ITプラットフォーム全体でインフラデータの運用ビューを柔軟に作成でき、それぞれのダッシュボードでデータの表示とグラフ化を柔軟に行うことができます。このハウツーでは、VMのパフォーマンスを強調するダッシュボードの例を作成します。

このハウツーはあくまでも例であり、すべてのシナリオを網羅しているわけではありません。ここで説明する概念と手順を使用して、特定のニーズに固有のデータを強調する独自のカスタムダッシュボードを作成できます。

* 概要 *

カスタムダッシュボードは、次のいずれかの方法で作成します。

* *ダッシュボード*>*+新しいダッシュボード*
* *[Dashboards]*>*[Show all dashboards]*をクリックし、*[+Add]*をクリックします


[New Dashboard]画面にはいくつかのコントロールがあります。

* *時間セレクタ*：カスタムの日付範囲セレクタを使用して、3時間から90日間の範囲のダッシュボードデータを表示できます。ウィジェットごとにこのグローバルな期間を無効にすることができます。
* *編集*ボタン:「オン」を選択すると編集モードが有効になり、ダッシュボードに変更を加えることができます。新しいダッシュボードは、デフォルトで編集モードで開きます。
* *保存*ボタン：ダッシュボードを保存、名前変更、または削除できます。
* *変数*ボタン：変数をダッシュボードに追加できます。変数を変更すると、すべてのウィジェットが一度に更新されます。変数の詳細については、を参照してください link:custom-dashboard-concepts.md#["カスタムダッシュボードの概念"]
* *ウィジェット*ボタン。任意の数の表、グラフ、またはその他のウィジェットをダッシュボードに追加できます。


ウィジェットは、サイズを変更したり、ダッシュボード内で別の位置に移動したりすることで、現在のニーズに合わせてデータを見やすくすることができます。

*ウィジェットタイプ*

次のタイプのウィジェットから選択できます。

*表*ウィジェット：選択したフィルタおよび列に従ってデータを表示する表。テーブルデータは、グループにまとめて、折りたたんだり展開したりすることができます。

*折れ線グラフ、スプライングラフ、面積グラフ、積み上げ面グラフ*：時系列グラフウィジェットで、パフォーマンスやその他のデータを経時的に表示できます。

*単一値*ウィジェット：カウンタから直接取得することも、クエリや式を使用して計算することもできる単一の値を表示するウィジェットです。たとえば、環境内のすべてのストレージの合計IOPSをダッシュボードの上部に1つの値として表示できます。

*棒グラフ：上位または下位の5、10、20、または50の値を表示するグラフ。

* Box Plot * chart：1つのチャートのデータの最小、最大、中央値、および下位4分の1と上位4分の1の範囲のプロット。

*散布図*グラフ：IOPSやレイテンシなど、関連するデータをポイントとしてプロットします。この例では、レイテンシが高くIOPSが低いアセットを簡単に確認できます。

また、選択できるレガシーウィジェットも多数あります。[*Widgets*]ドロップダウンで[** Show More...*]を選択すると、これらのウィジェットが表示されます。
