---
permalink: howto/expressions-example-system-i-o.html 
sidebar: sidebar 
keywords:  
summary: 式を使用すると、他の指標から計算できるデータを自由にグラフ化できます。 
---
= 式の例：システム I/O
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
式を使用すると、他の指標から計算できるデータを自由にグラフ化できます。



== このタスクについて

例2：OnCommand Insight はデータソースから多数の指標を取得します。その中には、読み取り、書き込み、合計IOPSがあります。ただし、収集によって報告されるIOPSの合計に「システム」IOPSが含まれることがあります。これは、データの読み取りや書き込みの直接的な一部ではないI/O処理です。このシステム I/O はオーバーヘッド I/O と考えることもできますが、適切なシステム運用には必要ですが、データの運用には直接関係しているわけではありません。

これらのシステム I/O を表示するには、収集によって報告された合計 IOPS から読み取り IOPS と書き込み IOPS を差し引きます。式は次のようになります。

* システムIOPS =合計IOPS -（読み取りIOPS +書き込みIOPS）


このデータは、ダッシュボードに折れ線グラフで表示できます。これを行うには、次の手順を実行します。



== 手順

. 新しいダッシュボードを作成するか、既存のダッシュボードを*編集モード*で開きます。
. ダッシュボードにウィジェットを追加します。「 * 線グラフ * 」を選択します。
+
ウィジェットが編集モードで開きます。デフォルトでは、*ストレージ*アセットの* IOPS -合計*を示すクエリが表示されます。必要に応じて、別のアセットタイプを選択します。

. ボタンをクリックして、クエリのコピーを作成します。
+
重複するクエリが元のクエリの下に追加されます。

. 2 番目のクエリで、 * 式に変換 * ボタンをクリックします。
+
現在のクエリが式モードに変換されます。いつでもクエリモードに切り替えるには、 [ クエリに戻る ] をクリックします。モードを切り替えるとフィールドがデフォルトにリセットされるので注意してください。

+
ここでは、* Expression *モードのままにします。

. [IOPS - Total]*指標がアルファベット変数フィールド「`a'」に表示されるようになりました。[IOPS - Total]*をクリックし、*[IOPS - Read]*に変更します。。
. [`b`]変数フィールドで、*[Select]*をクリックし、*[IOPS - Write]*を選択します。
. [*Expression*] フィールドでは、各変数に対応する文字を使用して式を作成します。ここでは、単純に次のように式を記述します。 `a + b`。[*Display*]セクションで、この式に[** Area chart*]を選択します。
. *Label* フィールドは、式を識別します。ラベルを「システムIOPS」に変更するか、同等の意味のあるものに変更します。
+
合計 IOPS の折れ線グラフが表示され、その下に読み取り IOPS と書き込み IOPS を組み合わせた面グラフが表示されます。この 2 つのグラフの間が、データの読み取り処理や書き込み処理に直接関係していない IOPS を表します。

. グラフをダッシュボードに保存するには、 * 保存 * をクリックします。

