---
permalink: howto/expressions-example-read-iops-percentage.html 
sidebar: sidebar 
keywords:  
summary: 式を使用すると、合計に対する割合など、別の方法で指標を表示できます。 
---
= 式の例：読み取りIOPSの割合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
式を使用すると、合計に対する割合など、別の方法で指標を表示できます。



== このタスクについて

この例では、合計IOPSに占める読み取りIOPSの割合を表示します。これは次の式と考えることができます。

* 読み取りの割合=（読み取りIOPS /合計IOPS）x 100


このデータは、ダッシュボードに折れ線グラフで表示できます。これを行うには、次の手順を実行します。



== 手順

. 新しいダッシュボードを作成するか、既存のダッシュボードを*編集モード*で開きます。
. ダッシュボードにウィジェットを追加します。[* Area chart* （エリアグラフ * ） ] を
+
ウィジェットが編集モードで開きます。デフォルトでは、*ストレージ*アセットの* IOPS -合計*を示すクエリが表示されます。必要に応じて、別のアセットタイプを選択します。

. [Convert to Expression]*ボタンをクリックします。
+
現在のクエリが式モードに変換されます。式モードのときはアセットタイプを変更できません。式モードでは、ボタンが*[クエリに戻す]*に変わります。いつでもクエリモードに切り替えるには、このボタンをクリックします。モードを切り替えるとフィールドがデフォルトにリセットされるので注意してください。

+
ここでは、* Expression *モードのままにします。

. [IOPS - Total]*指標がアルファベット変数フィールド「`a'」に表示されるようになりました。[`b`]変数フィールドで、*[Select]*をクリックし、*[IOPS - Read]*を選択します。
+
変数フィールドの後にある**+**ボタンをクリックすると、式に合計5つのアルファベット変数を追加できます。読み取りの割合の例では、合計IOPS（「a」）と読み取りIOPS（「b」）のみが必要です。

. [*Expression*] フィールドでは、各変数に対応する文字を使用して式を作成します。読み取りIOPSの割合=（読み取りIOPS /合計IOPS）x 100_であることがわかっているため、次のように式を書きます。 `(b / a) * 100`
. *Label* フィールドは、式を識別します。ラベルを"`Read Percentage`"に変更するか、同様に意味のあるものに変更してください。
. * Units *フィールドを"`%`"または"`percent`"に変更します。
+
グラフに、選択したストレージデバイスの読み取り IOPS の割合が時系列で表示されます。必要に応じて、フィルタを設定するか、別の集計方法を選択できます。集計方法として* Sum *を選択すると、すべてのパーセント値が合計され、100%を超える可能性があることに注意してください。

. グラフをダッシュボードに保存するには、 * 保存 * をクリックします。
+
*折れ線グラフ*、*スプライングラフ*、または*積み上げ面グラフ*ウィジェットでも式を使用できます。


