---
permalink: howto/host-and-vm-filesystem-utilization.html 
sidebar: sidebar 
keywords: filesystem 
summary: Host and VM File SystemsデータソースとHost Utilizationライセンスを組み合わせることで、既知のホストおよびVMについて、ファイルシステムレベルでのレポートとチャージバックを作成できます。 
---
= ホストおよびVMのファイルシステム使用率データを収集しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Host and VM File SystemsデータソースとHost Utilizationライセンスを組み合わせることで、既知のホストおよびVMについて、ファイルシステムレベルでのレポートとチャージバックを作成できます。

OnCommand Insight はストレージデバイスからデータを収集します。ストレージデバイスのほとんどは、ボリュームをブロックデバイスとして報告します。これにより、Insightではストレージレベルで利用率をレポートできますが、ファイルシステムレベルではレポートできません。ストレージアレイは通常、書き込まれたブロックを認識しますが、解放されたブロックは認識しません。

クライアントホストとVMがファイルシステムを実装（NTFS、ext *...） これらのブロックデバイスの上にあります。ほとんどのファイルシステムは、ディレクトリとファイルのメタデータを含む目次を保持しています。ファイルが削除されると、そのエントリは目次から単純に削除されます。これらのファイルによって使用されたブロックはファイルシステムによる再利用の対象になりますが、ストレージアレイは再利用を認識しません。Insightでファイルシステムの使用状況をレポートするには、正確なチャージバックを実現するために、ファイルシステムをクライアントホストまたはVMの観点から収集する必要があります。

Insightでは、* NetApp Host and VM File System *データソースと* Host Utilization *ライセンスを組み合わせて、このレベルのファイルシステム利用率データを収集できます。コストが正確にレポートされるように、VMには適切な* Compute Resource Group *という名前を付け、関連するストレージアレイには適切な*階層*のアノテーションを適切なコストでアノテートする必要があります。

[NOTE]
====
Host Utilizationライセンスは、Insightの他のライセンスとは異なり、容量ベースのライセンスではなく、リソースベースのライセンスです。

====