---
permalink: howto/how-to-troubleshoot-fibre-channel-bb-credit-0-errors.html 
sidebar: sidebar 
keywords:  
summary: ファイバチャネルでは、バッファ間クレジット（BBクレジット）を使用して転送フローが制御されます。クレジット値はポートからフレームが送信されると減少し、ポートが応答を受信すると補充されます。ポートのBBクレジットが補充されないと、伝送フローが影響を受ける可能性があります。ポートには、フレームが順番に組み立てられて配信されるまで、一時的にフレームを保存するためのメモリ（バッファ）が必要です。バッファの数はポートが格納できるフレームの数であり、バッファクレジットと呼ばれます。 
---
= ファイバチャネルのBBクレジット0エラーのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイバチャネルでは、バッファ間クレジット（BBクレジット）を使用して転送フローが制御されます。クレジット値はポートからフレームが送信されると減少し、ポートが応答を受信すると補充されます。ポートのBBクレジットが補充されないと、伝送フローが影響を受ける可能性があります。ポートには、フレームが順番に組み立てられて配信されるまで、一時的にフレームを保存するためのメモリ（バッファ）が必要です。バッファの数はポートが格納できるフレームの数であり、バッファクレジットと呼ばれます。

特定のポートで使用可能なクレジットが0に近づくと、0に達するとポートが送信を停止し、BBクレジットが補充されるまで再開しないという警告が表示されます。

Insightのパフォーマンスポリシーでは、次のポート指標にしきい値を設定できます。

|===


 a| 
BBクレジットゼロ-受信



 a| 
サンプリング期間中に受信バッファ間クレジット数がゼロになった回数



 a| 
BBクレジットゼロ-転送



 a| 
サンプリング期間中に送信のバッファ間クレジット数がゼロになった回数



 a| 
BBクレジットゼロ-合計



 a| 
接続されているポートで提供できるクレジットを使い果たしたために、このポートが送信を停止した回数



 a| 
BBクレジットゼロ期間-治療



 a| 
サンプリング期間中にTx BBクレジットがゼロだった時間（ミリ秒）

|===
BBクレジットエラーは、次のような状況が原因で発生する可能性があります。

* 比率の高いFCフレームのサイズが最大サイズよりも大幅に小さい場合は、BBクレジットの追加が必要になる可能性があります。
* 環境におけるワークロードの変化により、ワークロードに接続されているポートやデバイス（ストレージノードなど）に影響が及ぶ可能性があります。


ファブリック、スイッチ、およびポートアセットのページを使用して、Fibre Channel環境を監視できます。ポートアセットページには、リソースに関する概要情報、トポロジ（デバイスとその接続）、パフォーマンスチャート、および関連するリソースの表が表示されます。ファイバチャネルの問題のトラブルシューティングでは、各ポートアセットのパフォーマンスグラフに影響が大きいポートのトラフィックが表示されるため、このグラフが役立ちます。ポートアセットのページには、バッファ間クレジットの指標とポートエラーも表示されます。Insightでは、指標ごとに個別のパフォーマンスチャートが表示されます。
