---
permalink: howto/introduction-to-root-volume-isolation.html 
sidebar: sidebar 
keywords:  
summary: ネットアップストレージシステムでは、ルートアグリゲートにルートボリュームが含まれています。ルートボリュームには、ストレージシステムを管理および制御するための特別なディレクトリと構成ファイルが格納されています。管理処理と制御処理によって、ルートアグリゲートで大量のアクティビティが発生する可能性があります。InsightシステムでIO密度が高い上位10個の内部ボリュームを照会すると、結果にはネットアップのルートアグリゲートが上位10個のメンバーとして含まれることがあります。 
---
= I/O 密度レポートに内部データボリュームのみが記載されていることを確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットアップストレージシステムでは、ルートアグリゲートにルートボリュームが含まれています。ルートボリュームには、ストレージシステムを管理および制御するための特別なディレクトリと構成ファイルが格納されています。管理処理と制御処理によって、ルートアグリゲートで大量のアクティビティが発生する可能性があります。InsightシステムでIO密度が高い上位10個の内部ボリュームを照会すると、結果にはネットアップのルートアグリゲートが上位10個のメンバーとして含まれることがあります。

環境を監視する際には、どの内部データボリュームが高い I/O 密度を生成しているかを特定することが重要です。データボリュームだけを正確に特定するには、ネットアップの内部ボリュームを、 I/O 密度の監視に使用するクエリから分離する必要があります。

このガイドでは、ネットアップのルートアグリゲートを簡単に特定し、それらを内部ボリュームのクエリの結果から分離する方法と、システムにネットアップの新しいルートアグリゲートが追加されるたびにそれらを除外するルールを作成する方法について説明します。I/O密度レポートを内部データボリュームから取得するには、Insightの次の機能を使用します。

* Insight で監視しているネットアップのルートアグリゲートを特定するクエリを作成する。
* ネットアップのルートアグリゲートのそれぞれにアノテーションを割り当てる。
* ネットアップのアグリゲートを除外するアノテーションルールを作成します

