---
permalink: howto/more-on-dashboard-variables.html 
sidebar: sidebar 
keywords:  
summary: ダッシュボードの変数にはいくつかの種類があり、さまざまなフィールドで使用できます。また、命名規則もあります。ここでは、これらの概念について説明します。 
---
= ダッシュボードの変数の詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ダッシュボードの変数にはいくつかの種類があり、さまざまなフィールドで使用できます。また、命名規則もあります。ここでは、これらの概念について説明します。



== 変数の型

変数には、次のタイプがあります。

* テキスト * ：英数字の文字列。これがデフォルトの変数タイプです。

* 数値 * ：数値または数値の範囲。

* Boolean *：True/False、Yes/No、0/1などの値を持つフィールドに使用します ブール変数の場合、選択肢は_Yes_、_No_、_None_、_Any_です。

* 日付 * ：日付または日付の範囲。



== 「汎用」変数

汎用変数または汎用変数を設定するには、*変数*ボタンをクリックし、上記のいずれかのタイプを選択します。これらのタイプは常にドロップダウンリストの上部に表示されます。変数にはデフォルトの名前（例：「$var1」）が付けられ、特定のアノテーションや属性には関連付けられません。

汎用変数を設定すると、ウィジェットでその変数を使用して、そのタイプの_any_fieldをフィルタリングできます。たとえば、_Name_、_Alias_、および_Vendor_（すべてテキストタイプの属性）を表示する表ウィジェットがあり、「$var1」がテキストタイプの変数である場合、ウィジェット内のこれらのフィールドごとに$var1変数を使用するフィルタを設定できます。他のウィジェットでも、テキストフィールドに $var1 を使用するように設定できます。

ダッシュボードページで、$var1に値（「`netapp`」など）を設定すると、その変数を使用するように設定された_all_widgets内のフィールドの_all_がフィルタリングされます。これにより、ダッシュボードで選択したデータを複数のウィジェットで一度に更新できます。

汎用的な変数はその型のどのフィールドでも使用できるので、その機能を変更することなく汎用的な変数の名前を変更できます。

[NOTE]
====
すべての変数は、特定の属性に対して作成したものであっても、「汎用」変数として扱われます。これは、そのタイプの属性またはアノテーションに対してフィルタを設定すると、そのタイプの設定済み変数がすべて表示されるためです。ただし、汎用変数を使用して複数のフィールドにわたって値をフィルタリングする場合は、上記の_Name/Alias/Vendor_Exampleのように汎用変数を作成することを推奨します。

====


== 変数の命名規則

変数名：

* 常に先頭に"$`"を付ける必要があります。これは、変数を設定するときに自動的に追加されます。
* 特殊文字は使用できません。使用できるのは、 a~z のアルファベットと 0~9 の数字のみです。
* 「$」記号を含めて20文字以内にする必要があります。
* 大文字と小文字は区別されません。$CityNameと$CityNameは同じ変数です。
* 既存の変数名と同じにすることはできません。
* "$`"記号だけにすることはできません。




== 変数を使用するウィジェット

変数は次のウィジェットで使用できます。

* エリアチャート
* 棒グラフ
* ボックスプロットグラフ（ Box Plot Chart ）
* 折れ線グラフ
* 散布図
* 単一値ウィジェット
* スプライングラフ（ Spline Chart ）
* 積み上げ面グラフ
* 表ウィジェット

