---
permalink: howto/using-performance-policies-to-reduce-risk-in-thin-provisioning.html 
sidebar: sidebar 
keywords:  
summary: 仮想インフラのしきい値を超えたときにアラートを生成するには、パフォーマンスポリシーを作成する必要があります。アラートを使用すると、原因が処理を中断または停止する前に、環境内の変更に対応できます。 
---
= パフォーマンスポリシーを使用してシンプロビジョニングのリスクを軽減する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想インフラのしきい値を超えたときにアラートを生成するには、パフォーマンスポリシーを作成する必要があります。アラートを使用すると、原因が処理を中断または停止する前に、環境内の変更に対応できます。

仮想インフラの監視に役立つポリシーは次のとおりです。

* *データストア*
+
データストアでは次のポリシーを使用できます。

+
** 容量比率 - オーバーコミット
** 容量比率 - 使用済み
** Capacity - 使用済みです
** 容量 - 合計


* *ストレージプール*
+
シンプロビジョニング環境では、次のポリシーを使用してストレージに関連する容量の停止を防ぐことができます。

+
** プロビジョニング済み容量
** 使用済みパフォーマンス容量
** 容量比率 - オーバーコミット
** 容量比率 - 使用済み




これらのポリシーから拡張して、次のような仮想インフラストラクチャの容量を監視できます。

* 内部ボリューム
* LUN
* ディスク
* VMDK
* 仮想マシン


ポリシーはアノテーションを使用して設定できます。アプリケーションをサポートする特定のアセットに同じアノテーションを割り当てる。たとえば、データストアにアノテーションを割り当てたり、シンプロビジョニングアプリケーションのストレージプールにアノテーションを割り当てたりできます。本番環境用の Production というアノテーション、開発環境用の Development などのアノテーションを設定することができます。アセットがサポートしているアプリケーションのタイプに応じて、しきい値や警告の重要度を変更することができます。たとえば、本番アプリケーションのデータストアのしきい値に違反すると_critical warning_が発生し、開発環境でも同じ違反で_warning_のみが発生する可能性があります。定義済みのポリシーにアノテーションを組み込むと、重要度の低いアセットに関する不要なアラート通知をさらに削減できます。
