---
sidebar: sidebar 
permalink: task_config_telegraf_dcos.html 
keywords: telegraf, installation, install, dcos 
summary: DCOS コンフィギュレーション 
---
= DC/OS データコレクタ
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights は、このデータコレクタを使用して DC/OS からのメトリックを収集します。



== インストール

. [Observability]>[Collectors]*で、*+ Data Collector *をクリックします。[*DC/OS*]を選択します。
+
収集用にエージェントを設定していない場合は、にプロンプトが表示されます link:task_config_telegraf_agent.html["エージェントをインストールします"] お客様の環境で実現します。

+
エージェントがすでに設定されている場合は、適切な OS またはプラットフォームを選択し、 [* Continue （続行） ] をクリックします。

. データコレクタを設定するには、 [DC/OS Configuration] 画面の指示に従います。手順は、データの収集に使用するオペレーティングシステムまたはプラットフォームのタイプによって異なります。




== セットアップ（ Setup ）

セットアップ情報は、で確認できます https://docs.mesosphere.com["DC/OS のドキュメント"]。



== オブジェクトとカウンタ

次のオブジェクトとそのカウンタが収集されます。

[cols="<.<,<.<,<.<,<.<"]
|===
| オブジェクト | 識別子 | 属性（ Attributes ） | 「 dataPoints 」： 


| DCOS_node | dcos_containerです
DCOS_APP | クラスタ
ホスト名
パス（ファイルシステムフィールドのみ）
インターフェイス（ネットワークフィールドのみ）
container_id
task_name（タスク名） | system_uptime（float）
cpu_cores（float）
cpu_total（float）
cpu_user（float）
cpu_system（float）
cpu_idle（float）
cpu_wait（float）
LOAD_1min（浮動小数点数）
LOAD_5min（浮動小数点数）
LOAD_15min（浮動小数点数）
filesystem_capacity_total_bytes（int）
filesystem_capacity_used_bytes（int）
filesystem_capacity_free_bytes（int）
filesystem_inode_total（float）
filesystem_inode_used（float）
filesystem_inode_free（float）
memory_total_bytes（int）
memory_free_bytes（int）
memory_buffers_bytes（int）
memory_cached_bytes（int）
swap_total_bytes（int）
swap_free_bytes（int）
swap_used_bytes（int）
network_in_bytes（int）
network_out_bytes（int）
network_in_packets（float）
network_out_packets（float）
network_in_dropped（float）
network_out_dropped（float）
network_in_errors（float）
NETWORK_OUT_ERRORS（float）
process_count（float） 
|===


== トラブルシューティング

追加情報は、にあります link:concept_requesting_support.html["サポート"] ページ
